<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class AgreementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('agreements')->truncate();
        $agreements = [
            [
                'type' => 'Apply without register',
                'description' => json_encode([
                    'pl' => 'Zgoda1',
                    'en' => 'Consent1',
                    'ar' => 'موافقة1',
                    'pt' => 'Consentimento1',
                    'fr' => 'Consentement1',
                    'am' => 'ተፈቃድ1',
                    'es' => 'Consentimiento1',
                    'nl' => 'Toestemming1',
                    'ps' => 'منظوري1',
                    'hy' => 'Համաձայնություն1',
                    'az' => 'Razılıq1',
                    'bn' => 'সন্মতি1',
                    'dz' => 'བསུས་པ1',
                    'ms' => 'Persetujuan1',
                    'zh' => '同意1',
                    'ka' => 'თანხმობა1',
                    'hi' => 'सहमति1',
                    'id' => 'Persetujuan1',
                    'fa' => 'توافق1',
                    'he' => 'הסכמה1',
                    'ja' => '同意1',
                    'km' => 'យល់ព្រម1',
                    'ru' => 'Согласие1',
                    'ko' => '동의1',
                    'lo' => 'ຄວາມຍອມຮັບ1',
                    'dv' => 'ބަހަލަ1',
                    'my' => 'အတည်ပြုခြင်း1',
                    'mn' => 'Зөвшөөрөл1',
                    'ne' => 'स्वीकृति1',
                    'si' => 'අවසරය1',
                    'tg' => 'Ризоият1',
                    'th' => 'ความยินยอม1',
                    'tk' => 'Razılık1',
                    'uz' => 'Rozilik1',
                    'vi' => 'Sự đồng ý1',
                    'sq' => 'Pajtim1',
                    'ca' => 'Consentiment1',
                    'de' => 'Zustimmung1',
                    'be' => 'Згода1',
                    'bs' => 'Suglasnost1',
                    'bg' => 'Съгласие1',
                    'hr' => 'Suglasnost1',
                    'el' => 'Συγκατάθεση1',
                    'me' => 'Saglasnost1',
                    'cs' => 'Souhlas1',
                    'da' => 'Samtykke1',
                    'et' => 'Nõusolek1',
                    'fi' => 'Suostumus1',
                    'is' => 'Samþykki1',
                    'lt' => 'Sutikimas1',
                    'lb' => 'Zoustëmmung1',
                    'lv' => 'Pieņemšana1',
                    'mk' => 'Согласност1',
                    'ro' => 'Consimțământ1',
                    'it' => 'Consenso1',
                    'sr' => 'Suglasnost1',
                    'sk' => 'Súhlas1',
                    'sl' => 'Soglasje1',
                    'no' => 'Samtykke1',
                    'sv' => 'Samtycke1',
                    'tr' => 'Onay1',
                    'uk' => 'Згода1',
                    'hu' => 'Hozzájárulás1'
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
            'type' => 'Apply without register',
            'description' => json_encode([
                'pl' => 'Zgoda2',
                'en' => 'Consent2',
                'ar' => 'موافقة2',
                'pt' => 'Consentimento2',
                'fr' => 'Consentement2',
                'am' => 'ተፈቃድ2',
                'es' => 'Consentimiento2',
                'nl' => 'Toestemming2',
                'ps' => 'منظوري2',
                'hy' => 'Համաձայնություն2',
                'az' => 'Razılıq2',
                'bn' => 'সন্মতি2',
                'dz' => 'བསུས་པ2',
                'ms' => 'Persetujuan2',
                'zh' => '同意2',
                'ka' => 'თანხმობა2',
                'hi' => 'सहमति2',
                'id' => 'Persetujuan2',
                'fa' => 'توافق2',
                'he' => 'הסכמה2',
                'ja' => '同意2',
                'km' => 'យល់ព្រម2',
                'ru' => 'Согласие2',
                'ko' => '동의2',
                'lo' => 'ຄວາມຍອມຮັບ2',
                'dv' => 'ބަހަލަ2',
                'my' => 'အတည်ပြုခြင်း2',
                'mn' => 'Зөвшөөрөл2',
                'ne' => 'स्वीकृति2',
                'si' => 'අවසරය2',
                'tg' => 'Ризоият2',
                'th' => 'ความยินยอม2',
                'tk' => 'Razılık2',
                'uz' => 'Rozilik2',
                'vi' => 'Sự đồng ý2',
                'sq' => 'Pajtim2',
                'ca' => 'Consentiment2',
                'de' => 'Zustimmung2',
                'be' => 'Згода2',
                'bs' => 'Suglasnost2',
                'bg' => 'Съгласие2',
                'hr' => 'Suglasnost2',
                'el' => 'Συγκατάθεση2',
                'me' => 'Saglasnost2',
                'cs' => 'Souhlas2',
                'da' => 'Samtykke2',
                'et' => 'Nõusolek2',
                'fi' => 'Suostumus2',
                'is' => 'Samþykki2',
                'lt' => 'Sutikimas2',
                'lb' => 'Zoustëmmung2',
                'lv' => 'Pieņemšana2',
                'mk' => 'Согласност2',
                'ro' => 'Consimțământ2',
                'it' => 'Consenso2',
                'sr' => 'Suglasnost2',
                'sk' => 'Súhlas2',
                'sl' => 'Soglasje2',
                'no' => 'Samtykke2',
                'sv' => 'Samtycke2',
                'tr' => 'Onay2',
                'uk' => 'Згода2',
                'hu' => 'Hozzájárulás2'
            ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                   'type' => 'Apply without register',
                   'description' => json_encode([
                       'pl' => 'Zgoda3',
                       'en' => 'Consent3',
                       'ar' => 'موافقة3',
                       'pt' => 'Consentimento3',
                       'fr' => 'Consentement3',
                       'am' => 'ተፈቃድ3',
                       'es' => 'Consentimiento3',
                       'nl' => 'Toestemming3',
                       'ps' => 'منظوري3',
                       'hy' => 'Համաձայնություն3',
                       'az' => 'Razılıq3',
                       'bn' => 'সন্মতি3',
                       'dz' => 'བསུས་པ3',
                       'ms' => 'Persetujuan3',
                       'zh' => '同意3',
                       'ka' => 'თანხმობა3',
                       'hi' => 'सहमति3',
                       'id' => 'Persetujuan3',
                       'fa' => 'توافق3',
                       'he' => 'הסכמה3',
                       'ja' => '同意3',
                       'km' => 'យល់ព្រម3',
                       'ru' => 'Согласие3',
                       'ko' => '동의3',
                       'lo' => 'ຄວາມຍອມຮັບ3',
                       'dv' => 'ބަހަލަ3',
                       'my' => 'အတည်ပြုခြင်း3',
                       'mn' => 'Зөвшөөрөл3',
                       'ne' => 'स्वीकृति3',
                       'si' => 'අවසරය3',
                       'tg' => 'Ризоият3',
                       'th' => 'ความยินยอม3',
                       'tk' => 'Razılık3',
                       'uz' => 'Rozilik3',
                       'vi' => 'Sự đồng ý3',
                       'sq' => 'Pajtim3',
                       'ca' => 'Consentiment3',
                       'de' => 'Zustimmung3',
                       'be' => 'Згода3',
                       'bs' => 'Suglasnost3',
                       'bg' => 'Съгласие3',
                       'hr' => 'Suglasnost3',
                       'el' => 'Συγκατάθεση3',
                       'me' => 'Saglasnost3',
                       'cs' => 'Souhlas3',
                       'da' => 'Samtykke3',
                       'et' => 'Nõusolek3',
                       'fi' => 'Suostumus3',
                       'is' => 'Samþykki3',
                       'lt' => 'Sutikimas3',
                       'lb' => 'Zoustëmmung3',
                       'lv' => 'Pieņemšana3',
                       'mk' => 'Согласност3',
                       'ro' => 'Consimțământ3',
                       'it' => 'Consenso3',
                       'sr' => 'Suglasnost3',
                       'sk' => 'Súhlas3',
                       'sl' => 'Soglasje3',
                       'no' => 'Samtykke3',
                       'sv' => 'Samtycke3',
                       'tr' => 'Onay3',
                       'uk' => 'Згода3',
                       'hu' => 'Hozzájárulás3'
                   ]),
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s')
            ],
        ];
        DB::table('agreements')->insert($agreements);
    }
}
