<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class EducationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('education')->truncate();

        $educations = [
            [
                'id' => 1,
                'name' => json_encode([
                    'am' => 'መሠረታዊ', // Amharski
                    'ar' => 'أساسي', // Arabski
                    'az' => 'Əsas', // Azerski
                    'be' => 'Асноўнае', // Białoruski
                    'bg' => 'Основно', // Bułgarski
                    'bn' => 'মৌলিক', // Bengalski
                    'bs' => 'Osnovno', // Bośniacki
                    'ca' => 'Bàsic', // Kataloński
                    'cs' => 'Základní', // Czeski
                    'da' => 'Grundlæggende', // Duński
                    'de' => 'Grundlegend', // Niemiecki
                    'dv' => 'މަޤާމަތް', // Divehi
                    'dz' => 'གནས་གཙོ།', // Dzongkha
                    'el' => 'Βασικό', // Grecki
                    'en' => 'Basic', // Angielski
                    'es' => 'Básico', // Hiszpański
                    'et' => 'Põhiline', // Estoński
                    'fa' => 'پایه', // Perski
                    'fi' => 'Perus', // Fiński
                    'fr' => 'De base', // Francuski
                    'he' => 'בסיסי', // Hebrajski
                    'hi' => 'मूलभूत', // Hindi
                    'hr' => 'Osnovno', // Chorwacki
                    'hu' => 'Alapvető', // Węgierski
                    'hy' => 'Հիմնական', // Ormiański
                    'id' => 'Dasar', // Indonezyjski
                    'is' => 'Grunnur', // Islandzki
                    'it' => 'Base', // Włoski
                    'ja' => '基本的', // Japoński
                    'ka' => 'ძირითადი', // Gruziński
                    'km' => 'មូលដ្ឋាន', // Khmerski
                    'ko' => '기본적인', // Koreański
                    'lb' => 'Grondleeënd', // Luksemburski
                    'lo' => 'ພື້ນຖານ', // Laotański
                    'lt' => 'Pagrindinis', // Litewski
                    'lv' => 'Pamatprincips', // Łotewski
                    'me' => 'Osnovno', // Czarnogórski
                    'mk' => 'Основно', // Macedoński
                    'mn' => 'Үндсэн', // Mongołski
                    'ms' => 'Asas', // Malajski
                    'my' => 'အခြေခံ', // Birmański
                    'ne' => 'आधारभूत', // Nepalski
                    'nl' => 'Basis', // Holenderski
                    'no' => 'Grunnleggende', // Norweski
                    'pl' => 'Podstawowe', // Polski
                    'ps' => 'بنسټيز', // Paszto
                    'pt' => 'Básico', // Portugalski
                    'ro' => 'De bază', // Rumuński
                    'ru' => 'Основное', // Rosyjski
                    'si' => 'මූලික', // Syngaleski
                    'sk' => 'Základné', // Słowacki
                    'sl' => 'Osnovno', // Słoweński
                    'sq' => 'Bazë', // Albański
                    'sr' => 'Основно', // Serbski
                    'sv' => 'Grundläggande', // Szwedzki
                    'tg' => 'Асосӣ', // Tadżycki
                    'th' => 'พื้นฐาน', // Tajski
                    'tk' => 'Esasy', // Turkmeński
                    'tr' => 'Temel', // Turecki
                    'uk' => 'Основне', // Ukraiński
                    'uz' => 'Asosiy', // Uzbecki
                    'vi' => 'Cơ bản', // Wietnamski
                    'zh' => '基本的' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],[
                'id' => 2,
                'name' => json_encode([
                    'am' => 'መካከለኛ', // Amharski
                    'ar' => 'متوسط', // Arabski
                    'az' => 'Orta', // Azerski
                    'be' => 'Сярэдняе', // Białoruski
                    'bg' => 'Средно', // Bułgarski
                    'bn' => 'মাঝারি', // Bengalski
                    'bs' => 'Srednje', // Bośniacki
                    'ca' => 'Mitjà', // Kataloński
                    'cs' => 'Střední', // Czeski
                    'da' => 'Middel', // Duński
                    'de' => 'Mittel', // Niemiecki
                    'dv' => 'މެޑިއަމު', // Divehi
                    'dz' => 'བར་མ།', // Dzongkha
                    'el' => 'Μέσο', // Grecki
                    'en' => 'Medium', // Angielski
                    'es' => 'Medio', // Hiszpański
                    'et' => 'Keskmine', // Estoński
                    'fa' => 'متوسط', // Perski
                    'fi' => 'Keskitaso', // Fiński
                    'fr' => 'Moyen', // Francuski
                    'he' => 'בינוני', // Hebrajski
                    'hi' => 'मध्यम', // Hindi
                    'hr' => 'Srednje', // Chorwacki
                    'hu' => 'Közepes', // Węgierski
                    'hy' => 'Միջին', // Ormiański
                    'id' => 'Sedang', // Indonezyjski
                    'is' => 'Miðlungs', // Islandzki
                    'it' => 'Medio', // Włoski
                    'ja' => '中程度', // Japoński
                    'ka' => 'საშუალო', // Gruziński
                    'km' => 'មធ្យម', // Khmerski
                    'ko' => '중간', // Koreański
                    'lb' => 'Mëttel', // Luksemburski
                    'lo' => 'ລະດັບປານກາງ', // Laotański
                    'lt' => 'Vidutinis', // Litewski
                    'lv' => 'Vidējs', // Łotewski
                    'me' => 'Srednje', // Czarnogórski
                    'mk' => 'Средно', // Macedoński
                    'mn' => 'Дунд', // Mongołski
                    'ms' => 'Sederhana', // Malajski
                    'my' => 'အလတ်စား', // Birmański
                    'ne' => 'मध्यम', // Nepalski
                    'nl' => 'Gemiddeld', // Holenderski
                    'no' => 'Middels', // Norweski
                    'pl' => 'Średnie', // Polski
                    'ps' => 'منځنۍ', // Paszto
                    'pt' => 'Médio', // Portugalski
                    'ro' => 'Mediu', // Rumuński
                    'ru' => 'Среднее', // Rosyjski
                    'si' => 'මධ්‍යම', // Syngaleski
                    'sk' => 'Stredné', // Słowacki
                    'sl' => 'Srednje', // Słoweński
                    'sq' => 'Mesatare', // Albański
                    'sr' => 'Средње', // Serbski
                    'sv' => 'Medel', // Szwedzki
                    'tg' => 'Миёна', // Tadżycki
                    'th' => 'ปานกลาง', // Tajski
                    'tk' => 'Ortaça', // Turkmeński
                    'tr' => 'Orta', // Turecki
                    'uk' => 'Середнє', // Ukraiński
                    'uz' => 'O‘rtacha', // Uzbecki
                    'vi' => 'Trung bình', // Wietnamski
                    'zh' => '中等' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],[
                'id' => 3,
                'name' => json_encode([
                    'am' => 'መካከለኛ ቴክኒካል', // Amharski
                    'ar' => 'متوسط تقني', // Arabski
                    'az' => 'Orta texniki', // Azerski
                    'be' => 'Сярэдняе тэхнічнае', // Białoruski
                    'bg' => 'Средно техническо', // Bułgarski
                    'bn' => 'মাঝারি প্রযুক্তিগত', // Bengalski
                    'bs' => 'Srednje tehničko', // Bośniacki
                    'ca' => 'Mitjà tècnic', // Kataloński
                    'cs' => 'Střední technické', // Czeski
                    'da' => 'Mellemniveau teknisk', // Duński
                    'de' => 'Technisches Mittelniveau', // Niemiecki
                    'dv' => 'މެޑިއަމު ޓެކްނިކަލް', // Divehi
                    'dz' => 'མཐར་སྒྲིག་ཆ་ཚད་དང་སྤྱོད།', // Dzongkha
                    'el' => 'Μεσαίο τεχνικό', // Grecki
                    'en' => 'Technical middle', // Angielski
                    'es' => 'Técnico medio', // Hiszpański
                    'et' => 'Kesktaseme tehniline', // Estoński
                    'fa' => 'متوسط فنی', // Perski
                    'fi' => 'Keskitasoinen tekninen', // Fiński
                    'fr' => 'Technique intermédiaire', // Francuski
                    'he' => 'טכני בינוני', // Hebrajski
                    'hi' => 'मध्यम तकनीकी', // Hindi
                    'hr' => 'Srednje tehničko', // Chorwacki
                    'hu' => 'Középszintű műszaki', // Węgierski
                    'hy' => 'Միջին տեխնիկական', // Ormiański
                    'id' => 'Teknik menengah', // Indonezyjski
                    'is' => 'Miðlungs tæknilegt', // Islandzki
                    'it' => 'Tecnico medio', // Włoski
                    'ja' => '中程度の技術', // Japoński
                    'ka' => 'საშუალო ტექნიკური', // Gruziński
                    'km' => 'បច្ចេកទេសមធ្យម', // Khmerski
                    'ko' => '중급 기술', // Koreański
                    'lb' => 'Technesch mëttel', // Luksemburski
                    'lo' => 'ດ້ານເຕັກນິກລະດັບປານກາງ', // Laotański
                    'lt' => 'Vidutinė techninė', // Litewski
                    'lv' => 'Vidējā tehniskā', // Łotewski
                    'me' => 'Srednje tehničko', // Czarnogórski
                    'mk' => 'Средно техничко', // Macedoński
                    'mn' => 'Дунд техник', // Mongołski
                    'ms' => 'Teknik sederhana', // Malajski
                    'my' => 'အလတ်စား နည်းပညာ', // Birmański
                    'ne' => 'मध्यम प्राविधिक', // Nepalski
                    'nl' => 'Technisch middelbaar', // Holenderski
                    'no' => 'Middels teknisk', // Norweski
                    'pl' => 'Średnie techniczne', // Polski
                    'ps' => 'منځنۍ تخنیکي', // Paszto
                    'pt' => 'Técnico médio', // Portugalski
                    'ro' => 'Tehnic mediu', // Rumuński
                    'ru' => 'Среднее техническое', // Rosyjski
                    'si' => 'මධ්‍යම තාක්ෂණික', // Syngaleski
                    'sk' => 'Stredné technické', // Słowacki
                    'sl' => 'Srednje tehnično', // Słoweński
                    'sq' => 'Teknik mesatar', // Albański
                    'sr' => 'Средње техничко', // Serbski
                    'sv' => 'Tekniskt medel', // Szwedzki
                    'tg' => 'Миёнаи техникӣ', // Tadżycki
                    'th' => 'เทคนิคระดับกลาง', // Tajski
                    'tk' => 'Ortaça tehniki', // Turkmeński
                    'tr' => 'Orta düzey teknik', // Turecki
                    'uk' => 'Середнє технічне', // Ukraiński
                    'uz' => 'O‘rtacha texnik', // Uzbecki
                    'vi' => 'Kỹ thuật trung cấp', // Wietnamski
                    'zh' => '中等技术' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],[
                'id' => 4,
                'name' => json_encode([
                    'am' => 'ሙያዊ', // Amharski
                    'ar' => 'مهني', // Arabski
                    'az' => 'Peşəkar', // Azerski
                    'be' => 'Прафесійнае', // Białoruski
                    'bg' => 'Професионално', // Bułgarski
                    'bn' => 'পেশাদার', // Bengalski
                    'bs' => 'Profesionalno', // Bośniacki
                    'ca' => 'Professional', // Kataloński
                    'cs' => 'Odborné', // Czeski
                    'da' => 'Professionelt', // Duński
                    'de' => 'Beruflich', // Niemiecki
                    'dv' => 'މައުތަމަތް', // Divehi
                    'dz' => 'རིག་ལུས།', // Dzongkha
                    'el' => 'Επαγγελματικό', // Grecki
                    'en' => 'Professional', // Angielski
                    'es' => 'Profesional', // Hiszpański
                    'et' => 'Kutsealane', // Estoński
                    'fa' => 'حرفه‌ای', // Perski
                    'fi' => 'Ammatillinen', // Fiński
                    'fr' => 'Professionnel', // Francuski
                    'he' => 'מקצועי', // Hebrajski
                    'hi' => 'पेशेवर', // Hindi
                    'hr' => 'Stručno', // Chorwacki
                    'hu' => 'Szakmai', // Węgierski
                    'hy' => 'Մասնագիտական', // Ormiański
                    'id' => 'Profesional', // Indonezyjski
                    'is' => 'Starfsferil', // Islandzki
                    'it' => 'Professionale', // Włoski
                    'ja' => '職業的', // Japoński
                    'ka' => 'პროფესიული', // Gruziński
                    'km' => 'វិជ្ជាជីវៈ', // Khmerski
                    'ko' => '전문적인', // Koreański
                    'lb' => 'Berufflech', // Luksemburski
                    'lo' => 'ວິຊາສະເພາະ', // Laotański
                    'lt' => 'Profesionalus', // Litewski
                    'lv' => 'Profesionāls', // Łotewski
                    'me' => 'Profesionalno', // Czarnogórski
                    'mk' => 'Професионално', // Macedoński
                    'mn' => 'Мэргэжлийн', // Mongołski
                    'ms' => 'Profesional', // Malajski
                    'my' => 'ပညာရှင်ဆိုင်ရာ', // Birmański
                    'ne' => 'व्यावसायिक', // Nepalski
                    'nl' => 'Professioneel', // Holenderski
                    'no' => 'Yrkesmessig', // Norweski
                    'pl' => 'Zawodowe', // Polski
                    'ps' => 'مسلکي', // Paszto
                    'pt' => 'Profissional', // Portugalski
                    'ro' => 'Profesional', // Rumuński
                    'ru' => 'Профессиональное', // Rosyjski
                    'si' => 'වෘත්තිය', // Syngaleski
                    'sk' => 'Odborné', // Słowacki
                    'sl' => 'Poklicno', // Słoweński
                    'sq' => 'Profesionale', // Albański
                    'sr' => 'Професионално', // Serbski
                    'sv' => 'Professionell', // Szwedzki
                    'tg' => 'Касбӣ', // Tadżycki
                    'th' => 'ระดับมืออาชีพ', // Tajski
                    'tk' => 'Hünärment', // Turkmeński
                    'tr' => 'Mesleki', // Turecki
                    'uk' => 'Професійне', // Ukraiński
                    'uz' => 'Kasbiy', // Uzbecki
                    'vi' => 'Nghề nghiệp', // Wietnamski
                    'zh' => '职业', // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],[
                'id' => 5,
                'name' => json_encode([
                    'am' => 'ከፍተኛ', // Amharski
                    'ar' => 'أعلى', // Arabski
                    'az' => 'Yüksək', // Azerski
                    'be' => 'Вышэйшае', // Białoruski
                    'bg' => 'По-високо', // Bułgarski
                    'bn' => 'উচ্চতর', // Bengalski
                    'bs' => 'Više', // Bośniacki
                    'ca' => 'Superior', // Kataloński
                    'cs' => 'Vyšší', // Czeski
                    'da' => 'Højere', // Duński
                    'de' => 'Höher', // Niemiecki
                    'dv' => 'ދައްކާ', // Divehi
                    'dz' => 'མཐོ།', // Dzongkha
                    'el' => 'Ανώτερο', // Grecki
                    'en' => 'Higher', // Angielski
                    'es' => 'Superior', // Hiszpański
                    'et' => 'Kõrgem', // Estoński
                    'fa' => 'بالاتر', // Perski
                    'fi' => 'Korkeampi', // Fiński
                    'fr' => 'Supérieur', // Francuski
                    'he' => 'גבוה יותר', // Hebrajski
                    'hi' => 'उच्च', // Hindi
                    'hr' => 'Više', // Chorwacki
                    'hu' => 'Magasabb', // Węgierski
                    'hy' => 'Ավելի բարձր', // Ormiański
                    'id' => 'Lebih tinggi', // Indonezyjski
                    'is' => 'Hærra', // Islandzki
                    'it' => 'Superiore', // Włoski
                    'ja' => '高等', // Japoński
                    'ka' => 'უმაღლესი', // Gruziński
                    'km' => 'ខ្ពស់', // Khmerski
                    'ko' => '더 높은', // Koreański
                    'lb' => 'Méi héich', // Luksemburski
                    'lo' => 'ສູງຂຶ້ນ', // Laotański
                    'lt' => 'Aukštesnis', // Litewski
                    'lv' => 'Augstāks', // Łotewski
                    'me' => 'Više', // Czarnogórski
                    'mk' => 'Високо', // Macedoński
                    'mn' => 'Өндөр', // Mongołski
                    'ms' => 'Lebih tinggi', // Malajski
                    'my' => 'အဆင့်မြင့်', // Birmański
                    'ne' => 'उच्च', // Nepalski
                    'nl' => 'Hoger', // Holenderski
                    'no' => 'Høyere', // Norweski
                    'pl' => 'Wyższe', // Polski
                    'ps' => 'لوړ', // Paszto
                    'pt' => 'Superior', // Portugalski
                    'ro' => 'Mai înalt', // Rumuński
                    'ru' => 'Высшее', // Rosyjski
                    'si' => 'ඉහළ', // Syngaleski
                    'sk' => 'Vyššie', // Słowacki
                    'sl' => 'Višje', // Słoweński
                    'sq' => 'Më i lartë', // Albański
                    'sr' => 'Више', // Serbski
                    'sv' => 'Högre', // Szwedzki
                    'tg' => 'Баландтар', // Tadżycki
                    'th' => 'สูงกว่า', // Tajski
                    'tk' => 'Has', // Turkmeński
                    'tr' => 'Yüksek', // Turecki
                    'uk' => 'Вище', // Ukraiński
                    'uz' => 'Yuqori', // Uzbecki
                    'vi' => 'Cao hơn', // Wietnamski
                    'zh' => '更高', // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ]
        ];

        DB::table('education')->insert($educations);
    }
}
