<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class OfferSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('offers')->truncate();
        $offers = [
            [
                'id' => 1,
                'name' => json_encode([
                    'am' => 'የሥራ አደረጃጀት', // Amharski
                    'ar' => 'عقد عمل', // Arabski
                    'az' => 'Əmək müqaviləsi', // Azerski
                    'be' => 'Працоўная дамова', // Białoruski
                    'bg' => 'Трудов договор', // Bułgarski
                    'bn' => 'চাকরির চুক্তি', // Bengalski
                    'bs' => 'Ugovor o radu', // Bośniacki
                    'ca' => 'Contracte de treball', // Kataloński
                    'cs' => 'Pracovní smlouva', // Czeski
                    'da' => 'Ansættelseskontrakt', // Duński
                    'de' => 'Arbeitsvertrag', // Niemiecki
                    'dv' => 'ބަދަލުކުރެވިފައިވާ ބަޔާން', // Divehi
                    'dz' => 'ལས་གནས་དོ་དམག', // Dzongkha
                    'el' => 'Σύμβαση εργασίας', // Grecki
                    'en' => 'Employment contract', // Angielski
                    'es' => 'Contrato de trabajo', // Hiszpański
                    'et' => 'Tööleping', // Estoński
                    'fa' => 'قرارداد کاری', // Perski
                    'fi' => 'Työsopimus', // Fiński
                    'fr' => 'Contrat de travail', // Francuski
                    'he' => 'חוזה עבודה', // Hebrajski
                    'hi' => 'रोजगार अनुबंध', // Hindi
                    'hr' => 'Ugovor o radu', // Chorwacki
                    'hu' => 'Munkaszerződés', // Węgierski
                    'hy' => 'Աշխատանքի պայմանագիր', // Ormiański
                    'id' => 'Kontrak kerja', // Indonezyjski
                    'is' => 'Ráðningarsamningur', // Islandzki
                    'it' => 'Contratto di lavoro', // Włoski
                    'ja' => '雇用契約', // Japoński
                    'ka' => 'სამუშაო ხელშეკრულება', // Gruziński
                    'km' => 'កិច្ចសន្យាការងារ', // Khmerski
                    'ko' => '고용 계약서', // Koreański
                    'lb' => 'Aarbechtsvertrag', // Luksemburski
                    'lo' => 'ສັນຍາຈ້າງວຽກ', // Laotański
                    'lt' => 'Darbo sutartis', // Litewski
                    'lv' => 'Darba līgums', // Łotewski
                    'me' => 'Ugovor o radu', // Czarnogórski
                    'mk' => 'Договор за вработување', // Macedoński
                    'mn' => 'Ажлын гэрээ', // Mongołski
                    'ms' => 'Kontrak kerja', // Malajski
                    'my' => 'အလုပ်ချုပ်စာချုပ်', // Birmański
                    'ne' => 'रोजगार सम्झौता', // Nepalski
                    'nl' => 'Arbeidsovereenkomst', // Holenderski
                    'no' => 'Arbeidskontrakt', // Norweski
                    'pl' => 'Umowa o pracę', // Polski
                    'ps' => 'د کار تړون', // Paszto
                    'pt' => 'Contrato de trabalho', // Portugalski
                    'ro' => 'Contract de muncă', // Rumuński
                    'ru' => 'Трудовой договор', // Rosyjski
                    'si' => 'රැකියා ගිවිසුම', // Syngaleski
                    'sk' => 'Pracovná zmluva', // Słowacki
                    'sl' => 'Pogodba o zaposlitvi', // Słoweński
                    'sq' => 'Kontratë pune', // Albański
                    'sr' => 'Уговор о раду', // Serbski
                    'sv' => 'Anställningsavtal', // Szwedzki
                    'tg' => 'Шартномаи меҳнатӣ', // Tadżycki
                    'th' => 'สัญญาจ้างงาน', // Tajski
                    'tk' => 'Iş şertnamasy', // Turkmeński
                    'tr' => 'İş sözleşmesi', // Turecki
                    'uk' => 'Трудовий договір', // Ukraiński
                    'uz' => 'Mehnat shartnomasi', // Uzbecki
                    'vi' => 'Hợp đồng lao động', // Wietnamski
                    'zh' => '劳动合同' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],[
                'id' => 2,
                'name' => json_encode([
                    'am' => 'ረጅም ጊዜ መተባበር', // Amharski
                    'ar' => 'تعاون طويل الأمد', // Arabski
                    'az' => 'Uzunmüddətli əməkdaşlıq', // Azerski
                    'be' => 'Даўгатэрміновае супрацоўніцтва', // Białoruski
                    'bg' => 'Дългосрочно сътрудничество', // Bułgarski
                    'bn' => 'দীর্ঘমেয়াদী সহযোগিতা', // Bengalski
                    'bs' => 'Dugoročna saradnja', // Bośniacki
                    'ca' => 'Col·laboració a llarg termini', // Kataloński
                    'cs' => 'Dlouhodobá spolupráce', // Czeski
                    'da' => 'Langsigtet samarbejde', // Duński
                    'de' => 'Langfristige Zusammenarbeit', // Niemiecki
                    'dv' => 'ފަރިޔަފަރާ ފަހަތަކަށް އަދަދަކުރެވިފަ', // Divehi
                    'dz' => 'རིམ་གྲོན་ལོག་འབད།', // Dzongkha
                    'el' => 'Μακροχρόνια συνεργασία', // Grecki
                    'en' => 'Long-term cooperation', // Angielski
                    'es' => 'Colaboración a largo plazo', // Hiszpański
                    'et' => 'Pikaajaline koostöö', // Estoński
                    'fa' => 'همکاری بلندمدت', // Perski
                    'fi' => 'Pitkäaikainen yhteistyö', // Fiński
                    'fr' => 'Collaboration à long terme', // Francuski
                    'he' => 'שיתוף פעולה לטווח ארוך', // Hebrajski
                    'hi' => 'दीर्घकालिक सहयोग', // Hindi
                    'hr' => 'Dugoročna suradnja', // Chorwacki
                    'hu' => 'Hosszú távú együttműködés', // Węgierski
                    'hy' => 'Երկարաժամկետ համագործակցություն', // Ormiański
                    'id' => 'Kerja sama jangka panjang', // Indonezyjski
                    'is' => 'Langtímasamstarf', // Islandzki
                    'it' => 'Collaborazione a lungo termine', // Włoski
                    'ja' => '長期的な協力', // Japoński
                    'ka' => 'გრძელვადიანი თანამშრომლობა', // Gruziński
                    'km' => 'កិច្ចសហប្រតិបត្តិការវែង', // Khmerski
                    'ko' => '장기 협력', // Koreański
                    'lb' => 'Langfristeg Zesummenaarbecht', // Luksemburski
                    'lo' => 'ການຮ່ວມມືລະຍະຍາວ', // Laotański
                    'lt' => 'Ilgalaikis bendradarbiavimas', // Litewski
                    'lv' => 'Ilgtermiņa sadarbība', // Łotewski
                    'me' => 'Dugoročna saradnja', // Czarnogórski
                    'mk' => 'Долгорочна соработка', // Macedoński
                    'mn' => 'Урт хугацааны хамтын ажиллагаа', // Mongołski
                    'ms' => 'Kerjasama jangka panjang', // Malajski
                    'my' => 'ရှည်လျားသောပူးပေါင်းဆောင်ရွက်မှု', // Birmański
                    'ne' => 'दीर्घकालीन सहयोग', // Nepalski
                    'nl' => 'Langdurige samenwerking', // Holenderski
                    'no' => 'Langsiktig samarbeid', // Norweski
                    'pl' => 'Długoterminowa współpraca', // Polski
                    'ps' => 'د اوږدمهاله همکاري', // Paszto
                    'pt' => 'Cooperação a longo prazo', // Portugalski
                    'ro' => 'Colaborare pe termen lung', // Rumuński
                    'ru' => 'Долгосрочное сотрудничество', // Rosyjski
                    'si' => 'දිගුකාලීන සහයෝගය', // Syngaleski
                    'sk' => 'Dlhodobá spolupráca', // Słowacki
                    'sl' => 'Dolgotrajno sodelovanje', // Słoweński
                    'sq' => 'Bashkëpunim afatgjatë', // Albański
                    'sr' => 'Дугорочна сарадња', // Serbski
                    'sv' => 'Långsiktigt samarbete', // Szwedzki
                    'tg' => 'Ҳамкории дарозмуддат', // Tadżycki
                    'th' => 'ความร่วมมือระยะยาว', // Tajski
                    'tk' => 'Uzun möhletli hyzmatdaşlyk', // Turkmeński
                    'tr' => 'Uzun vadeli iş birliği', // Turecki
                    'uk' => 'Довгострокова співпраця', // Ukraiński
                    'uz' => 'Uzoq muddatli hamkorlik', // Uzbecki
                    'vi' => 'Hợp tác dài hạn', // Wietnamski
                    'zh' => '长期合作' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],[
                'id' => 3,
                'name' => json_encode([
                    'am' => 'ምክንያት ያልተጀመረ የሞክር ጊዜ', // Amharski
                    'ar' => 'بدون فترة تجربة', // Arabski
                    'az' => 'Sınaq müddəti yoxdur', // Azerski
                    'be' => 'Без выпрабавальнага тэрміну', // Białoruski
                    'bg' => 'Без изпитателен срок', // Bułgarski
                    'bn' => 'পরীক্ষামূলক সময় নেই', // Bengalski
                    'bs' => 'Bez probnog perioda', // Bośniacki
                    'ca' => 'Sense període de prova', // Kataloński
                    'cs' => 'Žádná zkušební doba', // Czeski
                    'da' => 'Ingen prøvetid', // Duński
                    'de' => 'Keine Probezeit', // Niemiecki
                    'dv' => 'ކަނޑަންކުރެވިދިނުން ބައިވެރިގެ ގަޑިއަކަށް', // Divehi
                    'dz' => 'དཔྱད་མཐོང་དོ་དམག', // Dzongkha
                    'el' => 'Χωρίς δοκιμαστική περίοδο', // Grecki
                    'en' => 'No probation period', // Angielski
                    'es' => 'Sin período de prueba', // Hiszpański
                    'et' => 'Katseaega pole', // Estoński
                    'fa' => 'بدون دوره آزمایشی', // Perski
                    'fi' => 'Ei koeajanjaksoa', // Fiński
                    'fr' => 'Pas de période d\'essai', // Francuski
                    'he' => 'ללא תקופת ניסיון', // Hebrajski
                    'hi' => 'कोई परिवीक्षा अवधि नहीं', // Hindi
                    'hr' => 'Bez probnog roka', // Chorwacki
                    'hu' => 'Nincs próbaidőszak', // Węgierski
                    'hy' => 'Փորձաշրջան չկա', // Ormiański
                    'id' => 'Tidak ada masa percobaan', // Indonezyjski
                    'is' => 'Enginn reynslutími', // Islandzki
                    'it' => 'Nessun periodo di prova', // Włoski
                    'ja' => '試用期間なし', // Japoński
                    'ka' => 'გამოცდის პერიოდი არ არის', // Gruziński
                    'km' => 'គ្មានអាកាសធាតុសាកល្បង', // Khmerski
                    'ko' => '수습 기간 없음', // Koreański
                    'lb' => 'Keng Testperiod', // Luksemburski
                    'lo' => 'ບໍ່ມີໄລຍະທົດລອງ', // Laotański
                    'lt' => 'Be bandomojo laikotarpio', // Litewski
                    'lv' => 'Bez pārbaudes laika', // Łotewski
                    'me' => 'Bez probnog roka', // Czarnogórski
                    'mk' => 'Без пробен период', // Macedoński
                    'mn' => 'Туршилтын хугацаа байхгүй', // Mongołski
                    'ms' => 'Tiada tempoh percubaan', // Malajski
                    'my' => 'စမ်းသပ်ကာလမရှိပါ', // Birmański
                    'ne' => 'परीक्षण अवधि छैन', // Nepalski
                    'nl' => 'Geen proeftijd', // Holenderski
                    'no' => 'Ingen prøvetid', // Norweski
                    'pl' => 'Brak okresu próbnego', // Polski
                    'ps' => 'د آزموینې موده نشته', // Paszto
                    'pt' => 'Sem período de experiência', // Portugalski
                    'ro' => 'Fără perioadă de probă', // Rumuński
                    'ru' => 'Без испытательного срока', // Rosyjski
                    'si' => 'පරීක්ෂාකාලයක් නැත', // Syngaleski
                    'sk' => 'Bez skúšobnej doby', // Słowacki
                    'sl' => 'Brez poskusne dobe', // Słoweński
                    'sq' => 'Pa periudhë prove', // Albański
                    'sr' => 'Без пробног периода', // Serbski
                    'sv' => 'Ingen prövotid', // Szwedzki
                    'tg' => 'Бе давраи санҷишӣ', // Tadżycki
                    'th' => 'ไม่มีระยะทดลองงาน', // Tajski
                    'tk' => 'Synag möhleti ýok', // Turkmeński
                    'tr' => 'Deneme süresi yok', // Turecki
                    'uk' => 'Без випробувального терміну', // Ukraiński
                    'uz' => 'Sinov muddati yoʻq', // Uzbecki
                    'vi' => 'Không có thời gian thử việc', // Wietnamski
                    'zh' => '没有试用期' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 4,
                'name' => json_encode([
                    'am' => 'የቅርብ ግምት ስርዓት', // Amharski
                    'ar' => 'نظام المكافآت', // Arabski
                    'az' => 'Mükafat sistemi', // Azerski
                    'be' => 'Прымяная сістэма', // Białoruski
                    'bg' => 'Бонусна система', // Bułgarski
                    'bn' => 'বোনাস সিস্টেম', // Bengalski
                    'bs' => 'Sistem bonusa', // Bośniacki
                    'ca' => 'Sistema de bonificacions', // Kataloński
                    'cs' => 'Bonusový systém', // Czeski
                    'da' => 'Bonussystem', // Duński
                    'de' => 'Bonussystem', // Niemiecki
                    'dv' => 'ބޮނަސް ސިސްޓަމް', // Divehi
                    'dz' => 'བསྡུར་སྐུལ་འབད་བའི་བརྡ་རྟ།', // Dzongkha
                    'el' => 'Σύστημα μπόνους', // Grecki
                    'en' => 'Bonus system', // Angielski
                    'es' => 'Sistema de bonificaciones', // Hiszpański
                    'et' => 'Boonussüsteem', // Estoński
                    'fa' => 'سیستم پاداش', // Perski
                    'fi' => 'Bonussysteemi', // Fiński
                    'fr' => 'Système de bonus', // Francuski
                    'he' => 'מערכת בונוסים', // Hebrajski
                    'hi' => 'बोनस प्रणाली', // Hindi
                    'hr' => 'Sustav bonusa', // Chorwacki
                    'hu' => 'Bónuszrendszer', // Węgierski
                    'hy' => 'Բոնուսային համակարգ', // Ormiański
                    'id' => 'Sistem bonus', // Indonezyjski
                    'is' => 'Bónuskerfi', // Islandzki
                    'it' => 'Sistema di bonus', // Włoski
                    'ja' => 'ボーナス制度', // Japoński
                    'ka' => 'პრემიის სისტემა', // Gruziński
                    'km' => 'ប្រព័ន្ធប្រាក់លើកទឹកចិត្ត', // Khmerski
                    'ko' => '보너스 시스템', // Koreański
                    'lb' => 'Bonussystem', // Luksemburski
                    'lo' => 'ລະບົບໂບນັດ', // Laotański
                    'lt' => 'Premijų sistema', // Litewski
                    'lv' => 'Bonusu sistēma', // Łotewski
                    'me' => 'Sistem bonusa', // Czarnogórski
                    'mk' => 'Систем на бонуси', // Macedoński
                    'mn' => 'Шагналын систем', // Mongołski
                    'ms' => 'Sistem bonus', // Malajski
                    'my' => 'ဆုကြေးပေးရေးစနစ်', // Birmański
                    'ne' => 'बोनस प्रणाली', // Nepalski
                    'nl' => 'Bonussysteem', // Holenderski
                    'no' => 'Bonussystem', // Norweski
                    'pl' => 'System premiowy', // Polski
                    'ps' => 'د جایزې سیسټم', // Paszto
                    'pt' => 'Sistema de bônus', // Portugalski
                    'ro' => 'Sistem de bonusuri', // Rumuński
                    'ru' => 'Система премий', // Rosyjski
                    'si' => 'ප්‍රේමියම් පද්ධතිය', // Syngaleski
                    'sk' => 'Bonusový systém', // Słowacki
                    'sl' => 'Sistem nagrajevanja', // Słoweński
                    'sq' => 'Sistemi i shpërblimeve', // Albański
                    'sr' => 'Систем бонуса', // Serbski
                    'sv' => 'Bonussystem', // Szwedzki
                    'tg' => 'Системаи бонус', // Tadżycki
                    'th' => 'ระบบโบนัส', // Tajski
                    'tk' => 'Bonus ulgamy', // Turkmeński
                    'tr' => 'Prim sistemi', // Turecki
                    'uk' => 'Бонусна система', // Ukraiński
                    'uz' => 'Bonus tizimi', // Uzbecki
                    'vi' => 'Hệ thống thưởng', // Wietnamski
                    'zh' => '奖金制度' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 5,
                'name' => json_encode([
                    'am' => 'ስልጠናዎች', // Amharski
                    'ar' => 'التدريبات', // Arabski
                    'az' => 'Təlimlər', // Azerski
                    'be' => 'Трэнінгі', // Białoruski
                    'bg' => 'Обучения', // Bułgarski
                    'bn' => 'প্রশিক্ষণ', // Bengalski
                    'bs' => 'Obuke', // Bośniacki
                    'ca' => 'Formacions', // Kataloński
                    'cs' => 'Školení', // Czeski
                    'da' => 'Træning', // Duński
                    'de' => 'Schulungen', // Niemiecki
                    'dv' => 'ދަރަޖަމަޢާތު', // Divehi
                    'dz' => 'ལག་དེབ་སློབ་སྦྱོང་།', // Dzongkha
                    'el' => 'Εκπαιδεύσεις', // Grecki
                    'en' => 'Trainings', // Angielski
                    'es' => 'Formaciones', // Hiszpański
                    'et' => 'Koolitused', // Estoński
                    'fa' => 'آموزش‌ها', // Perski
                    'fi' => 'Koulutukset', // Fiński
                    'fr' => 'Formations', // Francuski
                    'he' => 'הכשרות', // Hebrajski
                    'hi' => 'प्रशिक्षण', // Hindi
                    'hr' => 'Treninzi', // Chorwacki
                    'hu' => 'Képzések', // Węgierski
                    'hy' => 'Դասընթացներ', // Ormiański
                    'id' => 'Pelatihan', // Indonezyjski
                    'is' => 'Þjálfun', // Islandzki
                    'it' => 'Formazioni', // Włoski
                    'ja' => '研修', // Japoński
                    'ka' => 'ტრენინგები', // Gruziński
                    'km' => 'ការបណ្តុះបណ្តាល', // Khmerski
                    'ko' => '훈련', // Koreański
                    'lb' => 'Schoulungen', // Luksemburski
                    'lo' => 'ການຝຶກອົບຮົມ', // Laotański
                    'lt' => 'Mokymai', // Litewski
                    'lv' => 'Apmācības', // Łotewski
                    'me' => 'Obuke', // Czarnogórski
                    'mk' => 'Обуки', // Macedoński
                    'mn' => 'Сургалтууд', // Mongołski
                    'ms' => 'Latihan', // Malajski
                    'my' => 'လေ့ကျင့်မှုများ', // Birmański
                    'ne' => 'प्रशिक्षण', // Nepalski
                    'nl' => 'Trainingen', // Holenderski
                    'no' => 'Opplæring', // Norweski
                    'pl' => 'Szkolenia', // Polski
                    'ps' => 'روزنې', // Paszto
                    'pt' => 'Treinamentos', // Portugalski
                    'ro' => 'Traininguri', // Rumuński
                    'ru' => 'Обучение', // Rosyjski
                    'si' => 'පුහුණු', // Syngaleski
                    'sk' => 'Školenia', // Słowacki
                    'sl' => 'Usposabljanja', // Słoweński
                    'sq' => 'Trajnime', // Albański
                    'sr' => 'Тренинзи', // Serbski
                    'sv' => 'Utbildningar', // Szwedzki
                    'tg' => 'Омӯзишҳо', // Tadżycki
                    'th' => 'การฝึกอบรม', // Tajski
                    'tk' => 'Tälimler', // Turkmeński
                    'tr' => 'Eğitimler', // Turecki
                    'uk' => 'Тренінги', // Ukraiński
                    'uz' => 'Treninglar', // Uzbecki
                    'vi' => 'Đào tạo', // Wietnamski
                    'zh' => '培训' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],[
                'id' => 6,
                'name' => json_encode([
                    'am' => 'የሙያ አላማ መድረሻ እድል', // Amharski
                    'ar' => 'إمكانية الترقية المهنية', // Arabski
                    'az' => 'Peşəkar yüksəliş imkanı', // Azerski
                    'be' => 'Магчымасць кар\'ернага росту', // Białoruski
                    'bg' => 'Възможност за професионално развитие', // Bułgarski
                    'bn' => 'পেশাগত উন্নতির সুযোগ', // Bengalski
                    'bs' => 'Mogućnost profesionalnog napredovanja', // Bośniacki
                    'ca' => 'Oportunitat de promoció professional', // Kataloński
                    'cs' => 'Možnost profesního postupu', // Czeski
                    'da' => 'Mulighed for karrierefremgang', // Duński
                    'de' => 'Karriereaufstiegsmöglichkeit', // Niemiecki
                    'dv' => 'މައްސަލަ އަވަންސްކޮށްފައިވާ އަދަދަކުރެވިފައިވާ', // Divehi
                    'dz' => 'གུ་ཡིག་སྤེལ་འབད་ཐབས་ཡོད།', // Dzongkha
                    'el' => 'Δυνατότητα επαγγελματικής εξέλιξης', // Grecki
                    'en' => 'Career advancement opportunity', // Angielski
                    'es' => 'Oportunidad de ascenso profesional', // Hiszpański
                    'et' => 'Karjääri edendamise võimalus', // Estoński
                    'fa' => 'فرصت پیشرفت شغلی', // Perski
                    'fi' => 'Mahdollisuus uralla etenemiseen', // Fiński
                    'fr' => 'Possibilité d\'avancement professionnel', // Francuski
                    'he' => 'אפשרות לקידום מקצועי', // Hebrajski
                    'hi' => 'पेशेवर उन्नति का अवसर', // Hindi
                    'hr' => 'Mogućnost profesionalnog napretka', // Chorwacki
                    'hu' => 'Szakmai előrelépési lehetőség', // Węgierski
                    'hy' => 'Մասնագիտական առաջխաղացման հնարավորություն', // Ormiański
                    'id' => 'Peluang kemajuan karier', // Indonezyjski
                    'is' => 'Framfaratækifæri í starfi', // Islandzki
                    'it' => 'Possibilità di avanzamento professionale', // Włoski
                    'ja' => 'キャリアアップの可能性', // Japoński
                    'ka' => 'პროფესიული წინსვლის შესაძლებლობა', // Gruziński
                    'km' => 'ឱកាសជកះប្រជុំវិជ្ជាជីវៈ', // Khmerski
                    'ko' => '직업적 승진 기회', // Koreański
                    'lb' => 'Méiglechkeet fir berufflech Opstig', // Luksemburski
                    'lo' => 'ໂອກາດເພີ່ມລະດັບວຽກງານ', // Laotański
                    'lt' => 'Galimybė karjeros augimui', // Litewski
                    'lv' => 'Iespēja profesionālai izaugsmei', // Łotewski
                    'me' => 'Mogućnost profesionalnog napredovanja', // Czarnogórski
                    'mk' => 'Можност за професионален напредок', // Macedoński
                    'mn' => 'Мэргэжлийн дэвшлийн боломж', // Mongołski
                    'ms' => 'Peluang kenaikan pangkat', // Malajski
                    'my' => 'အလုပ်အကိုင်တိုးတက်မှုအခွင့်အလမ်း', // Birmański
                    'ne' => 'पेशागत उन्नति गर्ने अवसर', // Nepalski
                    'nl' => 'Mogelijkheid tot professionele vooruitgang', // Holenderski
                    'no' => 'Mulighet for karriereutvikling', // Norweski
                    'pl' => 'Możliwość awansu zawodowego', // Polski
                    'ps' => 'د مسلکي پرمختګ فرصت', // Paszto
                    'pt' => 'Oportunidade de progressão na carreira', // Portugalski
                    'ro' => 'Posibilitate de avansare profesională', // Rumuński
                    'ru' => 'Возможность карьерного роста', // Rosyjski
                    'si' => 'වෘත්තීය උසස්වීමේ අවස්ථාව', // Syngaleski
                    'sk' => 'Možnosť kariérneho postupu', // Słowacki
                    'sl' => 'Možnost poklicnega napredovanja', // Słoweński
                    'sq' => 'Mundësi për avancim profesional', // Albański
                    'sr' => 'Могућност професионалног напредовања', // Serbski
                    'sv' => 'Möjlighet till karriärutveckling', // Szwedzki
                    'tg' => 'Имконияти пешрафти касбӣ', // Tadżycki
                    'th' => 'โอกาสก้าวหน้าในอาชีพ', // Tajski
                    'tk' => 'Kärýera ösüş mümkinçilikleri', // Turkmeński
                    'tr' => 'Kariyer ilerleme fırsatı', // Turecki
                    'uk' => 'Можливість кар\'єрного росту', // Ukraiński
                    'uz' => 'Kasbiy o‘sish imkoniyati', // Uzbecki
                    'vi' => 'Cơ hội thăng tiến nghề nghiệp', // Wietnamski
                    'zh' => '职业发展机会' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 7,
                'name' => json_encode([
                    'am' => 'የተለመነ የሥራ ሰዓት', // Amharski
                    'ar' => 'وقت عمل مرن', // Arabski
                    'az' => 'Elastik iş vaxtı', // Azerski
                    'be' => 'Гнуткі графік працы', // Białoruski
                    'bg' => 'Гъвкаво работно време', // Bułgarski
                    'bn' => 'নমনীয় কাজের সময়', // Bengalski
                    'bs' => 'Fleksibilno radno vrijeme', // Bośniacki
                    'ca' => 'Horari laboral flexible', // Kataloński
                    'cs' => 'Flexibilní pracovní doba', // Czeski
                    'da' => 'Fleksibel arbejdstid', // Duński
                    'de' => 'Flexible Arbeitszeiten', // Niemiecki
                    'dv' => 'ފްލެކްސިބަލް މައްސަލަ ގަޑި', // Divehi
                    'dz' => 'རྒྱབ་རྩོད་ཆུ་ཚོད་ལྷག་བསྡུར།', // Dzongkha
                    'el' => 'Ευέλικτο ωράριο εργασίας', // Grecki
                    'en' => 'Flexible working hours', // Angielski
                    'es' => 'Horario de trabajo flexible', // Hiszpański
                    'et' => 'Paindlik tööaeg', // Estoński
                    'fa' => 'ساعات کاری انعطاف‌پذیر', // Perski
                    'fi' => 'Joustavat työajat', // Fiński
                    'fr' => 'Horaires de travail flexibles', // Francuski
                    'he' => 'שעות עבודה גמישות', // Hebrajski
                    'hi' => 'लचीला कार्य समय', // Hindi
                    'hr' => 'Fleksibilno radno vrijeme', // Chorwacki
                    'hu' => 'Rugalmas munkaidő', // Węgierski
                    'hy' => 'Ճկուն աշխատանքային ժամանակ', // Ormiański
                    'id' => 'Jam kerja fleksibel', // Indonezyjski
                    'is' => 'Sveigjanlegur vinnutími', // Islandzki
                    'it' => 'Orario di lavoro flessibile', // Włoski
                    'ja' => '柔軟な勤務時間', // Japoński
                    'ka' => 'მოქნილი სამუშაო დრო', // Gruziński
                    'km' => 'ម៉ោងធ្វើការស្រួលបត់', // Khmerski
                    'ko' => '유연한 근무 시간', // Koreański
                    'lb' => 'Flexibel Aarbechtszäit', // Luksemburski
                    'lo' => 'ເວລາເຮັດວຽກທີ່ຍືດຍຸ່ນ', // Laotański
                    'lt' => 'Lankstus darbo laikas', // Litewski
                    'lv' => 'Elastīgs darba laiks', // Łotewski
                    'me' => 'Fleksibilno radno vrijeme', // Czarnogórski
                    'mk' => 'Флексибилно работно време', // Macedoński
                    'mn' => 'Уян хатан ажлын цаг', // Mongołski
                    'ms' => 'Waktu kerja fleksibel', // Malajski
                    'my' => 'ပြောင်းလွယ်ပြင်လွယ် အလုပ်ချိန်', // Birmański
                    'ne' => 'लचिलो काम समय', // Nepalski
                    'nl' => 'Flexibele werktijden', // Holenderski
                    'no' => 'Fleksibel arbeidstid', // Norweski
                    'pl' => 'Elastyczny czas pracy', // Polski
                    'ps' => 'انعطاف وړ کاري وختونه', // Paszto
                    'pt' => 'Horário de trabalho flexível', // Portugalski
                    'ro' => 'Program de lucru flexibil', // Rumuński
                    'ru' => 'Гибкий график работы', // Rosyjski
                    'si' => 'සාමූහික කාර්ය මුරය', // Syngaleski
                    'sk' => 'Flexibilný pracovný čas', // Słowacki
                    'sl' => 'Prilagodljiv delovni čas', // Słoweński
                    'sq' => 'Orar fleksibël pune', // Albański
                    'sr' => 'Флексибилно радно време', // Serbski
                    'sv' => 'Flexibla arbetstider', // Szwedzki
                    'tg' => 'Соатҳои кории чандир', // Tadżycki
                    'th' => 'เวลาทำงานที่ยืดหยุ่น', // Tajski
                    'tk' => 'Çeýe iş wagty', // Turkmeński
                    'tr' => 'Esnek çalışma saatleri', // Turecki
                    'uk' => 'Гнучкий робочий час', // Ukraiński
                    'uz' => 'Moslashuvchan ish vaqti', // Uzbecki
                    'vi' => 'Giờ làm việc linh hoạt', // Wietnamski
                    'zh' => '灵活工作时间' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 8,
                'name' => json_encode([
                    'am' => 'እንቅስቃሴ ማድረግ የሚቻል ቦታ ውስጥ ስራ ማከናወን', // Amharski
                    'ar' => 'إمكانية العمل عن بعد', // Arabski
                    'az' => 'Uzaqdan işləmə imkanı', // Azerski
                    'be' => 'Магчымасць працы аддалена', // Białoruski
                    'bg' => 'Възможност за дистанционна работа', // Bułgarski
                    'bn' => 'দূরবর্তী কাজের সুযোগ', // Bengalski
                    'bs' => 'Mogućnost rada na daljinu', // Bośniacki
                    'ca' => 'Possibilitat de treballar a distància', // Kataloński
                    'cs' => 'Možnost práce na dálku', // Czeski
                    'da' => 'Mulighed for fjernarbejde', // Duński
                    'de' => 'Möglichkeit für Remote-Arbeit', // Niemiecki
                    'dv' => 'ޑިސްޓެންސް ވަރުދާއަށް ފަހަތަކަށް އަދަދަކުރެވިފަ', // Divehi
                    'dz' => 'དགའ་རོགས་བསྐྱར་གསར་སྤྱོད་ཆེན་ཞུ་འཕྲིན།', // Dzongkha
                    'el' => 'Δυνατότητα απομακρυσμένης εργασίας', // Grecki
                    'en' => 'Possibility of remote work', // Angielski
                    'es' => 'Posibilidad de trabajo remoto', // Hiszpański
                    'et' => 'Võimalus kaugtööks', // Estoński
                    'fa' => 'امکان کار از راه دور', // Perski
                    'fi' => 'Mahdollisuus etätyöhön', // Fiński
                    'fr' => 'Possibilité de télétravail', // Francuski
                    'he' => 'אפשרות לעבודה מרחוק', // Hebrajski
                    'hi' => 'दूरस्थ कार्य की संभावना', // Hindi
                    'hr' => 'Mogućnost rada na daljinu', // Chorwacki
                    'hu' => 'Távmunkavégzés lehetősége', // Węgierski
                    'hy' => 'Հեռահար աշխատանքի հնարավորություն', // Ormiański
                    'id' => 'Kemungkinan kerja jarak jauh', // Indonezyjski
                    'is' => 'Möguleiki á fjarvinnu', // Islandzki
                    'it' => 'Possibilità di lavoro da remoto', // Włoski
                    'ja' => 'リモートワークの可能性', // Japoński
                    'ka' => 'დისტანციური მუშაობის შესაძლებლობა', // Gruziński
                    'km' => 'ឱកាសធ្វើការចេញពីផ្ទះ', // Khmerski
                    'ko' => '원격 근무 가능성', // Koreański
                    'lb' => 'Méiglechkeet vun doheem ze schaffen', // Luksemburski
                    'lo' => 'ຄວາມເປັນໄປໄດ້ໃນການເຮັດວຽກທາງໄກ', // Laotański
                    'lt' => 'Nuotolinio darbo galimybė', // Litewski
                    'lv' => 'Iespēja strādāt attālināti', // Łotewski
                    'me' => 'Mogućnost rada na daljinu', // Czarnogórski
                    'mk' => 'Можност за работа од далечина', // Macedoński
                    'mn' => 'Холын ажил хийх боломж', // Mongołski
                    'ms' => 'Kemungkinan bekerja dari jauh', // Malajski
                    'my' => 'အဝေးမှအလုပ်လုပ်နိုင်မည့်အခွင့်အလမ်း', // Birmański
                    'ne' => 'दूरबाट काम गर्ने सम्भावना', // Nepalski
                    'nl' => 'Mogelijkheid tot remote werken', // Holenderski
                    'no' => 'Mulighet for fjernarbeid', // Norweski
                    'pl' => 'Możliwość pracy zdalnej', // Polski
                    'ps' => 'د لیرې پرتو کار کولو امکان', // Paszto
                    'pt' => 'Possibilidade de trabalho remoto', // Portugalski
                    'ro' => 'Posibilitatea de a lucra de la distanță', // Rumuński
                    'ru' => 'Возможность удаленной работы', // Rosyjski
                    'si' => 'දුරස්ථව සේවය කිරීමේ හැකියාව', // Syngaleski
                    'sk' => 'Možnosť práce na diaľku', // Słowacki
                    'sl' => 'Možnost dela na daljavo', // Słoweński
                    'sq' => 'Mundësia e punës nga distanca', // Albański
                    'sr' => 'Могућност рада на даљину', // Serbski
                    'sv' => 'Möjlighet till distansarbete', // Szwedzki
                    'tg' => 'Имконияти кори фосила', // Tadżycki
                    'th' => 'ความเป็นไปได้ในการทำงานทางไกล', // Tajski
                    'tk' => 'Uzakdan işlem ähtimallygy', // Turkmeński
                    'tr' => 'Uzaktan çalışma imkanı', // Turecki
                    'uk' => 'Можливість віддаленої роботи', // Ukraiński
                    'uz' => 'Masofadan ishlash imkoniyati', // Uzbecki
                    'vi' => 'Khả năng làm việc từ xa', // Wietnamski
                    'zh' => '远程工作的可能性' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 9,
                'name' => json_encode([
                    'am' => 'የግል ሕክምና እንክብካቤ', // Amharski
                    'ar' => 'رعاية طبية خاصة', // Arabski
                    'az' => 'Özəl tibbi xidmət', // Azerski
                    'be' => 'Прыватнае медыцынскае абслугоўванне', // Białoruski
                    'bg' => 'Частна медицинска грижа', // Bułgarski
                    'bn' => 'ব্যক্তিগত চিকিৎসা সেবা', // Bengalski
                    'bs' => 'Privatna medicinska njega', // Bośniacki
                    'ca' => 'Atenció mèdica privada', // Kataloński
                    'cs' => 'Soukromá lékařská péče', // Czeski
                    'da' => 'Privat medicinsk pleje', // Duński
                    'de' => 'Private medizinische Versorgung', // Niemiecki
                    'dv' => 'ޕްރަޔަވެޓް މެޑިކަލް ކެއަރު', // Divehi
                    'dz' => 'ཐོག་མར་གཞིས་བསྟེན་དང་གཅེས་བསྟེན།', // Dzongkha
                    'el' => 'Ιδιωτική ιατρική περίθαλψη', // Grecki
                    'en' => 'Private medical care', // Angielski
                    'es' => 'Atención médica privada', // Hiszpański
                    'et' => 'Privaatne arstiabi', // Estoński
                    'fa' => 'مراقبت پزشکی خصوصی', // Perski
                    'fi' => 'Yksityinen sairaanhoito', // Fiński
                    'fr' => 'Soins médicaux privés', // Francuski
                    'he' => 'טיפול רפואי פרטי', // Hebrajski
                    'hi' => 'निजी चिकित्सा देखभाल', // Hindi
                    'hr' => 'Privatna medicinska skrb', // Chorwacki
                    'hu' => 'Magán egészségügyi ellátás', // Węgierski
                    'hy' => 'Մասնավոր բժշկական խնամք', // Ormiański
                    'id' => 'Perawatan medis pribadi', // Indonezyjski
                    'is' => 'Einkarekin heilbrigðisþjónusta', // Islandzki
                    'it' => 'Assistenza medica privata', // Włoski
                    'ja' => 'プライベート医療ケア', // Japoński
                    'ka' => 'პირადი სამედიცინო ზრუნვა', // Gruziński
                    'km' => 'ការថែទាំសុខភាពឯកជន', // Khmerski
                    'ko' => '개인 의료 서비스', // Koreański
                    'lb' => 'Privat medezinesch Betreiung', // Luksemburski
                    'lo' => 'ການດູແລທາງການແພດສ່ວນຕົວ', // Laotański
                    'lt' => 'Privati medicininė priežiūra', // Litewski
                    'lv' => 'Privāta medicīniskā aprūpe', // Łotewski
                    'me' => 'Privatna medicinska njega', // Czarnogórski
                    'mk' => 'Приватна медицинска грижа', // Macedoński
                    'mn' => 'Хувийн эмнэлгийн үйлчилгээ', // Mongołski
                    'ms' => 'Penjagaan perubatan peribadi', // Malajski
                    'my' => 'ကိုယ်ပိုင်ဆေးကုသမှု', // Birmański
                    'ne' => 'निजी चिकित्सा हेरचाह', // Nepalski
                    'nl' => 'Particuliere medische zorg', // Holenderski
                    'no' => 'Privat medisinsk omsorg', // Norweski
                    'pl' => 'Prywatna opieka medyczna', // Polski
                    'ps' => 'شخصي طبي پاملرنه', // Paszto
                    'pt' => 'Cuidados médicos privados', // Portugalski
                    'ro' => 'Îngrijire medicală privată', // Rumuński
                    'ru' => 'Частная медицинская помощь', // Rosyjski
                    'si' => 'පෞද්ගලික වෛද්‍ය සේවාව', // Syngaleski
                    'sk' => 'Súkromná zdravotná starostlivosť', // Słowacki
                    'sl' => 'Zasebna zdravstvena oskrba', // Słoweński
                    'sq' => 'Kujdesi mjekësor privat', // Albański
                    'sr' => 'Приватна медицинска нега', // Serbski
                    'sv' => 'Privat medicinsk vård', // Szwedzki
                    'tg' => 'Тиббии хусусӣ', // Tadżycki
                    'th' => 'การดูแลทางการแพทย์ส่วนตัว', // Tajski
                    'tk' => 'Hususy lukmançylyk hyzmaty', // Turkmeński
                    'tr' => 'Özel sağlık hizmeti', // Turecki
                    'uk' => 'Приватна медична допомога', // Ukraiński
                    'uz' => 'Shaxsiy tibbiy xizmat', // Uzbecki
                    'vi' => 'Chăm sóc y tế tư nhân', // Wietnamski
                    'zh' => '私人医疗护理' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 10,
                'name' => json_encode([
                    'am' => 'ስፖርት ካርድ', // Amharski
                    'ar' => 'بطاقة رياضية', // Arabski
                    'az' => 'İdman kartı', // Azerski
                    'be' => 'Спартыўная карта', // Białoruski
                    'bg' => 'Спортна карта', // Bułgarski
                    'bn' => 'খেলাধুলার কার্ড', // Bengalski
                    'bs' => 'Sportska kartica', // Bośniacki
                    'ca' => 'Targeta esportiva', // Kataloński
                    'cs' => 'Sportovní karta', // Czeski
                    'da' => 'Sportskort', // Duński
                    'de' => 'Sportkarte', // Niemiecki
                    'dv' => 'ސްޕޯރޓް ކާރޑު', // Divehi
                    'dz' => 'གུ་ཡིག་སྤྱོད་ཆེན།', // Dzongkha
                    'el' => 'Αθλητική κάρτα', // Grecki
                    'en' => 'Sports card', // Angielski
                    'es' => 'Tarjeta deportiva', // Hiszpański
                    'et' => 'Spordikaart', // Estoński
                    'fa' => 'کارت ورزشی', // Perski
                    'fi' => 'Urheilukortti', // Fiński
                    'fr' => 'Carte sportive', // Francuski
                    'he' => 'כרטיס ספורט', // Hebrajski
                    'hi' => 'खेल कार्ड', // Hindi
                    'hr' => 'Sportska kartica', // Chorwacki
                    'hu' => 'Sportkártya', // Węgierski
                    'hy' => 'Սպորտային քարտ', // Ormiański
                    'id' => 'Kartu olahraga', // Indonezyjski
                    'is' => 'Íþróttakort', // Islandzki
                    'it' => 'Carta sportiva', // Włoski
                    'ja' => 'スポーツカード', // Japoński
                    'ka' => 'სპორტული ბარათი', // Gruziński
                    'km' => 'បណ្ណកីឡា', // Khmerski
                    'ko' => '스포츠 카드', // Koreański
                    'lb' => 'Sportkaart', // Luksemburski
                    'lo' => 'ບັດກິລາ', // Laotański
                    'lt' => 'Sporto kortelė', // Litewski
                    'lv' => 'Sporta karte', // Łotewski
                    'me' => 'Sportska kartica', // Czarnogórski
                    'mk' => 'Спортска карта', // Macedoński
                    'mn' => 'Спортын карт', // Mongołski
                    'ms' => 'Kad sukan', // Malajski
                    'my' => 'အားကစားကဒ်', // Birmański
                    'ne' => 'खेल कार्ड', // Nepalski
                    'nl' => 'Sportkaart', // Holenderski
                    'no' => 'Idrettskort', // Norweski
                    'pl' => 'Karta sportowa', // Polski
                    'ps' => 'د سپورت کارت', // Paszto
                    'pt' => 'Cartão desportivo', // Portugalski
                    'ro' => 'Card sportiv', // Rumuński
                    'ru' => 'Спортивная карта', // Rosyjski
                    'si' => 'ක්‍රීඩා කාඩ්පත', // Syngaleski
                    'sk' => 'Športová karta', // Słowacki
                    'sl' => 'Športna kartica', // Słoweński
                    'sq' => 'Kartë sportive', // Albański
                    'sr' => 'Спортска картица', // Serbski
                    'sv' => 'Sportkort', // Szwedzki
                    'tg' => 'Корти варзишӣ', // Tadżycki
                    'th' => 'บัตรกีฬา', // Tajski
                    'tk' => 'Sport karty', // Turkmeński
                    'tr' => 'Spor kartı', // Turecki
                    'uk' => 'Спортивна картка', // Ukraiński
                    'uz' => 'Sport kartasi', // Uzbecki
                    'vi' => 'Thẻ thể thao', // Wietnamski
                    'zh' => '运动卡' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 11,
                'name' => json_encode([
                    'am' => 'ለምግብ ድጋፍ', // Amharski
                    'ar' => 'تمويل الوجبات', // Arabski
                    'az' => 'Yemək üçün maliyyə dəstəyi', // Azerski
                    'be' => 'Субсідыі на харчаванне', // Białoruski
                    'bg' => 'Финансова подкрепа за храна', // Bułgarski
                    'bn' => 'খাবারের জন্য আর্থিক সহায়তা', // Bengalski
                    'bs' => 'Subvencija za obroke', // Bośniacki
                    'ca' => 'Subvenció per a àpats', // Kataloński
                    'cs' => 'Příspěvek na stravování', // Czeski
                    'da' => 'Tilskud til måltider', // Duński
                    'de' => 'Essenszuschuss', // Niemiecki
                    'dv' => 'ހަރަކާތަކުން ދަނޑަ އަދަދަކުރެވިފައިވާ', // Divehi
                    'dz' => 'ཟས་བཅོས་རག་སྤྲོས།', // Dzongkha
                    'el' => 'Επιχορήγηση για γεύματα', // Grecki
                    'en' => 'Meal subsidy', // Angielski
                    'es' => 'Subvención para comidas', // Hiszpański
                    'et' => 'Toidutoetus', // Estoński
                    'fa' => 'یارانه غذا', // Perski
                    'fi' => 'Ateriakorvaus', // Fiński
                    'fr' => 'Subvention pour les repas', // Francuski
                    'he' => 'מימון לארוחות', // Hebrajski
                    'hi' => 'भोजन के लिए अनुदान', // Hindi
                    'hr' => 'Subvencija za obroke', // Chorwacki
                    'hu' => 'Étkezési támogatás', // Węgierski
                    'hy' => 'Սննդի ֆինանսավորում', // Ormiański
                    'id' => 'Subsidi makanan', // Indonezyjski
                    'is' => 'Máltíðastyrkur', // Islandzki
                    'it' => 'Contributo per i pasti', // Włoski
                    'ja' => '食事補助', // Japoński
                    'ka' => 'კვების დაფინანსება', // Gruziński
                    'km' => 'ជំនួយសម្រាប់អាហារ', // Khmerski
                    'ko' => '식사 보조금', // Koreański
                    'lb' => 'Subsidiär fir Iessen', // Luksemburski
                    'lo' => 'ເງິນສະໜັບສະໜູນສໍາລັບອາຫານ', // Laotański
                    'lt' => 'Maisto subsidija', // Litewski
                    'lv' => 'Atbalsts maltītēm', // Łotewski
                    'me' => 'Subvencija za obroke', // Czarnogórski
                    'mk' => 'Субвенција за оброци', // Macedoński
                    'mn' => 'Хоолны тэтгэлэг', // Mongołski
                    'ms' => 'Subsidi makanan', // Malajski
                    'my' => 'အစားအသောက်အတွက်အထောက်အပံ့', // Birmański
                    'ne' => 'खानाको लागि आर्थिक सहायता', // Nepalski
                    'nl' => 'Maaltijdsubsidie', // Holenderski
                    'no' => 'Måltidstilskudd', // Norweski
                    'pl' => 'Dofinansowanie do posiłków', // Polski
                    'ps' => 'د خواړو لپاره مالي مرسته', // Paszto
                    'pt' => 'Subsídio para refeições', // Portugalski
                    'ro' => 'Subvenție pentru mese', // Rumuński
                    'ru' => 'Субсидия на питание', // Rosyjski
                    'si' => 'ආහාර සඳහා ආධාර', // Syngaleski
                    'sk' => 'Príspevok na stravu', // Słowacki
                    'sl' => 'Subvencija za obroke', // Słoweński
                    'sq' => 'Subvencion për ushqimet', // Albański
                    'sr' => 'Субвенција за оброке', // Serbski
                    'sv' => 'Måltidssubvention', // Szwedzki
                    'tg' => 'Кумак ба ғизо', // Tadżycki
                    'th' => 'เงินช่วยค่าอาหาร', // Tajski
                    'tk' => 'Iýmit subsidiýasy', // Turkmeński
                    'tr' => 'Yemek desteği', // Turecki
                    'uk' => 'Субсидія на харчування', // Ukraiński
                    'uz' => 'Ovqatga subsidiya', // Uzbecki
                    'vi' => 'Trợ cấp bữa ăn', // Wietnamski
                    'zh' => '餐补' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 12,
                'name' => json_encode([
                    'am' => 'ቢሮ በከተማ ማዕከል', // Amharski
                    'ar' => 'مكتب في وسط المدينة', // Arabski
                    'az' => 'Şəhərin mərkəzində ofis', // Azerski
                    'be' => 'Офіс у цэнтры горада', // Białoruski
                    'bg' => 'Офис в центъра на града', // Bułgarski
                    'bn' => 'শহরের কেন্দ্রস্থলে অফিস', // Bengalski
                    'bs' => 'Kancelarija u centru grada', // Bośniacki
                    'ca' => 'Oficina al centre de la ciutat', // Kataloński
                    'cs' => 'Kancelář v centru města', // Czeski
                    'da' => 'Kontor i byens centrum', // Duński
                    'de' => 'Büro im Stadtzentrum', // Niemiecki
                    'dv' => 'މީނާއިން ބޭނުމަކީން އޮފިސް', // Divehi
                    'dz' => 'གྲངས་མཐོང་བཞུགས་གནས།', // Dzongkha
                    'el' => 'Γραφείο στο κέντρο της πόλης', // Grecki
                    'en' => 'Office in the city center', // Angielski
                    'es' => 'Oficina en el centro de la ciudad', // Hiszpański
                    'et' => 'Kontor linna keskuses', // Estoński
                    'fa' => 'دفتر در مرکز شهر', // Perski
                    'fi' => 'Toimisto kaupungin keskustassa', // Fiński
                    'fr' => 'Bureau au centre-ville', // Francuski
                    'he' => 'משרד במרכז העיר', // Hebrajski
                    'hi' => 'शहर के केंद्र में कार्यालय', // Hindi
                    'hr' => 'Ured u centru grada', // Chorwacki
                    'hu' => 'Iroda a városközpontban', // Węgierski
                    'hy' => 'Գրասենյակ քաղաքի կենտրոնում', // Ormiański
                    'id' => 'Kantor di pusat kota', // Indonezyjski
                    'is' => 'Skrifstofa í miðbænum', // Islandzki
                    'it' => 'Ufficio nel centro città', // Włoski
                    'ja' => '市内中心部のオフィス', // Japoński
                    'ka' => 'ოფისი ქალაქის ცენტრში', // Gruziński
                    'km' => 'ការិយាល័យនៅកណ្តាលទីក្រុង', // Khmerski
                    'ko' => '도심에 위치한 사무실', // Koreański
                    'lb' => 'Büro am Stadzentrum', // Luksemburski
                    'lo' => 'ສະຫະວິສະຫະນາໃນກາງເມືອງ', // Laotański
                    'lt' => 'Biuras miesto centre', // Litewski
                    'lv' => 'Birojs pilsētas centrā', // Łotewski
                    'me' => 'Kancelarija u centru grada', // Czarnogórski
                    'mk' => 'Канцеларија во центарот на градот', // Macedoński
                    'mn' => 'Хотын төвд оффис', // Mongołski
                    'ms' => 'Pejabat di pusat bandar', // Malajski
                    'my' => 'မြို့အလယ်ဗဟိုရှိရုံး', // Birmański
                    'ne' => 'शहरको केन्द्रमा कार्यालय', // Nepalski
                    'nl' => 'Kantoor in het stadscentrum', // Holenderski
                    'no' => 'Kontor i sentrum av byen', // Norweski
                    'pl' => 'Biuro w centrum miasta', // Polski
                    'ps' => 'په ښار کې مرکزي دفتر', // Paszto
                    'pt' => 'Escritório no centro da cidade', // Portugalski
                    'ro' => 'Birou în centrul orașului', // Rumuński
                    'ru' => 'Офис в центре города', // Rosyjski
                    'si' => 'නගර මධ්‍යයේ කාර්යාලය', // Syngaleski
                    'sk' => 'Kancelária v centre mesta', // Słowacki
                    'sl' => 'Pisarna v središču mesta', // Słoweński
                    'sq' => 'Zyrë në qendër të qytetit', // Albański
                    'sr' => 'Канцеларија у центру града', // Serbski
                    'sv' => 'Kontor i stadens centrum', // Szwedzki
                    'tg' => 'Идора дар маркази шаҳр', // Tadżycki
                    'th' => 'สำนักงานในใจกลางเมือง', // Tajski
                    'tk' => 'Şäher merkezindäki ofis', // Turkmeński
                    'tr' => 'Şehir merkezinde ofis', // Turecki
                    'uk' => 'Офіс у центрі міста', // Ukraiński
                    'uz' => 'Shahar markazidagi ofis', // Uzbecki
                    'vi' => 'Văn phòng ở trung tâm thành phố', // Wietnamski
                    'zh' => '市中心的办公室' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 13,
                'name' => json_encode([
                    'am' => 'ለሰራተኞች የመኪና ማቆሚያ', // Amharski
                    'ar' => 'موقف للموظفين', // Arabski
                    'az' => 'İşçilər üçün dayanacaq', // Azerski
                    'be' => 'Паркоўка для супрацоўнікаў', // Białoruski
                    'bg' => 'Паркинг за служители', // Bułgarski
                    'bn' => 'কর্মীদের জন্য পার্কিং', // Bengalski
                    'bs' => 'Parking za zaposlenike', // Bośniacki
                    'ca' => 'Aparcament per als empleats', // Kataloński
                    'cs' => 'Parkoviště pro zaměstnance', // Czeski
                    'da' => 'Parkering til medarbejdere', // Duński
                    'de' => 'Parkplätze für Mitarbeiter', // Niemiecki
                    'dv' => 'މީހައިގެ ޕާކިންގް', // Divehi
                    'dz' => 'ལས་བཟོད་འཐོག་མོལ།', // Dzongkha
                    'el' => 'Χώρος στάθμευσης για εργαζομένους', // Grecki
                    'en' => 'Employee parking', // Angielski
                    'es' => 'Estacionamiento para empleados', // Hiszpański
                    'et' => 'Töötajate parkla', // Estoński
                    'fa' => 'پارکینگ برای کارمندان', // Perski
                    'fi' => 'Pysäköinti työntekijöille', // Fiński
                    'fr' => 'Parking pour les employés', // Francuski
                    'he' => 'חניה לעובדים', // Hebrajski
                    'hi' => 'कर्मचारियों के लिए पार्किंग', // Hindi
                    'hr' => 'Parkiralište za zaposlenike', // Chorwacki
                    'hu' => 'Parkoló az alkalmazottak számára', // Węgierski
                    'hy' => 'Աշխատակիցների համար կայանատեղի', // Ormiański
                    'id' => 'Parkir untuk karyawan', // Indonezyjski
                    'is' => 'Bílastæði fyrir starfsmenn', // Islandzki
                    'it' => 'Parcheggio per dipendenti', // Włoski
                    'ja' => '従業員用駐車場', // Japoński
                    'ka' => 'პარკინგი თანამშრომლებისთვის', // Gruziński
                    'km' => 'ចំណតសម្រាប់និយោជិត', // Khmerski
                    'ko' => '직원 전용 주차장', // Koreański
                    'lb' => 'Parking fir Mataarbechter', // Luksemburski
                    'lo' => 'ທີ່ຈອດລົດສໍາລັບພະນັກງານ', // Laotański
                    'lt' => 'Parkavimo vieta darbuotojams', // Litewski
                    'lv' => 'Stāvvieta darbiniekiem', // Łotewski
                    'me' => 'Parking za zaposlene', // Czarnogórski
                    'mk' => 'Паркинг за вработени', // Macedoński
                    'mn' => 'Ажилчдын зогсоол', // Mongołski
                    'ms' => 'Tempat letak kereta untuk pekerja', // Malajski
                    'my' => 'ဝန်ထမ်းများအတွက်ကားရပ်နားခန်း', // Birmański
                    'ne' => 'कर्मचारीहरूको लागि पार्किङ', // Nepalski
                    'nl' => 'Parkeerplaats voor medewerkers', // Holenderski
                    'no' => 'Parkeringsplass for ansatte', // Norweski
                    'pl' => 'Parking dla pracowników', // Polski
                    'ps' => 'د کارکوونکو لپاره پارکینګ', // Paszto
                    'pt' => 'Estacionamento para funcionários', // Portugalski
                    'ro' => 'Parcare pentru angajați', // Rumuński
                    'ru' => 'Парковка для сотрудников', // Rosyjski
                    'si' => 'සේවකයින් සඳහා වාහන නැවැත්වීම', // Syngaleski
                    'sk' => 'Parkovanie pre zamestnancov', // Słowacki
                    'sl' => 'Parkirišče za zaposlene', // Słoweński
                    'sq' => 'Parkim për punonjësit', // Albański
                    'sr' => 'Паркинг за запослене', // Serbski
                    'sv' => 'Parkering för anställda', // Szwedzki
                    'tg' => 'Истгоҳи нақлиёт барои кормандон', // Tadżycki
                    'th' => 'ที่จอดรถสำหรับพนักงาน', // Tajski
                    'tk' => 'Işgärler üçin awtoulag duralgasy', // Turkmeński
                    'tr' => 'Çalışanlar için otopark', // Turecki
                    'uk' => 'Парковка для працівників', // Ukraiński
                    'uz' => 'Xodimlar uchun avtoturargoh', // Uzbecki
                    'vi' => 'Bãi đỗ xe cho nhân viên', // Wietnamski
                    'zh' => '员工停车场' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 14,
                'name' => json_encode([
                    'am' => 'የሥራ መኪና', // Amharski
                    'ar' => 'سيارة وظيفية', // Arabski
                    'az' => 'Xidmət avtomobili', // Azerski
                    'be' => 'Службовы аўтамабіль', // Białoruski
                    'bg' => 'Служебен автомобил', // Bułgarski
                    'bn' => 'কর্মস্থল গাড়ি', // Bengalski
                    'bs' => 'Službeni automobil', // Bośniacki
                    'ca' => 'Cotxe d\'empresa', // Kataloński
                    'cs' => 'Služební automobil', // Czeski
                    'da' => 'Firmabil', // Duński
                    'de' => 'Dienstwagen', // Niemiecki
                    'dv' => 'ސެރވިސް ކާރު', // Divehi
                    'dz' => 'ཚོགས་འདུར་ཐབས་བརྩོན།', // Dzongkha
                    'el' => 'Εταιρικό αυτοκίνητο', // Grecki
                    'en' => 'Company car', // Angielski
                    'es' => 'Coche de empresa', // Hiszpański
                    'et' => 'Tööauto', // Estoński
                    'fa' => 'ماشین سازمانی', // Perski
                    'fi' => 'Työsuhdeauto', // Fiński
                    'fr' => 'Véhicule de fonction', // Francuski
                    'he' => 'רכב חברה', // Hebrajski
                    'hi' => 'कंपनी की गाड़ी', // Hindi
                    'hr' => 'Službeni automobil', // Chorwacki
                    'hu' => 'Céges autó', // Węgierski
                    'hy' => 'Ծառայողական մեքենա', // Ormiański
                    'id' => 'Mobil dinas', // Indonezyjski
                    'is' => 'Þjónustubíll', // Islandzki
                    'it' => 'Auto aziendale', // Włoski
                    'ja' => '社用車', // Japoński
                    'ka' => 'სამსახურებრივი მანქანა', // Gruziński
                    'km' => 'ឡានសេវាកម្ម', // Khmerski
                    'ko' => '업무용 차량', // Koreański
                    'lb' => 'Firmeauto', // Luksemburski
                    'lo' => 'ລົດບໍລິສັດ', // Laotański
                    'lt' => 'Įmonės automobilis', // Litewski
                    'lv' => 'Dienesta automašīna', // Łotewski
                    'me' => 'Službeni automobil', // Czarnogórski
                    'mk' => 'Службен автомобил', // Macedoński
                    'mn' => 'Албаны машин', // Mongołski
                    'ms' => 'Kereta perkhidmatan', // Malajski
                    'my' => 'အလုပ်သုံးကား', // Birmański
                    'ne' => 'कम्पनीको गाडी', // Nepalski
                    'nl' => 'Bedrijfsauto', // Holenderski
                    'no' => 'Firmabil', // Norweski
                    'pl' => 'Samochód służbowy', // Polski
                    'ps' => 'د خدمت موټر', // Paszto
                    'pt' => 'Carro da empresa', // Portugalski
                    'ro' => 'Mașină de serviciu', // Rumuński
                    'ru' => 'Служебный автомобиль', // Rosyjski
                    'si' => 'සේවා රථය', // Syngaleski
                    'sk' => 'Služobné auto', // Słowacki
                    'sl' => 'Službeni avto', // Słoweński
                    'sq' => 'Makina e punës', // Albański
                    'sr' => 'Службени ауто', // Serbski
                    'sv' => 'Tjänstebil', // Szwedzki
                    'tg' => 'Мошини хизматӣ', // Tadżycki
                    'th' => 'รถยนต์ของบริษัท', // Tajski
                    'tk' => 'Hyzmat awtoulagy', // Turkmeński
                    'tr' => 'Şirket arabası', // Turecki
                    'uk' => 'Службовий автомобіль', // Ukraiński
                    'uz' => 'Xizmat mashinasi', // Uzbecki
                    'vi' => 'Xe công ty', // Wietnamski
                    'zh' => '公司汽车' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 15,
                'name' => json_encode([
                    'am' => 'ተጨማሪ መድን', // Amharski
                    'ar' => 'تأمين إضافي', // Arabski
                    'az' => 'Əlavə sığorta', // Azerski
                    'be' => 'Дадатковае страхаванне', // Białoruski
                    'bg' => 'Допълнителна застраховка', // Bułgarski
                    'bn' => 'অতিরিক্ত বীমা', // Bengalski
                    'bs' => 'Dodatno osiguranje', // Bośniacki
                    'ca' => 'Assegurança addicional', // Kataloński
                    'cs' => 'Doplňkové pojištění', // Czeski
                    'da' => 'Ekstra forsikring', // Duński
                    'de' => 'Zusatzversicherung', // Niemiecki
                    'dv' => 'އެޑިޝަނަލް އިންސާރަންސް', // Divehi
                    'dz' => 'དོ་དམ་སྐྱོང་ཚད་བསྒྲིགས།', // Dzongkha
                    'el' => 'Πρόσθετη ασφάλιση', // Grecki
                    'en' => 'Additional insurance', // Angielski
                    'es' => 'Seguro adicional', // Hiszpański
                    'et' => 'Lisakindlustus', // Estoński
                    'fa' => 'بیمه اضافی', // Perski
                    'fi' => 'Lisävakuutus', // Fiński
                    'fr' => 'Assurance supplémentaire', // Francuski
                    'he' => 'ביטוח נוסף', // Hebrajski
                    'hi' => 'अतिरिक्त बीमा', // Hindi
                    'hr' => 'Dodatno osiguranje', // Chorwacki
                    'hu' => 'Kiegészítő biztosítás', // Węgierski
                    'hy' => 'Լրացուցիչ ապահովագրություն', // Ormiański
                    'id' => 'Asuransi tambahan', // Indonezyjski
                    'is' => 'Viðbótartrygging', // Islandzki
                    'it' => 'Assicurazione aggiuntiva', // Włoski
                    'ja' => '追加保険', // Japoński
                    'ka' => 'დამატებითი დაზღვევა', // Gruziński
                    'km' => 'ការធានារ៉ាប់រងបន្ថែម', // Khmerski
                    'ko' => '추가 보험', // Koreański
                    'lb' => 'Zousätzlech Versécherung', // Luksemburski
                    'lo' => 'ປະກັນໄພເພີ່ມເຕີມ', // Laotański
                    'lt' => 'Papildomas draudimas', // Litewski
                    'lv' => 'Papildu apdrošināšana', // Łotewski
                    'me' => 'Dodatno osiguranje', // Czarnogórski
                    'mk' => 'Дополнително осигурување', // Macedoński
                    'mn' => 'Нэмэлт даатгал', // Mongołski
                    'ms' => 'Insurans tambahan', // Malajski
                    'my' => 'ထပ်ဆင့်အာမခံ', // Birmański
                    'ne' => 'थप बीमा', // Nepalski
                    'nl' => 'Aanvullende verzekering', // Holenderski
                    'no' => 'Ekstra forsikring', // Norweski
                    'pl' => 'Dodatkowe ubezpieczenie', // Polski
                    'ps' => 'اضافي بیمه', // Paszto
                    'pt' => 'Seguro adicional', // Portugalski
                    'ro' => 'Asigurare suplimentară', // Rumuński
                    'ru' => 'Дополнительное страхование', // Rosyjski
                    'si' => 'අතිරේක රක්ෂණය', // Syngaleski
                    'sk' => 'Doplnkové poistenie', // Słowacki
                    'sl' => 'Dodatno zavarovanje', // Słoweński
                    'sq' => 'Sigurim shtesë', // Albański
                    'sr' => 'Додатно осигурање', // Serbski
                    'sv' => 'Ytterligare försäkring', // Szwedzki
                    'tg' => 'Суғуртаи иловагӣ', // Tadżycki
                    'th' => 'ประกันเพิ่มเติม', // Tajski
                    'tk' => 'Goşmaça ätiýaçlandyryş', // Turkmeński
                    'tr' => 'Ek sigorta', // Turecki
                    'uk' => 'Додаткове страхування', // Ukraiński
                    'uz' => 'Qo‘shimcha sug‘urta', // Uzbecki
                    'vi' => 'Bảo hiểm bổ sung', // Wietnamski
                    'zh' => '额外保险' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 16,
                'name' => json_encode([
                    'am' => 'ቅናሽ በግዢ', // Amharski
                    'ar' => 'خصم على المشتريات', // Arabski
                    'az' => 'Alış-verişdə endirim', // Azerski
                    'be' => 'Зніжка на пакупкі', // Białoruski
                    'bg' => 'Отстъпка за покупки', // Bułgarski
                    'bn' => 'কেনাকাটায় ছাড়', // Bengalski
                    'bs' => 'Popust na kupovinu', // Bośniacki
                    'ca' => 'Descompte en compres', // Kataloński
                    'cs' => 'Sleva na nákupy', // Czeski
                    'da' => 'Rabat på indkøb', // Duński
                    'de' => 'Rabatt auf Einkäufe', // Niemiecki
                    'dv' => 'ހައްދަދާން ދަނޑަ ދާއިރު', // Divehi
                    'dz' => 'སྤྲོད་བཤོལ་ལས་ཉོས་པ།', // Dzongkha
                    'el' => 'Έκπτωση στις αγορές', // Grecki
                    'en' => 'Discount on purchases', // Angielski
                    'es' => 'Descuento en compras', // Hiszpański
                    'et' => 'Allahindlus ostudele', // Estoński
                    'fa' => 'تخفیف در خرید', // Perski
                    'fi' => 'Alennus ostoksista', // Fiński
                    'fr' => 'Réduction sur les achats', // Francuski
                    'he' => 'הנחה על קניות', // Hebrajski
                    'hi' => 'खरीदारी पर छूट', // Hindi
                    'hr' => 'Popust na kupnju', // Chorwacki
                    'hu' => 'Kedvezmény vásárláskor', // Węgierski
                    'hy' => 'Զեղչ գնումների համար', // Ormiański
                    'id' => 'Diskon untuk pembelian', // Indonezyjski
                    'is' => 'Afsláttur af innkaupum', // Islandzki
                    'it' => 'Sconto sugli acquisti', // Włoski
                    'ja' => '購入時の割引', // Japoński
                    'ka' => 'ფასდაკლება შესყიდვებზე', // Gruziński
                    'km' => 'បញ្ចុះតម្លៃលើការទិញ', // Khmerski
                    'ko' => '구매 할인', // Koreański
                    'lb' => 'Remise op Akaaf', // Luksemburski
                    'lo' => 'ສ່ວນຫຼຸດໃນການຊື້ຂາຍ', // Laotański
                    'lt' => 'Nuolaida pirkiniams', // Litewski
                    'lv' => 'Atlaide pirkumiem', // Łotewski
                    'me' => 'Popust na kupovinu', // Czarnogórski
                    'mk' => 'Попуст на купувања', // Macedoński
                    'mn' => 'Худалдан авалтад хөнгөлөлт', // Mongołski
                    'ms' => 'Diskaun untuk pembelian', // Malajski
                    'my' => 'ဈေးဝယ်မှုအတွက်လျှော့ဈေး', // Birmański
                    'ne' => 'किनमेलमा छुट', // Nepalski
                    'nl' => 'Korting op aankopen', // Holenderski
                    'no' => 'Rabatt på kjøp', // Norweski
                    'pl' => 'Zniżka na zakupy', // Polski
                    'ps' => 'په پیرود کې تخفیف', // Paszto
                    'pt' => 'Desconto em compras', // Portugalski
                    'ro' => 'Reducere la cumpărături', // Rumuński
                    'ru' => 'Скидка на покупки', // Rosyjski
                    'si' => 'ගැණුම් මත වට්ටම්', // Syngaleski
                    'sk' => 'Zľava na nákupy', // Słowacki
                    'sl' => 'Popust na nakupe', // Słoweński
                    'sq' => 'Zbritje për blerjet', // Albański
                    'sr' => 'Попуст на куповину', // Serbski
                    'sv' => 'Rabatt på inköp', // Szwedzki
                    'tg' => 'Тахфиф барои харид', // Tadżycki
                    'th' => 'ส่วนลดในการซื้อ', // Tajski
                    'tk' => 'Satyn alyş üçin arzanladyş', // Turkmeński
                    'tr' => 'Alışveriş indirimi', // Turecki
                    'uk' => 'Знижка на покупки', // Ukraiński
                    'uz' => 'Xaridlarga chegirma', // Uzbecki
                    'vi' => 'Giảm giá khi mua sắm', // Wietnamski
                    'zh' => '购物折扣' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 17,
                'name' => json_encode([
                    'am' => 'የማካበያ ክስተቶች', // Amharski
                    'ar' => 'فعاليات الدمج', // Arabski
                    'az' => 'İnteqrasiya tədbirləri', // Azerski
                    'be' => 'Інтэграцыйныя мерапрыемствы', // Białoruski
                    'bg' => 'Интеграционни събития', // Bułgarski
                    'bn' => 'ইন্টিগ্রেশন ইভেন্ট', // Bengalski
                    'bs' => 'Integracijski događaji', // Bośniacki
                    'ca' => 'Esdeveniments d\'integració', // Kataloński
                    'cs' => 'Integrační akce', // Czeski
                    'da' => 'Integrationsbegivenheder', // Duński
                    'de' => 'Integrationsveranstaltungen', // Niemiecki
                    'dv' => 'އިންޓެގްރޭޝަން އެވެންޓުތައް', // Divehi
                    'dz' => 'ཁུར་སྤྱོད་གྲོགས་སྤྲོད།', // Dzongkha
                    'el' => 'Εκδηλώσεις ενσωμάτωσης', // Grecki
                    'en' => 'Integration events', // Angielski
                    'es' => 'Eventos de integración', // Hiszpański
                    'et' => 'Integreerimisüritused', // Estoński
                    'fa' => 'رویدادهای یکپارچه‌سازی', // Perski
                    'fi' => 'Yhteisöllisyystapahtumat', // Fiński
                    'fr' => 'Événements d\'intégration', // Francuski
                    'he' => 'אירועי גיבוש', // Hebrajski
                    'hi' => 'एकीकरण कार्यक्रम', // Hindi
                    'hr' => 'Integracijski događaji', // Chorwacki
                    'hu' => 'Integrációs események', // Węgierski
                    'hy' => 'Ինտեգրման միջոցառումներ', // Ormiański
                    'id' => 'Acara integrasi', // Indonezyjski
                    'is' => 'Samþættingarviðburðir', // Islandzki
                    'it' => 'Eventi di integrazione', // Włoski
                    'ja' => '統合イベント', // Japoński
                    'ka' => 'ინტეგრაციული ღონისძიებები', // Gruziński
                    'km' => 'ព្រឹត្តិការណ៍បញ្ចូលសហគមន៍', // Khmerski
                    'ko' => '통합 행사', // Koreański
                    'lb' => 'Integratiounsevenementer', // Luksemburski
                    'lo' => 'ກິດຈະກຳບູລະກົມ', // Laotański
                    'lt' => 'Integracijos renginiai', // Litewski
                    'lv' => 'Integrācijas pasākumi', // Łotewski
                    'me' => 'Integracioni događaji', // Czarnogórski
                    'mk' => 'Интеграциски настани', // Macedoński
                    'mn' => 'Интеграцийн үйл ажиллагаа', // Mongołski
                    'ms' => 'Acara integrasi', // Malajski
                    'my' => 'သင်းအဖွဲ့ဖွဲ့စည်းမှုပွဲများ', // Birmański
                    'ne' => 'एकीकरण कार्यक्रमहरू', // Nepalski
                    'nl' => 'Integratie-evenementen', // Holenderski
                    'no' => 'Integrasjonsarrangementer', // Norweski
                    'pl' => 'Wydarzenia integracyjne', // Polski
                    'ps' => 'د یوځای کیدو پیښې', // Paszto
                    'pt' => 'Eventos de integração', // Portugalski
                    'ro' => 'Evenimente de integrare', // Rumuński
                    'ru' => 'Интеграционные мероприятия', // Rosyjski
                    'si' => 'ඒකාබද්ධ විශේෂාවන්', // Syngaleski
                    'sk' => 'Integračné podujatia', // Słowacki
                    'sl' => 'Integracijski dogodki', // Słoweński
                    'sq' => 'Ngjarje integruese', // Albański
                    'sr' => 'Интеграциони догађаји', // Serbski
                    'sv' => 'Integrationshändelser', // Szwedzki
                    'tg' => 'Рӯйдодҳои ҳамгироӣ', // Tadżycki
                    'th' => 'กิจกรรมการบูรณาการ', // Tajski
                    'tk' => 'Integrasiýa wakalary', // Turkmeński
                    'tr' => 'Entegrasyon etkinlikleri', // Turecki
                    'uk' => 'Інтеграційні заходи', // Ukraiński
                    'uz' => 'Integratsion tadbirlar', // Uzbecki
                    'vi' => 'Sự kiện hội nhập', // Wietnamski
                    'zh' => '融合活动' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 18,
                'name' => json_encode([
                    'am' => 'ቡና/ሻይ', // Amharski
                    'ar' => 'قهوة/شاي', // Arabski
                    'az' => 'Qəhvə/çay', // Azerski
                    'be' => 'Кава/чай', // Białoruski
                    'bg' => 'Кафе/чай', // Bułgarski
                    'bn' => 'কফি/চা', // Bengalski
                    'bs' => 'Kafa/čaj', // Bośniacki
                    'ca' => 'Cafè/te', // Kataloński
                    'cs' => 'Káva/čaj', // Czeski
                    'da' => 'Kaffe/te', // Duński
                    'de' => 'Kaffee/Tee', // Niemiecki
                    'dv' => 'ކޮފީ/ޓީ', // Divehi
                    'dz' => 'ཀ་ཕི/ཇ་མ', // Dzongkha
                    'el' => 'Καφές/τσάι', // Grecki
                    'en' => 'Coffee/tea', // Angielski
                    'es' => 'Café/té', // Hiszpański
                    'et' => 'Kohv/tee', // Estoński
                    'fa' => 'قهوه/چای', // Perski
                    'fi' => 'Kahvi/tee', // Fiński
                    'fr' => 'Café/thé', // Francuski
                    'he' => 'קפה/תה', // Hebrajski
                    'hi' => 'कॉफी/चाय', // Hindi
                    'hr' => 'Kava/čaj', // Chorwacki
                    'hu' => 'Kávé/tea', // Węgierski
                    'hy' => 'Սուրճ/թեյ', // Ormiański
                    'id' => 'Kopi/teh', // Indonezyjski
                    'is' => 'Kaffi/te', // Islandzki
                    'it' => 'Caffè/tè', // Włoski
                    'ja' => 'コーヒー/お茶', // Japoński
                    'ka' => 'ყავა/ჩაი', // Gruziński
                    'km' => 'កាហ្វេ/តែ', // Khmerski
                    'ko' => '커피/차', // Koreański
                    'lb' => 'Kaffi/Téi', // Luksemburski
                    'lo' => 'ກາເຟ/ຊາ', // Laotański
                    'lt' => 'Kava/arbata', // Litewski
                    'lv' => 'Kafija/tēja', // Łotewski
                    'me' => 'Kafa/čaj', // Czarnogórski
                    'mk' => 'Кафе/чај', // Macedoński
                    'mn' => 'Кофе/цай', // Mongołski
                    'ms' => 'Kopi/teh', // Malajski
                    'my' => 'ကော်ဖီ/လက်ဖက်ရည်', // Birmański
                    'ne' => 'कफी/चिया', // Nepalski
                    'nl' => 'Koffie/thee', // Holenderski
                    'no' => 'Kaffe/te', // Norweski
                    'pl' => 'Kawa/herbata', // Polski
                    'ps' => 'کافي/چاى', // Paszto
                    'pt' => 'Café/chá', // Portugalski
                    'ro' => 'Cafea/ceai', // Rumuński
                    'ru' => 'Кофе/чай', // Rosyjski
                    'si' => 'කෝපි/තේ', // Syngaleski
                    'sk' => 'Káva/čaj', // Słowacki
                    'sl' => 'Kava/čaj', // Słoweński
                    'sq' => 'Kafe/çaj', // Albański
                    'sr' => 'Кафа/чај', // Serbski
                    'sv' => 'Kaffe/te', // Szwedzki
                    'tg' => 'Қаҳва/чой', // Tadżycki
                    'th' => 'กาแฟ/ชา', // Tajski
                    'tk' => 'Kofe/çaý', // Turkmeński
                    'tr' => 'Kahve/çay', // Turecki
                    'uk' => 'Кава/чай', // Ukraiński
                    'uz' => 'Qahva/choy', // Uzbecki
                    'vi' => 'Cà phê/trà', // Wietnamski
                    'zh' => '咖啡/茶' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 19,
                'name' => json_encode([
                    'am' => 'ፍራፍሬ', // Amharski
                    'ar' => 'فواكه', // Arabski
                    'az' => 'Meyvələr', // Azerski
                    'be' => 'Плады', // Białoruski
                    'bg' => 'Плодове', // Bułgarski
                    'bn' => 'ফল', // Bengalski
                    'bs' => 'Voće', // Bośniacki
                    'ca' => 'Fruites', // Kataloński
                    'cs' => 'Ovoce', // Czeski
                    'da' => 'Frugt', // Duński
                    'de' => 'Früchte', // Niemiecki
                    'dv' => 'ފްރޫޓްތައް', // Divehi
                    'dz' => 'ཤིང་ཏོག', // Dzongkha
                    'el' => 'Φρούτα', // Grecki
                    'en' => 'Fruits', // Angielski
                    'es' => 'Frutas', // Hiszpański
                    'et' => 'Puuviljad', // Estoński
                    'fa' => 'میوه‌ها', // Perski
                    'fi' => 'Hedelmät', // Fiński
                    'fr' => 'Fruits', // Francuski
                    'he' => 'פירות', // Hebrajski
                    'hi' => 'फल', // Hindi
                    'hr' => 'Voće', // Chorwacki
                    'hu' => 'Gyümölcsök', // Węgierski
                    'hy' => 'Մրգեր', // Ormiański
                    'id' => 'Buah-buahan', // Indonezyjski
                    'is' => 'Ávextir', // Islandzki
                    'it' => 'Frutta', // Włoski
                    'ja' => '果物', // Japoński
                    'ka' => 'ხილი', // Gruziński
                    'km' => 'ផ្លែឈើ', // Khmerski
                    'ko' => '과일', // Koreański
                    'lb' => 'Uebst', // Luksemburski
                    'lo' => 'ຜົນໄມ້', // Laotański
                    'lt' => 'Vaisiai', // Litewski
                    'lv' => 'Augļi', // Łotewski
                    'me' => 'Voće', // Czarnogórski
                    'mk' => 'Овошје', // Macedoński
                    'mn' => 'Жимс', // Mongołski
                    'ms' => 'Buah-buahan', // Malajski
                    'my' => 'အသီးအဖွဲ့', // Birmański
                    'ne' => 'फलफूल', // Nepalski
                    'nl' => 'Fruit', // Holenderski
                    'no' => 'Frukt', // Norweski
                    'pl' => 'Owoce', // Polski
                    'ps' => 'ميوې', // Paszto
                    'pt' => 'Frutas', // Portugalski
                    'ro' => 'Fructe', // Rumuński
                    'ru' => 'Фрукты', // Rosyjski
                    'si' => 'පලතුරු', // Syngaleski
                    'sk' => 'Ovocie', // Słowacki
                    'sl' => 'Sadje', // Słoweński
                    'sq' => 'Fruta', // Albański
                    'sr' => 'Воће', // Serbski
                    'sv' => 'Frukt', // Szwedzki
                    'tg' => 'Меваҳо', // Tadżycki
                    'th' => 'ผลไม้', // Tajski
                    'tk' => 'Miwe', // Turkmeński
                    'tr' => 'Meyveler', // Turecki
                    'uk' => 'Фрукти', // Ukraiński
                    'uz' => 'Mevalar', // Uzbecki
                    'vi' => 'Trái cây', // Wietnamski
                    'zh' => '水果' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 20,
                'name' => json_encode([
                    'am' => 'የልብስ ሥርዓት አልባ', // Amharski
                    'ar' => 'لا يوجد قواعد للزي', // Arabski
                    'az' => 'Geyim qaydası yoxdur', // Azerski
                    'be' => 'Адсутнасць дрэс-кода', // Białoruski
                    'bg' => 'Без дрескод', // Bułgarski
                    'bn' => 'ড্রেস কোড নেই', // Bengalski
                    'bs' => 'Bez dress code-a', // Bośniacki
                    'ca' => 'Sense codi de vestimenta', // Kataloński
                    'cs' => 'Žádný dress code', // Czeski
                    'da' => 'Ingen dresscode', // Duński
                    'de' => 'Kein Dresscode', // Niemiecki
                    'dv' => 'ޑްރެސް ކޯޑް ނެތް', // Divehi
                    'dz' => 'གནས་ཚུལ་གྱི་བཙོན་ཁྲིམས་མེད་པ།', // Dzongkha
                    'el' => 'Χωρίς ενδυματολογικό κώδικα', // Grecki
                    'en' => 'No dress code', // Angielski
                    'es' => 'Sin código de vestimenta', // Hiszpański
                    'et' => 'Kleitkoodi pole', // Estoński
                    'fa' => 'بدون قانون لباس', // Perski
                    'fi' => 'Ei pukukoodia', // Fiński
                    'fr' => 'Pas de code vestimentaire', // Francuski
                    'he' => 'אין קוד לבוש', // Hebrajski
                    'hi' => 'कोई ड्रेस कोड नहीं', // Hindi
                    'hr' => 'Bez dress codea', // Chorwacki
                    'hu' => 'Nincs dress code', // Węgierski
                    'hy' => 'Առանց հագուստի կոդի', // Ormiański
                    'id' => 'Tidak ada aturan berpakaian', // Indonezyjski
                    'is' => 'Enginn klæðaburðarkóði', // Islandzki
                    'it' => 'Nessun codice di abbigliamento', // Włoski
                    'ja' => '服装規定なし', // Japoński
                    'ka' => 'ტანსაცმლის კოდი არ არის', // Gruziński
                    'km' => 'គ្មានលក្ខខណ្ឌសំលៀកបំពាក់', // Khmerski
                    'ko' => '복장 규정 없음', // Koreański
                    'lb' => 'Keng Kleedungscode', // Luksemburski
                    'lo' => 'ບໍ່ມີລະບຽບການແຕ່ງກາຍ', // Laotański
                    'lt' => 'Nėra aprangos kodo', // Litewski
                    'lv' => 'Nav ģērbšanās koda', // Łotewski
                    'me' => 'Bez dress codea', // Czarnogórski
                    'mk' => 'Без кодекс за облекување', // Macedoński
                    'mn' => 'Хувцасны дүрэмгүй', // Mongołski
                    'ms' => 'Tiada kod pakaian', // Malajski
                    'my' => 'အဝတ်အစားစည်းကမ်းမရှိပါ', // Birmański
                    'ne' => 'ड्रेस कोड छैन', // Nepalski
                    'nl' => 'Geen dresscode', // Holenderski
                    'no' => 'Ingen kleskode', // Norweski
                    'pl' => 'Brak dress code\'u', // Polski
                    'ps' => 'هیڅ لباس کوډ نشته', // Paszto
                    'pt' => 'Sem código de vestimenta', // Portugalski
                    'ro' => 'Fără cod vestimentar', // Rumuński
                    'ru' => 'Нет дресс-кода', // Rosyjski
                    'si' => 'ඇඳුම් රෙගුලාසි නොමැත', // Syngaleski
                    'sk' => 'Žiadny dress code', // Słowacki
                    'sl' => 'Brez kode oblačenja', // Słoweński
                    'sq' => 'Pa kod veshjeje', // Albański
                    'sr' => 'Без правила облачења', // Serbski
                    'sv' => 'Ingen klädkod', // Szwedzki
                    'tg' => 'Коди либос нест', // Tadżycki
                    'th' => 'ไม่มีการแต่งกาย', // Tajski
                    'tk' => 'Geýim düzgüni ýok', // Turkmeński
                    'tr' => 'Kıyafet kuralı yok', // Turecki
                    'uk' => 'Немає дрес-коду', // Ukraiński
                    'uz' => 'Kiyim kodi yo‘q', // Uzbecki
                    'vi' => 'Không có quy định trang phục', // Wietnamski
                    'zh' => '无着装要求' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 21,
                'name' => json_encode([
                    'am' => 'የሰራተኞች ሽልማቶች', // Amharski
                    'ar' => 'جوائز الموظفين', // Arabski
                    'az' => 'İşçi mükafatları', // Azerski
                    'be' => 'Працоўныя ўзнагароды', // Białoruski
                    'bg' => 'Награди за служители', // Bułgarski
                    'bn' => 'কর্মচারী পুরস্কার', // Bengalski
                    'bs' => 'Nagrade za zaposlene', // Bośniacki
                    'ca' => 'Premis per als empleats', // Kataloński
                    'cs' => 'Zaměstnanecké odměny', // Czeski
                    'da' => 'Medarbejderpriser', // Duński
                    'de' => 'Mitarbeiterpreise', // Niemiecki
                    'dv' => 'އައުމިންގެ ގެއުލުތައް', // Divehi
                    'dz' => 'ལས་གཡོག་ཞབས་བཏང་གི་ཞིབ་བརྟན།', // Dzongkha
                    'el' => 'Βραβεία εργαζομένων', // Grecki
                    'en' => 'Employee awards', // Angielski
                    'es' => 'Premios para empleados', // Hiszpański
                    'et' => 'Töötajate auhinnad', // Estoński
                    'fa' => 'جوایز کارکنان', // Perski
                    'fi' => 'Työntekijäpalkinnot', // Fiński
                    'fr' => 'Récompenses pour les employés', // Francuski
                    'he' => 'פרסי עובדים', // Hebrajski
                    'hi' => 'कर्मचारी पुरस्कार', // Hindi
                    'hr' => 'Nagrade za zaposlenike', // Chorwacki
                    'hu' => 'Dolgozói díjak', // Węgierski
                    'hy' => 'Աշխատակիցների մրցանակներ', // Ormiański
                    'id' => 'Penghargaan karyawan', // Indonezyjski
                    'is' => 'Verðlaun starfsmanna', // Islandzki
                    'it' => 'Premi per i dipendenti', // Włoski
                    'ja' => '従業員賞', // Japoński
                    'ka' => 'თანამშრომლის ჯილდოები', // Gruziński
                    'km' => 'រង្វាន់សម្រាប់បុគ្គលិក', // Khmerski
                    'ko' => '직원 상', // Koreański
                    'lb' => 'Mataarbechterpräisser', // Luksemburski
                    'lo' => 'ລາງວັນພະນັກງານ', // Laotański
                    'lt' => 'Darbuotojų apdovanojimai', // Litewski
                    'lv' => 'Darbinieku balvas', // Łotewski
                    'me' => 'Nagrade za zaposlene', // Czarnogórski
                    'mk' => 'Награди за вработени', // Macedoński
                    'mn' => 'Ажилчдын шагнал', // Mongołski
                    'ms' => 'Anugerah pekerja', // Malajski
                    'my' => 'ဝန်ထမ်းဆုများ', // Birmański
                    'ne' => 'कर्मचारी पुरस्कारहरू', // Nepalski
                    'nl' => 'Werknemersprijzen', // Holenderski
                    'no' => 'Ansattpriser', // Norweski
                    'pl' => 'Nagrody pracownicze', // Polski
                    'ps' => 'د کارمندانو جایزې', // Paszto
                    'pt' => 'Prêmios para funcionários', // Portugalski
                    'ro' => 'Premii pentru angajați', // Rumuński
                    'ru' => 'Награды для сотрудников', // Rosyjski
                    'si' => 'සේවක සම්මාන', // Syngaleski
                    'sk' => 'Zamestnanecké ocenenia', // Słowacki
                    'sl' => 'Nagrade za zaposlene', // Słoweński
                    'sq' => 'Çmimet për punonjësit', // Albański
                    'sr' => 'Награде за запослене', // Serbski
                    'sv' => 'Anställdas utmärkelser', // Szwedzki
                    'tg' => 'Мукофотҳои кормандон', // Tadżycki
                    'th' => 'รางวัลพนักงาน', // Tajski
                    'tk' => 'Işgär baýraklary', // Turkmeński
                    'tr' => 'Çalışan ödülleri', // Turecki
                    'uk' => 'Нагороди для працівників', // Ukraiński
                    'uz' => 'Xodimlar mukofotlari', // Uzbecki
                    'vi' => 'Giải thưởng nhân viên', // Wietnamski
                    'zh' => '员工奖励' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 22,
                'name' => json_encode([
                    'am' => 'ወደ ትራንስፖርት ድጋፍ', // Amharski
                    'ar' => 'تمويل النقل', // Arabski
                    'az' => 'Nəqliyyat üçün maliyyə dəstəyi', // Azerski
                    'be' => 'Субсідыі на транспарт', // Białoruski
                    'bg' => 'Финансово подпомагане за транспорт', // Bułgarski
                    'bn' => 'পরিবহনের জন্য আর্থিক সহায়তা', // Bengalski
                    'bs' => 'Subvencija za prijevoz', // Bośniacki
                    'ca' => 'Subvenció per al transport', // Kataloński
                    'cs' => 'Příspěvek na dopravu', // Czeski
                    'da' => 'Transporttilskud', // Duński
                    'de' => 'Zuschuss für den Transport', // Niemiecki
                    'dv' => 'ޓްރާންސްޕޯރޓުއަށް ދަނޑަ އަދަދަކުރެވިފަ', // Divehi
                    'dz' => 'ཐོག་མར་གཅོད་མཁོ་དང་སྤྲོད།', // Dzongkha
                    'el' => 'Επιχορήγηση για μεταφορά', // Grecki
                    'en' => 'Transportation subsidy', // Angielski
                    'es' => 'Subvención para transporte', // Hiszpański
                    'et' => 'Transporditoetus', // Estoński
                    'fa' => 'یارانه حمل و نقل', // Perski
                    'fi' => 'Kuljetustuki', // Fiński
                    'fr' => 'Subvention pour le transport', // Francuski
                    'he' => 'מימון לתחבורה', // Hebrajski
                    'hi' => 'परिवहन के लिए अनुदान', // Hindi
                    'hr' => 'Subvencija za prijevoz', // Chorwacki
                    'hu' => 'Utazási támogatás', // Węgierski
                    'hy' => 'Տրանսպորտի համար ֆինանսավորում', // Ormiański
                    'id' => 'Subsidi transportasi', // Indonezyjski
                    'is' => 'Samgöngustyrkur', // Islandzki
                    'it' => 'Contributo per il trasporto', // Włoski
                    'ja' => '交通補助金', // Japoński
                    'ka' => 'ტრანსპორტის დაფინანსება', // Gruziński
                    'km' => 'ជំនួយសម្រាប់ការដឹកជញ្ជូន', // Khmerski
                    'ko' => '교통비 지원', // Koreański
                    'lb' => 'Subsidiär fir den Transport', // Luksemburski
                    'lo' => 'ສະໜັບສະໜູນສໍາລັບການຂົນສົ່ງ', // Laotański
                    'lt' => 'Transporto subsidija', // Litewski
                    'lv' => 'Atbalsts transportam', // Łotewski
                    'me' => 'Subvencija za transport', // Czarnogórski
                    'mk' => 'Субвенција за транспорт', // Macedoński
                    'mn' => 'Тээврийн зардалд татаас', // Mongołski
                    'ms' => 'Subsidi untuk pengangkutan', // Malajski
                    'my' => 'သယ်ယူပို့ဆောင်ရေးအထောက်အပံ့', // Birmański
                    'ne' => 'यातायातका लागि अनुदान', // Nepalski
                    'nl' => 'Subsidie voor vervoer', // Holenderski
                    'no' => 'Transporttilskudd', // Norweski
                    'pl' => 'Dofinansowanie do transportu', // Polski
                    'ps' => 'د ترانسپورت لپاره مالي مرسته', // Paszto
                    'pt' => 'Subsídio para transporte', // Portugalski
                    'ro' => 'Subvenție pentru transport', // Rumuński
                    'ru' => 'Субсидия на транспорт', // Rosyjski
                    'si' => 'ප්රවාහනය සඳහා ආධාර', // Syngaleski
                    'sk' => 'Príspevok na dopravu', // Słowacki
                    'sl' => 'Subvencija za prevoz', // Słoweński
                    'sq' => 'Subvencion për transportin', // Albański
                    'sr' => 'Субвенција за транспорт', // Serbski
                    'sv' => 'Transportbidrag', // Szwedzki
                    'tg' => 'Субсидия барои нақлиёт', // Tadżycki
                    'th' => 'เงินอุดหนุนการขนส่ง', // Tajski
                    'tk' => 'Transport üçin subsidiýa', // Turkmeński
                    'tr' => 'Ulaşım desteği', // Turecki
                    'uk' => 'Субсидія на транспорт', // Ukraiński
                    'uz' => 'Transport uchun subsidiya', // Uzbecki
                    'vi' => 'Trợ cấp giao thông', // Wietnamski
                    'zh' => '交通补贴' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ]
        ];
        DB::table('offers')->insert($offers);
    }
}
