<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PaySystemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('pay_systems')->truncate();

        $pay_systems = [
            [
                'id' => 1,
                'name' => json_encode([
                    'am' => 'ቋሚ ደመወዝ', // Amharski
                    'ar' => 'راتب ثابت', // Arabski
                    'az' => 'Daimi maaş', // Azerski
                    'be' => 'Пастаянная зарплата', // Białoruski
                    'bg' => 'Фиксирана заплата', // Bułgarski
                    'bn' => 'স্থায়ী বেতন', // Bengalski
                    'bs' => 'Stalna plata', // Bośniacki
                    'ca' => 'Sou fix', // Kataloński
                    'cs' => 'Stálý plat', // Czeski
                    'da' => 'Fast løn', // Duński
                    'de' => 'Festgehalt', // Niemiecki
                    'dv' => 'މިއަދަދާ މައިލްލެމަށް', // Divehi
                    'dz' => 'རྟག་ཏུ་བཏང་མི་དོ་དམག', // Dzongkha
                    'el' => 'Σταθερός μισθός', // Grecki
                    'en' => 'Fixed salary', // Angielski
                    'es' => 'Salario fijo', // Hiszpański
                    'et' => 'Fikseeritud palk', // Estoński
                    'fa' => 'حقوق ثابت', // Perski
                    'fi' => 'Kiinteä palkka', // Fiński
                    'fr' => 'Salaire fixe', // Francuski
                    'he' => 'משכורת קבועה', // Hebrajski
                    'hi' => 'स्थिर वेतन', // Hindi
                    'hr' => 'Fiksna plaća', // Chorwacki
                    'hu' => 'Fix fizetés', // Węgierski
                    'hy' => 'Մշտական աշխատավարձ', // Ormiański
                    'id' => 'Gaji tetap', // Indonezyjski
                    'is' => 'Föst laun', // Islandzki
                    'it' => 'Stipendio fisso', // Włoski
                    'ja' => '固定給与', // Japoński
                    'ka' => 'ფიქსირებული ხელფასი', // Gruziński
                    'km' => 'ប្រាក់ខែថេរ', // Khmerski
                    'ko' => '고정 급여', // Koreański
                    'lb' => 'Feste Pai', // Luksemburski
                    'lo' => 'ເງິນເດືອນຄົງທີ່', // Laotański
                    'lt' => 'Fiksuotas atlyginimas', // Litewski
                    'lv' => 'Fiksēta alga', // Łotewski
                    'me' => 'Fiksna plata', // Czarnogórski
                    'mk' => 'Фиксна плата', // Macedoński
                    'mn' => 'Тогтмол цалин', // Mongołski
                    'ms' => 'Gaji tetap', // Malajski
                    'my' => 'အမြဲတမ်းလစာ', // Birmański
                    'ne' => 'स्थिर तलब', // Nepalski
                    'nl' => 'Vast salaris', // Holenderski
                    'no' => 'Fast lønn', // Norweski
                    'pl' => 'Stałe wynagrodzenie', // Polski
                    'ps' => 'ثابت معاش', // Paszto
                    'pt' => 'Salário fixo', // Portugalski
                    'ro' => 'Salariu fix', // Rumuński
                    'ru' => 'Фиксированная зарплата', // Rosyjski
                    'si' => 'ස්ථීර වැටුප්', // Syngaleski
                    'sk' => 'Fixný plat', // Słowacki
                    'sl' => 'Fiksna plača', // Słoweński
                    'sq' => 'Paga e qëndrueshme', // Albański
                    'sr' => 'Фиксна плата', // Serbski
                    'sv' => 'Fast lön', // Szwedzki
                    'tg' => 'Музди доимӣ', // Tadżycki
                    'th' => 'เงินเดือนประจำ', // Tajski
                    'tk' => 'Durnukly aýlyk', // Turkmeński
                    'tr' => 'Sabit maaş', // Turecki
                    'uk' => 'Фіксована зарплата', // Ukraiński
                    'uz' => 'Doimiy maosh', // Uzbecki
                    'vi' => 'Lương cố định', // Wietnamski
                    'zh' => '固定工资' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],[
                'id' => 2,
                'name' => json_encode([
                    'am' => 'አግባብ ቅርብ ግምት', // Amharski
                    'ar' => 'مكافأة مناسبة', // Arabski
                    'az' => 'Tədbir mükafatı', // Azerski
                    'be' => 'Прымеркаваная прэмія', // Białoruski
                    'bg' => 'Случаен бонус', // Bułgarski
                    'bn' => 'উপলক্ষ্য বোনাস', // Bengalski
                    'bs' => 'Prigodna premija', // Bośniacki
                    'ca' => 'Prima d\'ocasió', // Kataloński
                    'cs' => 'Příležitostní prémie', // Czeski
                    'da' => 'Lejlighedsbonus', // Duński
                    'de' => 'Anlassbezogener Bonus', // Niemiecki
                    'dv' => 'އައިލަފާންނަ ބޮނަސް', // Divehi
                    'dz' => 'ཚོགས་ལོག་སྤུན་སྤྲོད།', // Dzongkha
                    'el' => 'Ευκαιριακό επίδομα', // Grecki
                    'en' => 'Occasional bonus', // Angielski
                    'es' => 'Bono ocasional', // Hiszpański
                    'et' => 'Erakorraline boonus', // Estoński
                    'fa' => 'پاداش مناسبتی', // Perski
                    'fi' => 'Tilauskohtainen bonus', // Fiński
                    'fr' => 'Prime occasionnelle', // Francuski
                    'he' => 'בונוס אירוע', // Hebrajski
                    'hi' => 'अवसरजन्य बोनस', // Hindi
                    'hr' => 'Prigodna premija', // Chorwacki
                    'hu' => 'Alkalmi bónusz', // Węgierski
                    'hy' => 'Ապահովման հավելավճար', // Ormiański
                    'id' => 'Bonus khusus', // Indonezyjski
                    'is' => 'Tímabundinn bónus', // Islandzki
                    'it' => 'Premio occasionale', // Włoski
                    'ja' => '特別ボーナス', // Japoński
                    'ka' => 'შემთხვევითი პრემია', // Gruziński
                    'km' => 'ប្រាក់លើកទឹកចិត្តពិសេស', // Khmerski
                    'ko' => '특별 보너스', // Koreański
                    'lb' => 'Geleeënheetsbonus', // Luksemburski
                    'lo' => 'ໂບນັດພິເສດ', // Laotański
                    'lt' => 'Proginė premija', // Litewski
                    'lv' => 'Gadījuma prēmija', // Łotewski
                    'me' => 'Prigodna premija', // Czarnogórski
                    'mk' => 'Пригоден бонус', // Macedoński
                    'mn' => 'Онцгой урамшуулал', // Mongołski
                    'ms' => 'Bonus khas', // Malajski
                    'my' => 'အခါသမယပိုဆု', // Birmański
                    'ne' => 'विशेष बोनस', // Nepalski
                    'nl' => 'Gelegenheidsbonus', // Holenderski
                    'no' => 'Leilighetsbonus', // Norweski
                    'pl' => 'Premia okolicznościowa', // Polski
                    'ps' => 'د مناسبت جایزه', // Paszto
                    'pt' => 'Bónus ocasional', // Portugalski
                    'ro' => 'Primă ocazională', // Rumuński
                    'ru' => 'Случайная премия', // Rosyjski
                    'si' => 'විශේෂ පිරිවිතර බෝනස්', // Syngaleski
                    'sk' => 'Príležitostná prémia', // Słowacki
                    'sl' => 'Priložnostna premija', // Słoweński
                    'sq' => 'Premi rastësore', // Albański
                    'sr' => 'Пригодна премија', // Serbski
                    'sv' => 'Tillfällig bonus', // Szwedzki
                    'tg' => 'Бонуси мавсимӣ', // Tadżycki
                    'th' => 'โบนัสโอกาสพิเศษ', // Tajski
                    'tk' => 'Maksatlaýyn bonus', // Turkmeński
                    'tr' => 'Özel bonus', // Turecki
                    'uk' => 'Додаткова премія', // Ukraiński
                    'uz' => 'Maxsus bonus', // Uzbecki
                    'vi' => 'Thưởng đặc biệt', // Wietnamski
                    'zh' => '特别奖金' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],[
                'id' => 3,
                'name' => json_encode([
                    'am' => 'ቋሚ ቅርብ ግምት', // Amharski
                    'ar' => 'مكافأة ثابتة', // Arabski
                    'az' => 'Daimi mükafat', // Azerski
                    'be' => 'Пастаянная прэмія', // Białoruski
                    'bg' => 'Фиксиран бонус', // Bułgarski
                    'bn' => 'স্থায়ী বোনাস', // Bengalski
                    'bs' => 'Stalni bonus', // Bośniacki
                    'ca' => 'Prima fixa', // Kataloński
                    'cs' => 'Stálá prémie', // Czeski
                    'da' => 'Fast bonus', // Duński
                    'de' => 'Fester Bonus', // Niemiecki
                    'dv' => 'މިއަދަދާ ފިކްސްތް ބޮނަސް', // Divehi
                    'dz' => 'རྟག་ཏུ་བརྒྱ་ཆ་གྱི་དོ་དམག', // Dzongkha
                    'el' => 'Σταθερό μπόνους', // Grecki
                    'en' => 'Fixed bonus', // Angielski
                    'es' => 'Bono fijo', // Hiszpański
                    'et' => 'Fikseeritud boonus', // Estoński
                    'fa' => 'پاداش ثابت', // Perski
                    'fi' => 'Kiinteä bonus', // Fiński
                    'fr' => 'Prime fixe', // Francuski
                    'he' => 'בונוס קבוע', // Hebrajski
                    'hi' => 'स्थिर बोनस', // Hindi
                    'hr' => 'Fiksni bonus', // Chorwacki
                    'hu' => 'Fix bónusz', // Węgierski
                    'hy' => 'Մշտական բոնուս', // Ormiański
                    'id' => 'Bonus tetap', // Indonezyjski
                    'is' => 'Fastur bónus', // Islandzki
                    'it' => 'Bonus fisso', // Włoski
                    'ja' => '固定ボーナス', // Japoński
                    'ka' => 'ფიქსირებული ბონუსი', // Gruziński
                    'km' => 'ប្រាក់លើកទឹកចិត្តថេរ', // Khmerski
                    'ko' => '고정 보너스', // Koreański
                    'lb' => 'Feste Prime', // Luksemburski
                    'lo' => 'ໂບນັດຄົງທີ່', // Laotański
                    'lt' => 'Fiksuota premija', // Litewski
                    'lv' => 'Fiksēta prēmija', // Łotewski
                    'me' => 'Fiksni bonus', // Czarnogórski
                    'mk' => 'Фиксен бонус', // Macedoński
                    'mn' => 'Тогтмол урамшуулал', // Mongołski
                    'ms' => 'Bonus tetap', // Malajski
                    'my' => 'အမြဲတမ်းပိုဆု', // Birmański
                    'ne' => 'स्थिर बोनस', // Nepalski
                    'nl' => 'Vaste bonus', // Holenderski
                    'no' => 'Fast bonus', // Norweski
                    'pl' => 'Stała premia', // Polski
                    'ps' => 'ثابت جایزه', // Paszto
                    'pt' => 'Bónus fixo', // Portugalski
                    'ro' => 'Primă fixă', // Rumuński
                    'ru' => 'Фиксированная премия', // Rosyjski
                    'si' => 'ස්ථීර බෝනස්', // Syngaleski
                    'sk' => 'Fixná prémia', // Słowacki
                    'sl' => 'Fiksna premija', // Słoweński
                    'sq' => 'Premi fikse', // Albański
                    'sr' => 'Фиксна премија', // Serbski
                    'sv' => 'Fast bonus', // Szwedzki
                    'tg' => 'Бонуси доимӣ', // Tadżycki
                    'th' => 'โบนัสคงที่', // Tajski
                    'tk' => 'Durnukly bonus', // Turkmeński
                    'tr' => 'Sabit bonus', // Turecki
                    'uk' => 'Фіксована премія', // Ukraiński
                    'uz' => 'Doimiy bonus', // Uzbecki
                    'vi' => 'Thưởng cố định', // Wietnamski
                    'zh' => '固定奖金' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 4,
                'name' => json_encode([
                    'am' => 'ለውጤቶች ቅርብ ግምት', // Amharski
                    'ar' => 'مكافأة على الأداء', // Arabski
                    'az' => 'Nəticələrə görə mükafat', // Azerski
                    'be' => 'Прэмія за вынікі', // Białoruski
                    'bg' => 'Бонус за резултати', // Bułgarski
                    'bn' => 'ফলাফলের জন্য বোনাস', // Bengalski
                    'bs' => 'Bonus za rezultate', // Bośniacki
                    'ca' => 'Prima per resultats', // Kataloński
                    'cs' => 'Prémie za výsledky', // Czeski
                    'da' => 'Bonus for resultater', // Duński
                    'de' => 'Leistungsbonus', // Niemiecki
                    'dv' => 'ނަތީޖާއަށް ބޮނަސް', // Divehi
                    'dz' => 'བཀྲིས་བསྡུར་དང་གཏན་ཁེལ།', // Dzongkha
                    'el' => 'Μπόνους για αποτελέσματα', // Grecki
                    'en' => 'Performance bonus', // Angielski
                    'es' => 'Bono por resultados', // Hiszpański
                    'et' => 'Tulemuste boonus', // Estoński
                    'fa' => 'پاداش بابت نتایج', // Perski
                    'fi' => 'Tulospalkkio', // Fiński
                    'fr' => 'Prime de performance', // Francuski
                    'he' => 'בונוס על תוצאות', // Hebrajski
                    'hi' => 'परिणामों के लिए बोनस', // Hindi
                    'hr' => 'Bonus za rezultate', // Chorwacki
                    'hu' => 'Teljesítménybónusz', // Węgierski
                    'hy' => 'Պարգևատրում արդյունքների համար', // Ormiański
                    'id' => 'Bonus berdasarkan hasil', // Indonezyjski
                    'is' => 'Árangursbónus', // Islandzki
                    'it' => 'Bonus per risultati', // Włoski
                    'ja' => '成果ボーナス', // Japoński
                    'ka' => 'შედეგებზე პრემია', // Gruziński
                    'km' => 'ប្រាក់លើកទឹកចិត្តតាមលទ្ធផល', // Khmerski
                    'ko' => '성과 보너스', // Koreański
                    'lb' => 'Prime fir Resultater', // Luksemburski
                    'lo' => 'ໂບນັດສຳລັບຜົນງານ', // Laotański
                    'lt' => 'Premija už rezultatus', // Litewski
                    'lv' => 'Prēmija par rezultātiem', // Łotewski
                    'me' => 'Bonus za rezultate', // Czarnogórski
                    'mk' => 'Бонус за резултати', // Macedoński
                    'mn' => 'Үр дүнгийн урамшуулал', // Mongołski
                    'ms' => 'Bonus berdasarkan hasil', // Malajski
                    'my' => 'ရလဒ်အတွက်ပိုဆု', // Birmański
                    'ne' => 'परिणामहरूको लागि बोनस', // Nepalski
                    'nl' => 'Bonus voor resultaten', // Holenderski
                    'no' => 'Bonus for resultater', // Norweski
                    'pl' => 'Premia za wyniki', // Polski
                    'ps' => 'د پایلو لپاره جایزه', // Paszto
                    'pt' => 'Bónus por resultados', // Portugalski
                    'ro' => 'Bonus pentru rezultate', // Rumuński
                    'ru' => 'Бонус за результаты', // Rosyjski
                    'si' => 'ප්‍රතිඵල සඳහා බෝනස්', // Syngaleski
                    'sk' => 'Prémia za výsledky', // Słowacki
                    'sl' => 'Premija za rezultate', // Słoweński
                    'sq' => 'Bonus për rezultate', // Albański
                    'sr' => 'Бонус за резултате', // Serbski
                    'sv' => 'Bonus för resultat', // Szwedzki
                    'tg' => 'Бонус барои натиҷаҳо', // Tadżycki
                    'th' => 'โบนัสตามผลลัพธ์', // Tajski
                    'tk' => 'Netijelere görä bonus', // Turkmeński
                    'tr' => 'Sonuçlar için bonus', // Turecki
                    'uk' => 'Бонус за результати', // Ukraiński
                    'uz' => 'Natijalar uchun bonus', // Uzbecki
                    'vi' => 'Thưởng theo kết quả', // Wietnamski
                    'zh' => '业绩奖金' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 5,
                'name' => json_encode([
                    'am' => 'ኮሚሽን', // Amharski
                    'ar' => 'عمولة', // Arabski
                    'az' => 'Komissiya', // Azerski
                    'be' => 'Камісія', // Białoruski
                    'bg' => 'Комисиона', // Bułgarski
                    'bn' => 'কমিশন', // Bengalski
                    'bs' => 'Provizija', // Bośniacki
                    'ca' => 'Comissió', // Kataloński
                    'cs' => 'Provize', // Czeski
                    'da' => 'Kommission', // Duński
                    'de' => 'Provision', // Niemiecki
                    'dv' => 'ކޮމިޝަން', // Divehi
                    'dz' => 'ཚོགས་འདུ', // Dzongkha
                    'el' => 'Προμήθεια', // Grecki
                    'en' => 'Commission', // Angielski
                    'es' => 'Comisión', // Hiszpański
                    'et' => 'Komisjon', // Estoński
                    'fa' => 'کمیسیون', // Perski
                    'fi' => 'Provisio', // Fiński
                    'fr' => 'Commission', // Francuski
                    'he' => 'עמלה', // Hebrajski
                    'hi' => 'कमीशन', // Hindi
                    'hr' => 'Provizija', // Chorwacki
                    'hu' => 'Jutalék', // Węgierski
                    'hy' => 'Հանձնաժողով', // Ormiański
                    'id' => 'Komisi', // Indonezyjski
                    'is' => 'Þóknun', // Islandzki
                    'it' => 'Commissione', // Włoski
                    'ja' => '手数料', // Japoński
                    'ka' => 'კომისია', // Gruziński
                    'km' => 'កម្រៃជើងសា', // Khmerski
                    'ko' => '수수료', // Koreański
                    'lb' => 'Kommissioun', // Luksemburski
                    'lo' => 'ຄ່ານາຍໜ້າ', // Laotański
                    'lt' => 'Komisija', // Litewski
                    'lv' => 'Komisija', // Łotewski
                    'me' => 'Provizija', // Czarnogórski
                    'mk' => 'Провизија', // Macedoński
                    'mn' => 'Комиссын', // Mongołski
                    'ms' => 'Komisen', // Malajski
                    'my' => 'ကော်မရှင်', // Birmański
                    'ne' => 'कमिसन', // Nepalski
                    'nl' => 'Commissie', // Holenderski
                    'no' => 'Provisjon', // Norweski
                    'pl' => 'Prowizja', // Polski
                    'ps' => 'کمیسیون', // Paszto
                    'pt' => 'Comissão', // Portugalski
                    'ro' => 'Comision', // Rumuński
                    'ru' => 'Комиссия', // Rosyjski
                    'si' => 'කොමිස්', // Syngaleski
                    'sk' => 'Provízia', // Słowacki
                    'sl' => 'Provizija', // Słoweński
                    'sq' => 'Komision', // Albański
                    'sr' => 'Провизија', // Serbski
                    'sv' => 'Provision', // Szwedzki
                    'tg' => 'Комиссия', // Tadżycki
                    'th' => 'ค่าคอมมิชชั่น', // Tajski
                    'tk' => 'Komissiýa', // Turkmeński
                    'tr' => 'Komisyon', // Turecki
                    'uk' => 'Комісія', // Ukraiński
                    'uz' => 'Komissiya', // Uzbecki
                    'vi' => 'Hoa hồng', // Wietnamski
                    'zh' => '佣金' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],[
                'id' => 6,
                'name' => json_encode([
                    'am' => 'ተጨማሪ', // Amharski
                    'ar' => 'إضافة', // Arabski
                    'az' => 'Əlavə', // Azerski
                    'be' => 'Дадатак', // Białoruski
                    'bg' => 'Допълнение', // Bułgarski
                    'bn' => 'অতিরিক্ত', // Bengalski
                    'bs' => 'Dodatak', // Bośniacki
                    'ca' => 'Complement', // Kataloński
                    'cs' => 'Příplatek', // Czeski
                    'da' => 'Tillæg', // Duński
                    'de' => 'Zulage', // Niemiecki
                    'dv' => 'ތަކުންދެން', // Divehi
                    'dz' => 'མང་བདེན།', // Dzongkha
                    'el' => 'Επίδομα', // Grecki
                    'en' => 'Allowance', // Angielski
                    'es' => 'Complemento', // Hiszpański
                    'et' => 'Lisa', // Estoński
                    'fa' => 'افزونه', // Perski
                    'fi' => 'Lisä', // Fiński
                    'fr' => 'Complément', // Francuski
                    'he' => 'תוספת', // Hebrajski
                    'hi' => 'भत्ता', // Hindi
                    'hr' => 'Dodatak', // Chorwacki
                    'hu' => 'Pótlék', // Węgierski
                    'hy' => 'Լրացում', // Ormiański
                    'id' => 'Tambahan', // Indonezyjski
                    'is' => 'Viðbót', // Islandzki
                    'it' => 'Indennità', // Włoski
                    'ja' => '手当', // Japoński
                    'ka' => 'დანამატი', // Gruziński
                    'km' => 'បន្ថែម', // Khmerski
                    'ko' => '수당', // Koreański
                    'lb' => 'Zousaz', // Luksemburski
                    'lo' => 'ເພີ່ມເຕີມ', // Laotański
                    'lt' => 'Priedas', // Litewski
                    'lv' => 'Pabalsts', // Łotewski
                    'me' => 'Dodatak', // Czarnogórski
                    'mk' => 'Додаток', // Macedoński
                    'mn' => 'Нэмэлт', // Mongołski
                    'ms' => 'Elaun', // Malajski
                    'my' => 'အပိုဆောင်း', // Birmański
                    'ne' => 'भत्ता', // Nepalski
                    'nl' => 'Toelage', // Holenderski
                    'no' => 'Tillegg', // Norweski
                    'pl' => 'Dodatek', // Polski
                    'ps' => 'اضافه', // Paszto
                    'pt' => 'Adicional', // Portugalski
                    'ro' => 'Indemnizație', // Rumuński
                    'ru' => 'Доплата', // Rosyjski
                    'si' => 'අමතර', // Syngaleski
                    'sk' => 'Príplatok', // Słowacki
                    'sl' => 'Dodatek', // Słoweński
                    'sq' => 'Shtesë', // Albański
                    'sr' => 'Додатак', // Serbski
                    'sv' => 'Tillägg', // Szwedzki
                    'tg' => 'Иловагӣ', // Tadżycki
                    'th' => 'เบี้ยเลี้ยง', // Tajski
                    'tk' => 'Goşmaça', // Turkmeński
                    'tr' => 'Ek', // Turecki
                    'uk' => 'Доплата', // Ukraiński
                    'uz' => 'Qoʻshimcha', // Uzbecki
                    'vi' => 'Phụ cấp', // Wietnamski
                    'zh' => '津贴' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 7,
                'name' => json_encode([
                    'am' => 'ተጨማሪ ሰዓት', // Amharski
                    'ar' => 'ساعات إضافية', // Arabski
                    'az' => 'Əlavə saatlar', // Azerski
                    'be' => 'Звышурочныя гадзіны', // Białoruski
                    'bg' => 'Извънредни часове', // Bułgarski
                    'bn' => 'অতিরিক্ত সময়', // Bengalski
                    'bs' => 'Prekovremeni sati', // Bośniacki
                    'ca' => 'Hores extres', // Kataloński
                    'cs' => 'Přesčasy', // Czeski
                    'da' => 'Overarbejde', // Duński
                    'de' => 'Überstunden', // Niemiecki
                    'dv' => 'އިތުރަށް ގެންނަން', // Divehi
                    'dz' => 'དཀར་དོག་སྔོན་འཇུག', // Dzongkha
                    'el' => 'Υπερωρίες', // Grecki
                    'en' => 'Overtime', // Angielski
                    'es' => 'Horas extras', // Hiszpański
                    'et' => 'Ületunnid', // Estoński
                    'fa' => 'اضافه‌کاری', // Perski
                    'fi' => 'Ylityöt', // Fiński
                    'fr' => 'Heures supplémentaires', // Francuski
                    'he' => 'שעות נוספות', // Hebrajski
                    'hi' => 'अतिरिक्त समय', // Hindi
                    'hr' => 'Prekovremeni sati', // Chorwacki
                    'hu' => 'Túlóra', // Węgierski
                    'hy' => 'Ավելացրած ժամեր', // Ormiański
                    'id' => 'Lembur', // Indonezyjski
                    'is' => 'Yfirvinna', // Islandzki
                    'it' => 'Straordinari', // Włoski
                    'ja' => '残業', // Japoński
                    'ka' => 'ზედმეტი საათები', // Gruziński
                    'km' => 'ម៉ោងបន្ថែម', // Khmerski
                    'ko' => '초과 근무', // Koreański
                    'lb' => 'Iwwerstonnen', // Luksemburski
                    'lo' => 'ເວລາເພີ່ມເຕີມ', // Laotański
                    'lt' => 'Viršvalandžiai', // Litewski
                    'lv' => 'Virsstundas', // Łotewski
                    'me' => 'Prekovremeni sati', // Czarnogórski
                    'mk' => 'Прекувремени часови', // Macedoński
                    'mn' => 'Илүү цаг', // Mongołski
                    'ms' => 'Kerja lebih masa', // Malajski
                    'my' => 'အချိန်ပို', // Birmański
                    'ne' => 'अतिरिक्त समय', // Nepalski
                    'nl' => 'Overuren', // Holenderski
                    'no' => 'Overtid', // Norweski
                    'pl' => 'Nadgodziny', // Polski
                    'ps' => 'اضافي ساعتونه', // Paszto
                    'pt' => 'Horas extras', // Portugalski
                    'ro' => 'Ore suplimentare', // Rumuński
                    'ru' => 'Сверхурочные часы', // Rosyjski
                    'si' => 'අතිකාල', // Syngaleski
                    'sk' => 'Nadčasy', // Słowacki
                    'sl' => 'Nadure', // Słoweński
                    'sq' => 'Orë shtesë', // Albański
                    'sr' => 'Прековремени сати', // Serbski
                    'sv' => 'Övertid', // Szwedzki
                    'tg' => 'Соатҳои изофа', // Tadżycki
                    'th' => 'ทำงานล่วงเวลา', // Tajski
                    'tk' => 'Çykdajy wagt', // Turkmeński
                    'tr' => 'Fazla mesai', // Turecki
                    'uk' => 'Надурочні години', // Ukraiński
                    'uz' => 'Qo‘shimcha ish soati', // Uzbecki
                    'vi' => 'Làm thêm giờ', // Wietnamski
                    'zh' => '加班' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],[
                'id' => 8,
                'name' => json_encode([
                    'am' => 'ተወካዮች', // Amharski
                    'ar' => 'الوفود', // Arabski
                    'az' => 'Delegasiyalar', // Azerski
                    'be' => 'Дэлегацыі', // Białoruski
                    'bg' => 'Делегации', // Bułgarski
                    'bn' => 'প্রতিনিধি দল', // Bengalski
                    'bs' => 'Delegacije', // Bośniacki
                    'ca' => 'Delegacions', // Kataloński
                    'cs' => 'Delegace', // Czeski
                    'da' => 'Delegationer', // Duński
                    'de' => 'Delegationen', // Niemiecki
                    'dv' => 'ޑެލެގޭޝަން', // Divehi
                    'dz' => 'ཁྲིམས་རྩོད', // Dzongkha
                    'el' => 'Αντιπροσωπείες', // Grecki
                    'en' => 'Delegations', // Angielski
                    'es' => 'Delegaciones', // Hiszpański
                    'et' => 'Delegatsioonid', // Estoński
                    'fa' => 'هیئت‌ها', // Perski
                    'fi' => 'Valtuuskunnat', // Fiński
                    'fr' => 'Délégations', // Francuski
                    'he' => 'משלחות', // Hebrajski
                    'hi' => 'प्रत्यायोजित', // Hindi
                    'hr' => 'Delegacije', // Chorwacki
                    'hu' => 'Delegációk', // Węgierski
                    'hy' => 'Պատվիրակություններ', // Ormiański
                    'id' => 'Delegasi', // Indonezyjski
                    'is' => 'Sendinefndir', // Islandzki
                    'it' => 'Delegazioni', // Włoski
                    'ja' => '代表団', // Japoński
                    'ka' => 'დელეგაციები', // Gruziński
                    'km' => 'អ្នកតំណាង', // Khmerski
                    'ko' => '대표단', // Koreański
                    'lb' => 'Delegatiounen', // Luksemburski
                    'lo' => 'ຄະນະຜູ້ແທນ', // Laotański
                    'lt' => 'Delegacijos', // Litewski
                    'lv' => 'Delegācijas', // Łotewski
                    'me' => 'Delegacije', // Czarnogórski
                    'mk' => 'Делегации', // Macedoński
                    'mn' => 'Төлөөлөгчид', // Mongołski
                    'ms' => 'Delegasi', // Malajski
                    'my' => 'ကိုယ်စားလှယ်အဖွဲ့များ', // Birmański
                    'ne' => 'प्रतिनिधि मण्डल', // Nepalski
                    'nl' => 'Delegaties', // Holenderski
                    'no' => 'Delegasjoner', // Norweski
                    'pl' => 'Delegacje', // Polski
                    'ps' => 'هیئتونه', // Paszto
                    'pt' => 'Delegações', // Portugalski
                    'ro' => 'Delegații', // Rumuński
                    'ru' => 'Делегации', // Rosyjski
                    'si' => 'යාත්‍රික', // Syngaleski
                    'sk' => 'Delegácie', // Słowacki
                    'sl' => 'Delegacije', // Słoweński
                    'sq' => 'Delegacione', // Albański
                    'sr' => 'Делегације', // Serbski
                    'sv' => 'Delegationer', // Szwedzki
                    'tg' => 'Ваколатдорӣ', // Tadżycki
                    'th' => 'คณะผู้แทน', // Tajski
                    'tk' => 'Wekilçilikler', // Turkmeński
                    'tr' => 'Delegasyonlar', // Turecki
                    'uk' => 'Делегації', // Ukraiński
                    'uz' => 'Delegatsiyalar', // Uzbecki
                    'vi' => 'Phái đoàn', // Wietnamski
                    'zh' => '代表团' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ]
        ];
        DB::table('pay_systems')->insert($pay_systems);
    }
}
