<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        $points=[
            'am' => 'ነጥቦች', // Amharski
            'ar' => 'نقاط', // Arabski
            'az' => 'Nöqtələr', // Azerski
            'be' => 'Кропкі', // Białoruski
            'bg' => 'Точки', // Bułgarski
            'bn' => 'পয়েন্ট', // Bengalski
            'bs' => 'Bodovi', // Bośniacki
            'ca' => 'Punts', // Kataloński
            'cs' => 'Body', // Czeski
            'da' => 'Punkter', // Duński
            'de' => 'Punkte', // Niemiecki
            'dv' => 'ޕުނކްޓޯޝަށް', // Divehi
            'dz' => 'མིང་གོང་ལོན།', // Dzongkha
            'el' => 'Σημεία', // Grecki
            'en' => 'Points', // Angielski
            'es' => 'Puntos', // Hiszpański
            'et' => 'Punktid', // Estoński
            'fa' => 'نقاط', // Perski
            'fi' => 'Pisteet', // Fiński
            'fr' => 'Points', // Francuski
            'he' => 'נקודות', // Hebrajski
            'hi' => 'बिंदु', // Hindi
            'hr' => 'Bodovi', // Chorwacki
            'hu' => 'Pontok', // Węgierski
            'hy' => 'Թետեր', // Ormiański
            'id' => 'Poin', // Indonezyjski
            'is' => 'Punktar', // Islandzki
            'it' => 'Punti', // Włoski
            'ja' => 'ポイント', // Japoński
            'ka' => 'ქულები', // Gruziński
            'km' => 'ពិន្ទុ', // Khmerski
            'ko' => '점수', // Koreański
            'lb' => 'Punkten', // Luksemburski
            'lo' => 'ເຈົາລະດັບ', // Laotański
            'lt' => 'Taškai', // Litewski
            'lv' => 'Punkti', // Łotewski
            'me' => 'Bodovi', // Czarnogórski
            'mk' => 'Поени', // Macedoński
            'mn' => 'Точка', // Mongołski
            'ms' => 'Mata', // Malajski
            'my' => 'အမှတ်', // Birmański
            'ne' => 'अंक', // Nepalski
            'nl' => 'Punten', // Holenderski
            'no' => 'Poeng', // Norweski
            'pl' => 'Punkty', // Polski
            'ps' => 'پوائنټونه', // Paszto
            'pt' => 'Pontos', // Portugalski
            'ro' => 'Puncte', // Rumuński
            'ru' => 'Очки', // Rosyjski
            'si' => 'ඉලක්ක', // Syngaleski
            'sk' => 'Body', // Słowacki
            'sl' => 'Točke', // Słoweński
            'sq' => 'Pikë', // Albański
            'sr' => 'Поени', // Serbski
            'sv' => 'Poäng', // Szwedzki
            'tg' => 'Нуқтаҳо', // Tadżycki
            'th' => 'คะแนน', // Tajski
            'tk' => 'Poçtalar', // Turkmeński
            'tr' => 'Puanlar', // Turecki
            'uk' => 'Бали', // Ukraiński
            'uz' => 'Ballar', // Uzbecki
            'vi' => 'Điểm', // Wietnamski
            'zh' => '分数' // Chiński
        ];

        DB::table('products')->truncate();

        $products = [
            ['id' => 1, 'points'=>1000,'price'=>30.00,'product_type'=>'Points','type'=>json_encode([
                $points
            ]),'name'=>json_encode([
                'am' => '1000 ነጥቦች', // Amharski
                'ar' => '1000 نقطة', // Arabski
                'az' => '1000 nöqtə', // Azerski
                'be' => '1000 кропак', // Białoruski
                'bg' => '1000 точки', // Bułgarski
                'bn' => '১০০০ পয়েন্ট', // Bengalski
                'bs' => '1000 bodova', // Bośniacki
                'ca' => '1000 punts', // Kataloński
                'cs' => '1000 bodů', // Czeski
                'da' => '1000 punkter', // Duński
                'de' => '1000 Punkte', // Niemiecki
                'dv' => '1000 ޕުންކްޓު', // Divehi
                'dz' => 'གཅིག་སྟོང་པའི་མིང་གོང་ལོན།', // Dzongkha
                'el' => '1000 σημεία', // Grecki
                'en' => '1000 points', // Angielski
                'es' => '1000 puntos', // Hiszpański
                'et' => '1000 punkti', // Estoński
                'fa' => '1000 امتیاز', // Perski
                'fi' => '1000 pistettä', // Fiński
                'fr' => '1000 points', // Francuski
                'he' => '1000 נקודות', // Hebrajski
                'hi' => '1000 अंक', // Hindi
                'hr' => '1000 bodova', // Chorwacki
                'hu' => '1000 pont', // Węgierski
                'hy' => '1000 միավոր', // Ormiański
                'id' => '1000 poin', // Indonezyjski
                'is' => '1000 punktar', // Islandzki
                'it' => '1000 punti', // Włoski
                'ja' => '1000ポイント', // Japoński
                'ka' => '1000 ქულა', // Gruziński
                'km' => '1000 ពិន្ទុ', // Khmerski
                'ko' => '1000점', // Koreański
                'lb' => '1000 Punkten', // Luksemburski
                'lo' => '1000 ຄະແນນ', // Laotański
                'lt' => '1000 taškų', // Litewski
                'lv' => '1000 punkti', // Łotewski
                'me' => '1000 bodova', // Czarnogórski
                'mk' => '1000 поени', // Macedoński
                'mn' => '1000 оноо', // Mongołski
                'ms' => '1000 mata', // Malajski
                'my' => '၁၀၀၀ အမှတ်', // Birmański
                'ne' => '१००० अंक', // Nepalski
                'nl' => '1000 punten', // Holenderski
                'no' => '1000 poeng', // Norweski
                'pl' => '1000 punktów', // Polski
                'ps' => '1000 پوائنټونه', // Paszto
                'pt' => '1000 pontos', // Portugalski
                'ro' => '1000 de puncte', // Rumuński
                'ru' => '1000 очков', // Rosyjski
                'si' => '1000 ලකුණු', // Syngaleski
                'sk' => '1000 bodov', // Słowacki
                'sl' => '1000 točk', // Słoweński
                'sq' => '1000 pikë', // Albański
                'sr' => '1000 поена', // Serbski
                'sv' => '1000 poäng', // Szwedzki
                'tg' => '1000 нуқта', // Tadżycki
                'th' => '1000 คะแนน', // Tajski
                'tk' => '1000 nokat', // Turkmeński
                'tr' => '1000 puan', // Turecki
                'uk' => '1000 балів', // Ukraiński
                'uz' => '1000 ball', // Uzbecki
                'vi' => '1000 điểm', // Wietnamski
                'zh' => '1000分' // Chiński
            ]),'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
            ['id' => 2, 'points'=>3000, 'price'=>80.00,'product_type'=>'Points','type'=>json_encode([
                $points
            ]),'name'=>json_encode([
                'am' => '3000 ነጥቦች', // Amharski
                'ar' => '3000 نقطة', // Arabski
                'az' => '3000 nöqtə', // Azerski
                'be' => '3000 кропак', // Białoruski
                'bg' => '3000 точки', // Bułgarski
                'bn' => '৩,০০০ পয়েন্ট', // Bengalski
                'bs' => '3000 bodova', // Bośniacki
                'ca' => '3000 punts', // Kataloński
                'cs' => '3000 bodů', // Czeski
                'da' => '3000 punkter', // Duński
                'de' => '3000 Punkte', // Niemiecki
                'dv' => '3000 ޕުންކްޓު', // Divehi
                'dz' => 'ལོན་གྱི་མིང་ལས་ 3000།', // Dzongkha
                'el' => '3000 σημεία', // Grecki
                'en' => '3000 points', // Angielski
                'es' => '3000 puntos', // Hiszpański
                'et' => '3000 punkti', // Estoński
                'fa' => '3000 امتیاز', // Perski
                'fi' => '3000 pistettä', // Fiński
                'fr' => '3000 points', // Francuski
                'he' => '3000 נקודות', // Hebrajski
                'hi' => '3000 अंक', // Hindi
                'hr' => '3000 bodova', // Chorwacki
                'hu' => '3000 pont', // Węgierski
                'hy' => '3000 միավոր', // Ormiański
                'id' => '3000 poin', // Indonezyjski
                'is' => '3000 punktar', // Islandzki
                'it' => '3000 punti', // Włoski
                'ja' => '3000ポイント', // Japoński
                'ka' => '3000 ქულა', // Gruziński
                'km' => '3000 ពិន្ទុ', // Khmerski
                'ko' => '3000점', // Koreański
                'lb' => '3000 Punkten', // Luksemburski
                'lo' => '3000 ຄະແນນ', // Laotański
                'lt' => '3000 taškų', // Litewski
                'lv' => '3000 punkti', // Łotewski
                'me' => '3000 bodova', // Czarnogórski
                'mk' => '3000 поени', // Macedoński
                'mn' => '3000 оноо', // Mongołski
                'ms' => '3000 mata', // Malajski
                'my' => '၃၀၀၀ အမှတ်', // Birmański
                'ne' => '३००० अंक', // Nepalski
                'nl' => '3000 punten', // Holenderski
                'no' => '3000 poeng', // Norweski
                'pl' => '3000 punktów', // Polski
                'ps' => '3000 پوائنټونه', // Paszto
                'pt' => '3000 pontos', // Portugalski
                'ro' => '3000 de puncte', // Rumuński
                'ru' => '3000 очков', // Rosyjski
                'si' => '3000 ලකුණු', // Syngaleski
                'sk' => '3000 bodov', // Słowacki
                'sl' => '3000 točk', // Słoweński
                'sq' => '3000 pikë', // Albański
                'sr' => '3000 поена', // Serbski
                'sv' => '3000 poäng', // Szwedzki
                'tg' => '3000 нуқта', // Tadżycki
                'th' => '3000 คะแนน', // Tajski
                'tk' => '3000 nokat', // Turkmeński
                'tr' => '3000 puan', // Turecki
                'uk' => '3000 балів', // Ukraiński
                'uz' => '3000 ball', // Uzbecki
                'vi' => '3000 điểm', // Wietnamski
                'zh' => '3000分' // Chiński
            ]),'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
            ['id' => 3, 'points'=>5000, 'price'=>120.00,'product_type'=>'Points','type'=>json_encode([
                $points
            ]),'name'=>json_encode([
                'am' => '5000 ነጥቦች', // Amharski
                'ar' => '5000 نقطة', // Arabski
                'az' => '5000 nöqtə', // Azerski
                'be' => '5000 кропак', // Białoruski
                'bg' => '5000 точки', // Bułgarski
                'bn' => '৫,০০০ পয়েন্ট', // Bengalski
                'bs' => '5000 bodova', // Bośniacki
                'ca' => '5000 punts', // Kataloński
                'cs' => '5000 bodů', // Czeski
                'da' => '5000 punkter', // Duński
                'de' => '5000 Punkte', // Niemiecki
                'dv' => '5000 ޕުންކްޓު', // Divehi
                'dz' => 'ལོན་གྱི་མིང་ལས་ 5000།', // Dzongkha
                'el' => '5000 σημεία', // Grecki
                'en' => '5000 points', // Angielski
                'es' => '5000 puntos', // Hiszpański
                'et' => '5000 punkti', // Estoński
                'fa' => '5000 امتیاز', // Perski
                'fi' => '5000 pistettä', // Fiński
                'fr' => '5000 points', // Francuski
                'he' => '5000 נקודות', // Hebrajski
                'hi' => '5000 अंक', // Hindi
                'hr' => '5000 bodova', // Chorwacki
                'hu' => '5000 pont', // Węgierski
                'hy' => '5000 միավոր', // Ormiański
                'id' => '5000 poin', // Indonezyjski
                'is' => '5000 punktar', // Islandzki
                'it' => '5000 punti', // Włoski
                'ja' => '5000ポイント', // Japoński
                'ka' => '5000 ქულა', // Gruziński
                'km' => '5000 ពិន្ទុ', // Khmerski
                'ko' => '5000점', // Koreański
                'lb' => '5000 Punkten', // Luksemburski
                'lo' => '5000 ຄະແນນ', // Laotański
                'lt' => '5000 taškų', // Litewski
                'lv' => '5000 punkti', // Łotewski
                'me' => '5000 bodova', // Czarnogórski
                'mk' => '5000 поени', // Macedoński
                'mn' => '5000 оноо', // Mongołski
                'ms' => '5000 mata', // Malajski
                'my' => '၅၀၀၀ အမှတ်', // Birmański
                'ne' => '५००० अंक', // Nepalski
                'nl' => '5000 punten', // Holenderski
                'no' => '5000 poeng', // Norweski
                'pl' => '5000 punktów', // Polski
                'ps' => '5000 پوائنټونه', // Paszto
                'pt' => '5000 pontos', // Portugalski
                'ro' => '5000 de puncte', // Rumuński
                'ru' => '5000 очков', // Rosyjski
                'si' => '5000 ලකුණු', // Syngaleski
                'sk' => '5000 bodov', // Słowacki
                'sl' => '5000 točk', // Słoweński
                'sq' => '5000 pikë', // Albański
                'sr' => '5000 поена', // Serbski
                'sv' => '5000 poäng', // Szwedzki
                'tg' => '5000 нуқта', // Tadżycki
                'th' => '5000 คะแนน', // Tajski
                'tk' => '5000 nokat', // Turkmeński
                'tr' => '5000 puan', // Turecki
                'uk' => '5000 балів', // Ukraiński
                'uz' => '5000 ball', // Uzbecki
                'vi' => '5000 điểm', // Wietnamski
                'zh' => '5000分' // Chiński
            ]),'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
            ['id' => 4, 'points'=>10000, 'price'=>220.00,'product_type'=>'Points','type'=>json_encode([
                $points
            ]),'name'=>json_encode([
                'am' => '10000 ነጥቦች', // Amharski
                'ar' => '10000 نقطة', // Arabski
                'az' => '10000 nöqtə', // Azerski
                'be' => '10000 кропак', // Białoruski
                'bg' => '10000 точки', // Bułgarski
                'bn' => '১০,০০০ পয়েন্ট', // Bengalski
                'bs' => '10000 bodova', // Bośniacki
                'ca' => '10000 punts', // Kataloński
                'cs' => '10000 bodů', // Czeski
                'da' => '10000 punkter', // Duński
                'de' => '10000 Punkte', // Niemiecki
                'dv' => '10000 ޕުންކްޓު', // Divehi
                'dz' => 'གཅིག་སྟོང་དང་པོ་མིང་གོང་ལོན།', // Dzongkha
                'el' => '10000 σημεία', // Grecki
                'en' => '10000 points', // Angielski
                'es' => '10000 puntos', // Hiszpański
                'et' => '10000 punkti', // Estoński
                'fa' => '10000 امتیاز', // Perski
                'fi' => '10000 pistettä', // Fiński
                'fr' => '10000 points', // Francuski
                'he' => '10000 נקודות', // Hebrajski
                'hi' => '10000 अंक', // Hindi
                'hr' => '10000 bodova', // Chorwacki
                'hu' => '10000 pont', // Węgierski
                'hy' => '10000 միավոր', // Ormiański
                'id' => '10000 poin', // Indonezyjski
                'is' => '10000 punktar', // Islandzki
                'it' => '10000 punti', // Włoski
                'ja' => '10000ポイント', // Japoński
                'ka' => '10000 ქულა', // Gruziński
                'km' => '10000 ពិន្ទុ', // Khmerski
                'ko' => '10000점', // Koreański
                'lb' => '10000 Punkten', // Luksemburski
                'lo' => '10000 ຄະແນນ', // Laotański
                'lt' => '10000 taškų', // Litewski
                'lv' => '10000 punkti', // Łotewski
                'me' => '10000 bodova', // Czarnogórski
                'mk' => '10000 поени', // Macedoński
                'mn' => '10000 оноо', // Mongołski
                'ms' => '10000 mata', // Malajski
                'my' => '၁၀၀၀၀ အမှတ်', // Birmański
                'ne' => '१०००० अंक', // Nepalski
                'nl' => '10000 punten', // Holenderski
                'no' => '10000 poeng', // Norweski
                'pl' => '10000 punktów', // Polski
                'ps' => '10000 پوائنټونه', // Paszto
                'pt' => '10000 pontos', // Portugalski
                'ro' => '10000 de puncte', // Rumuński
                'ru' => '10000 очков', // Rosyjski
                'si' => '10000 ලකුණු', // Syngaleski
                'sk' => '10000 bodov', // Słowacki
                'sl' => '10000 točk', // Słoweński
                'sq' => '10000 pikë', // Albański
                'sr' => '10000 поена', // Serbski
                'sv' => '10000 poäng', // Szwedzki
                'tg' => '10000 нуқта', // Tadżycki
                'th' => '10000 คะแนน', // Tajski
                'tk' => '10000 nokat', // Turkmeński
                'tr' => '10000 puan', // Turecki
                'uk' => '10000 балів', // Ukraiński
                'uz' => '10000 ball', // Uzbecki
                'vi' => '10000 điểm', // Wietnamski
                'zh' => '10000分' // Chiński
            ]),'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
            ['id' => 5, 'points'=>30000, 'price'=>630.00,'product_type'=>'Points','type'=>json_encode([
                $points
            ]),'name'=>json_encode([
                'am' => '30000 ነጥቦች', // Amharski
                'ar' => '30000 نقطة', // Arabski
                'az' => '30000 nöqtə', // Azerski
                'be' => '30000 кропак', // Białoruski
                'bg' => '30000 точки', // Bułgarski
                'bn' => '৩০,০০০ পয়েন্ট', // Bengalski
                'bs' => '30000 bodova', // Bośniacki
                'ca' => '30000 punts', // Kataloński
                'cs' => '30000 bodů', // Czeski
                'da' => '30000 punkter', // Duński
                'de' => '30000 Punkte', // Niemiecki
                'dv' => '30000 ޕުންކްޓު', // Divehi
                'dz' => 'གསུམ་སྟོང་པའི་མིང་གོང་ལོན།', // Dzongkha
                'el' => '30000 σημεία', // Grecki
                'en' => '30000 points', // Angielski
                'es' => '30000 puntos', // Hiszpański
                'et' => '30000 punkti', // Estoński
                'fa' => '30000 امتیاز', // Perski
                'fi' => '30000 pistettä', // Fiński
                'fr' => '30000 points', // Francuski
                'he' => '30000 נקודות', // Hebrajski
                'hi' => '30000 अंक', // Hindi
                'hr' => '30000 bodova', // Chorwacki
                'hu' => '30000 pont', // Węgierski
                'hy' => '30000 միավոր', // Ormiański
                'id' => '30000 poin', // Indonezyjski
                'is' => '30000 punktar', // Islandzki
                'it' => '30000 punti', // Włoski
                'ja' => '30000ポイント', // Japoński
                'ka' => '30000 ქულა', // Gruziński
                'km' => '30000 ពិន្ទុ', // Khmerski
                'ko' => '30000점', // Koreański
                'lb' => '30000 Punkten', // Luksemburski
                'lo' => '30000 ຄະແນນ', // Laotański
                'lt' => '30000 taškų', // Litewski
                'lv' => '30000 punkti', // Łotewski
                'me' => '30000 bodova', // Czarnogórski
                'mk' => '30000 поени', // Macedoński
                'mn' => '30000 оноо', // Mongołski
                'ms' => '30000 mata', // Malajski
                'my' => '၃၀၀၀၀ အမှတ်', // Birmański
                'ne' => '३०००० अंक', // Nepalski
                'nl' => '30000 punten', // Holenderski
                'no' => '30000 poeng', // Norweski
                'pl' => '30000 punktów', // Polski
                'ps' => '30000 پوائنټونه', // Paszto
                'pt' => '30000 pontos', // Portugalski
                'ro' => '30000 de puncte', // Rumuński
                'ru' => '30000 очков', // Rosyjski
                'si' => '30000 ලකුණු', // Syngaleski
                'sk' => '30000 bodov', // Słowacki
                'sl' => '30000 točk', // Słoweński
                'sq' => '30000 pikë', // Albański
                'sr' => '30000 поена', // Serbski
                'sv' => '30000 poäng', // Szwedzki
                'tg' => '30000 нуқта', // Tadżycki
                'th' => '30000 คะแนน', // Tajski
                'tk' => '30000 nokat', // Turkmeński
                'tr' => '30000 puan', // Turecki
                'uk' => '30000 балів', // Ukraiński
                'uz' => '30000 ball', // Uzbecki
                'vi' => '30000 điểm', // Wietnamski
                'zh' => '30000分' // Chiński
            ]),'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
            ['id' => 6, 'points'=>50000, 'price'=>1000.00,'product_type'=>'Points','type'=>json_encode([
                $points
            ]),'name'=>json_encode([
                'am' => '50000 ነጥቦች', // Amharski
                'ar' => '50000 نقطة', // Arabski
                'az' => '50000 nöqtə', // Azerski
                'be' => '50000 кропак', // Białoruski
                'bg' => '50000 точки', // Bułgarski
                'bn' => '৫০,০০০ পয়েন্ট', // Bengalski
                'bs' => '50000 bodova', // Bośniacki
                'ca' => '50000 punts', // Kataloński
                'cs' => '50000 bodů', // Czeski
                'da' => '50000 punkter', // Duński
                'de' => '50000 Punkte', // Niemiecki
                'dv' => '50000 ޕުންކްޓު', // Divehi
                'dz' => 'ལོན་གྱི་མིང་ལས་ 50000།', // Dzongkha
                'el' => '50000 σημεία', // Grecki
                'en' => '50000 points', // Angielski
                'es' => '50000 puntos', // Hiszpański
                'et' => '50000 punkti', // Estoński
                'fa' => '50000 امتیاز', // Perski
                'fi' => '50000 pistettä', // Fiński
                'fr' => '50000 points', // Francuski
                'he' => '50000 נקודות', // Hebrajski
                'hi' => '50000 अंक', // Hindi
                'hr' => '50000 bodova', // Chorwacki
                'hu' => '50000 pont', // Węgierski
                'hy' => '50000 միավոր', // Ormiański
                'id' => '50000 poin', // Indonezyjski
                'is' => '50000 punktar', // Islandzki
                'it' => '50000 punti', // Włoski
                'ja' => '50000ポイント', // Japoński
                'ka' => '50000 ქულა', // Gruziński
                'km' => '50000 ពិន្ទុ', // Khmerski
                'ko' => '50000점', // Koreański
                'lb' => '50000 Punkten', // Luksemburski
                'lo' => '50000 ຄະແນນ', // Laotański
                'lt' => '50000 taškų', // Litewski
                'lv' => '50000 punkti', // Łotewski
                'me' => '50000 bodova', // Czarnogórski
                'mk' => '50000 поени', // Macedoński
                'mn' => '50000 оноо', // Mongołski
                'ms' => '50000 mata', // Malajski
                'my' => '၅၀၀၀၀ အမှတ်', // Birmański
                'ne' => '५०००० अंक', // Nepalski
                'nl' => '50000 punten', // Holenderski
                'no' => '50000 poeng', // Norweski
                'pl' => '50000 punktów', // Polski
                'ps' => '50000 پوائنټونه', // Paszto
                'pt' => '50000 pontos', // Portugalski
                'ro' => '50000 de puncte', // Rumuński
                'ru' => '50000 очков', // Rosyjski
                'si' => '50000 ලකුණු', // Syngaleski
                'sk' => '50000 bodov', // Słowacki
                'sl' => '50000 točk', // Słoweński
                'sq' => '50000 pikë', // Albański
                'sr' => '50000 поена', // Serbski
                'sv' => '50000 poäng', // Szwedzki
                'tg' => '50000 нуқта', // Tadżycki
                'th' => '50000 คะแนน', // Tajski
                'tk' => '50000 nokat', // Turkmeński
                'tr' => '50000 puan', // Turecki
                'uk' => '50000 балів', // Ukraiński
                'uz' => '50000 ball', // Uzbecki
                'vi' => '50000 điểm', // Wietnamski
                'zh' => '50000分' // Chiński
            ]), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
            ['id' => 7, 'points'=>100000, 'price'=>1800.00,'product_type'=>'Points','type'=>json_encode([
                $points
            ]),'name'=>json_encode([
                'am' => '100000 ነጥቦች', // Amharski
                'ar' => '100000 نقطة', // Arabski
                'az' => '100000 nöqtə', // Azerski
                'be' => '100000 кропак', // Białoruski
                'bg' => '100000 точки', // Bułgarski
                'bn' => '১,০০,০০০ পয়েন্ট', // Bengalski
                'bs' => '100000 bodova', // Bośniacki
                'ca' => '100000 punts', // Kataloński
                'cs' => '100000 bodů', // Czeski
                'da' => '100000 punkter', // Duński
                'de' => '100000 Punkte', // Niemiecki
                'dv' => '100000 ޕުންކްޓު', // Divehi
                'dz' => 'གཅིག་སྟོང་གཅིག་ཆང་མིང་གོང་ལོན།', // Dzongkha
                'el' => '100000 σημεία', // Grecki
                'en' => '100000 points', // Angielski
                'es' => '100000 puntos', // Hiszpański
                'et' => '100000 punkti', // Estoński
                'fa' => '100000 امتیاز', // Perski
                'fi' => '100000 pistettä', // Fiński
                'fr' => '100000 points', // Francuski
                'he' => '100000 נקודות', // Hebrajski
                'hi' => '100000 अंक', // Hindi
                'hr' => '100000 bodova', // Chorwacki
                'hu' => '100000 pont', // Węgierski
                'hy' => '100000 միավոր', // Ormiański
                'id' => '100000 poin', // Indonezyjski
                'is' => '100000 punktar', // Islandzki
                'it' => '100000 punti', // Włoski
                'ja' => '100000ポイント', // Japoński
                'ka' => '100000 ქულა', // Gruziński
                'km' => '100000 ពិន្ទុ', // Khmerski
                'ko' => '100000점', // Koreański
                'lb' => '100000 Punkten', // Luksemburski
                'lo' => '100000 ຄະແນນ', // Laotański
                'lt' => '100000 taškų', // Litewski
                'lv' => '100000 punkti', // Łotewski
                'me' => '100000 bodova', // Czarnogórski
                'mk' => '100000 поени', // Macedoński
                'mn' => '100000 оноо', // Mongołski
                'ms' => '100000 mata', // Malajski
                'my' => '၁၀၀၀၀၀ အမှတ်', // Birmański
                'ne' => '१,००,००० अंक', // Nepalski
                'nl' => '100000 punten', // Holenderski
                'no' => '100000 poeng', // Norweski
                'pl' => '100000 punktów', // Polski
                'ps' => '100000 پوائنټونه', // Paszto
                'pt' => '100000 pontos', // Portugalski
                'ro' => '100000 de puncte', // Rumuński
                'ru' => '100000 очков', // Rosyjski
                'si' => '100000 ලකුණු', // Syngaleski
                'sk' => '100000 bodov', // Słowacki
                'sl' => '100000 točk', // Słoweński
                'sq' => '100000 pikë', // Albański
                'sr' => '100000 поена', // Serbski
                'sv' => '100000 poäng', // Szwedzki
                'tg' => '100000 нуқта', // Tadżycki
                'th' => '100000 คะแนน', // Tajski
                'tk' => '100000 nokat', // Turkmeński
                'tr' => '100000 puan', // Turecki
                'uk' => '100000 балів', // Ukraiński
                'uz' => '100000 ball', // Uzbecki
                'vi' => '100000 điểm', // Wietnamski
                'zh' => '100000分' // Chiński
            ]),'created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
            ['id' => 8, 'points'=>0,'type'=>json_encode([
                'am' => 'ተጨማሪ', // Amharski
                'ar' => 'إضافي', // Arabski
                'az' => 'Əlavə', // Azerski
                'be' => 'Дадатковае', // Białoruski
                'bg' => 'Допълнително', // Bułgarski
                'bn' => 'অতিরিক্ত', // Bengalski
                'bs' => 'Dodatno', // Bośniacki
                'ca' => 'Addicional', // Kataloński
                'cs' => 'Dodatečné', // Czeski
                'da' => 'Yderligere', // Duński
                'de' => 'Zusätzlich', // Niemiecki
                'dv' => 'އިތުރަށް', // Divehi
                'dz' => 'མང་བདེན།', // Dzongkha
                'el' => 'Πρόσθετο', // Grecki
                'en' => 'Additional', // Angielski
                'es' => 'Adicional', // Hiszpański
                'et' => 'Täiendav', // Estoński
                'fa' => 'اضافی', // Perski
                'fi' => 'Lisä-', // Fiński
                'fr' => 'Supplémentaire', // Francuski
                'he' => 'נוסף', // Hebrajski
                'hi' => 'अतिरिक्त', // Hindi
                'hr' => 'Dodatno', // Chorwacki
                'hu' => 'További', // Węgierski
                'hy' => 'Լրացուցիչ', // Ormiański
                'id' => 'Tambahan', // Indonezyjski
                'is' => 'Viðbótar', // Islandzki
                'it' => 'Aggiuntivo', // Włoski
                'ja' => '追加の', // Japoński
                'ka' => 'დამატებითი', // Gruziński
                'km' => 'បន្ថែម', // Khmerski
                'ko' => '추가', // Koreański
                'lb' => 'Zousätzlech', // Luksemburski
                'lo' => 'ເພີ່ມເຕີມ', // Laotański
                'lt' => 'Papildomas', // Litewski
                'lv' => 'Papildu', // Łotewski
                'me' => 'Dodatno', // Czarnogórski
                'mk' => 'Дополнително', // Macedoński
                'mn' => 'Нэмэлт', // Mongołski
                'ms' => 'Tambahan', // Malajski
                'my' => 'ထပ်ဆောင်း', // Birmański
                'ne' => 'थप', // Nepalski
                'nl' => 'Extra', // Holenderski
                'no' => 'Ekstra', // Norweski
                'pl' => 'Dodatkowe', // Polski
                'ps' => 'اضافي', // Paszto
                'pt' => 'Adicional', // Portugalski
                'ro' => 'Suplimentar', // Rumuński
                'ru' => 'Дополнительное', // Rosyjski
                'si' => 'අමතර', // Syngaleski
                'sk' => 'Dodatočné', // Słowacki
                'sl' => 'Dodatno', // Słoweński
                'sq' => 'Shtesë', // Albański
                'sr' => 'Додатно', // Serbski
                'sv' => 'Ytterligare', // Szwedzki
                'tg' => 'Иловагӣ', // Tadżycki
                'th' => 'เพิ่มเติม', // Tajski
                'tk' => 'Goşmaça', // Turkmeński
                'tr' => 'Ek', // Turecki
                'uk' => 'Додаткове', // Ukraiński
                'uz' => 'Qo\'shimcha', // Uzbecki
                'vi' => 'Bổ sung', // Wietnamski
                'zh' => '额外的' // Chiński
            ]), 'name'=>json_encode([
                'am' => 'ባነር', // Amharski
                'ar' => 'لافتة', // Arabski
                'az' => 'Banner', // Azerski
                'be' => 'Банер', // Białoruski
                'bg' => 'Банер', // Bułgarski
                'bn' => 'ব্যানার', // Bengalski
                'bs' => 'Baner', // Bośniacki
                'ca' => 'Bàner', // Kataloński
                'cs' => 'Banner', // Czeski
                'da' => 'Banner', // Duński
                'de' => 'Banner', // Niemiecki
                'dv' => 'ބެނަރ', // Divehi
                'dz' => 'བན་ནར།', // Dzongkha
                'el' => 'Πανό', // Grecki
                'en' => 'Banner', // Angielski
                'es' => 'Banner', // Hiszpański
                'et' => 'Bänner', // Estoński
                'fa' => 'بنر', // Perski
                'fi' => 'Banneri', // Fiński
                'fr' => 'Bannière', // Francuski
                'he' => 'באנר', // Hebrajski
                'hi' => 'बैनर', // Hindi
                'hr' => 'Baner', // Chorwacki
                'hu' => 'Banner', // Węgierski
                'hy' => 'Բաներ', // Ormiański
                'id' => 'Banner', // Indonezyjski
                'is' => 'Borði', // Islandzki
                'it' => 'Banner', // Włoski
                'ja' => 'バナー', // Japoński
                'ka' => 'ბანერი', // Gruziński
                'km' => 'បដា', // Khmerski
                'ko' => '배너', // Koreański
                'lb' => 'Banner', // Luksemburski
                'lo' => 'ປ້າຍ', // Laotański
                'lt' => 'Baneris', // Litewski
                'lv' => 'Baneris', // Łotewski
                'me' => 'Baner', // Czarnogórski
                'mk' => 'Банер', // Macedoński
                'mn' => 'Баннер', // Mongołski
                'ms' => 'Banner', // Malajski
                'my' => 'ဘနာ', // Birmański
                'ne' => 'ब्यानर', // Nepalski
                'nl' => 'Banner', // Holenderski
                'no' => 'Banner', // Norweski
                'pl' => 'Baner', // Polski
                'ps' => 'بينر', // Paszto
                'pt' => 'Banner', // Portugalski
                'ro' => 'Banner', // Rumuński
                'ru' => 'Баннер', // Rosyjski
                'si' => 'බැනර්', // Syngaleski
                'sk' => 'Baner', // Słowacki
                'sl' => 'Pasica', // Słoweński
                'sq' => 'Baner', // Albański
                'sr' => 'Банер', // Serbski
                'sv' => 'Banner', // Szwedzki
                'tg' => 'Баннер', // Tadżycki
                'th' => 'แบนเนอร์', // Tajski
                'tk' => 'Banner', // Turkmeński
                'tr' => 'Afiş', // Turecki
                'uk' => 'Банер', // Ukraiński
                'uz' => 'Banner', // Uzbecki
                'vi' => 'Biểu ngữ', // Wietnamski
                'zh' => '横幅' // Chiński
            ]),'price'=>5000.00,'product_type'=>'Extra','created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
            ['id' => 9, 'points'=>0,'type'=>json_encode([
                'am' => 'ተጨማሪ', // Amharski
                'ar' => 'إضافي', // Arabski
                'az' => 'Əlavə', // Azerski
                'be' => 'Дадатковае', // Białoruski
                'bg' => 'Допълнително', // Bułgarski
                'bn' => 'অতিরিক্ত', // Bengalski
                'bs' => 'Dodatno', // Bośniacki
                'ca' => 'Addicional', // Kataloński
                'cs' => 'Dodatečné', // Czeski
                'da' => 'Yderligere', // Duński
                'de' => 'Zusätzlich', // Niemiecki
                'dv' => 'އިތުރަށް', // Divehi
                'dz' => 'མང་བདེན།', // Dzongkha
                'el' => 'Πρόσθετο', // Grecki
                'en' => 'Additional', // Angielski
                'es' => 'Adicional', // Hiszpański
                'et' => 'Täiendav', // Estoński
                'fa' => 'اضافی', // Perski
                'fi' => 'Lisä-', // Fiński
                'fr' => 'Supplémentaire', // Francuski
                'he' => 'נוסף', // Hebrajski
                'hi' => 'अतिरिक्त', // Hindi
                'hr' => 'Dodatno', // Chorwacki
                'hu' => 'További', // Węgierski
                'hy' => 'Լրացուցիչ', // Ormiański
                'id' => 'Tambahan', // Indonezyjski
                'is' => 'Viðbótar', // Islandzki
                'it' => 'Aggiuntivo', // Włoski
                'ja' => '追加の', // Japoński
                'ka' => 'დამატებითი', // Gruziński
                'km' => 'បន្ថែម', // Khmerski
                'ko' => '추가', // Koreański
                'lb' => 'Zousätzlech', // Luksemburski
                'lo' => 'ເພີ່ມເຕີມ', // Laotański
                'lt' => 'Papildomas', // Litewski
                'lv' => 'Papildu', // Łotewski
                'me' => 'Dodatno', // Czarnogórski
                'mk' => 'Дополнително', // Macedoński
                'mn' => 'Нэмэлт', // Mongołski
                'ms' => 'Tambahan', // Malajski
                'my' => 'ထပ်ဆောင်း', // Birmański
                'ne' => 'थप', // Nepalski
                'nl' => 'Extra', // Holenderski
                'no' => 'Ekstra', // Norweski
                'pl' => 'Dodatkowe', // Polski
                'ps' => 'اضافي', // Paszto
                'pt' => 'Adicional', // Portugalski
                'ro' => 'Suplimentar', // Rumuński
                'ru' => 'Дополнительное', // Rosyjski
                'si' => 'අමතර', // Syngaleski
                'sk' => 'Dodatočné', // Słowacki
                'sl' => 'Dodatno', // Słoweński
                'sq' => 'Shtesë', // Albański
                'sr' => 'Додатно', // Serbski
                'sv' => 'Ytterligare', // Szwedzki
                'tg' => 'Иловагӣ', // Tadżycki
                'th' => 'เพิ่มเติม', // Tajski
                'tk' => 'Goşmaça', // Turkmeński
                'tr' => 'Ek', // Turecki
                'uk' => 'Додаткове', // Ukraiński
                'uz' => 'Qo\'shimcha', // Uzbecki
                'vi' => 'Bổ sung', // Wietnamski
                'zh' => '额外的' // Chiński
            ]), 'name'=>json_encode([
                'am' => 'የተለየ የሥራ ኃላፊ', // Amharski
                'ar' => 'صاحب عمل مميز', // Arabski
                'az' => 'Fərqlənən işəgötürən', // Azerski
                'be' => 'Выдатны наймальнік', // Białoruski
                'bg' => 'Изтъкнат работодател', // Bułgarski
                'bn' => 'বৈশিষ্ট্যযুক্ত নিয়োগকর্তা', // Bengalski
                'bs' => 'Istaknuti poslodavac', // Bośniacki
                'ca' => 'Empleador destacat', // Kataloński
                'cs' => 'Významný zaměstnavatel', // Czeski
                'da' => 'Fremhævet arbejdsgiver', // Duński
                'de' => 'Hervorgehobener Arbeitgeber', // Niemiecki
                'dv' => 'މިއަދަދާ މައިބުންކޮށްފައިވާ ކަރަން', // Divehi
                'dz' => 'གསར་འཛུགས་འཚོ་སྤྱི།', // Dzongkha
                'el' => 'Εξέχων εργοδότης', // Grecki
                'en' => 'Featured Employer', // Angielski
                'es' => 'Empleador destacado', // Hiszpański
                'et' => 'Esiletõstetud tööandja', // Estoński
                'fa' => 'کارفرمای برجسته', // Perski
                'fi' => 'Erityisesti esitelty työnantaja', // Fiński
                'fr' => 'Employeur en vedette', // Francuski
                'he' => 'מעסיק מובלט', // Hebrajski
                'hi' => 'विशेष नियोक्ता', // Hindi
                'hr' => 'Istaknuti poslodavac', // Chorwacki
                'hu' => 'Kiemelt munkáltató', // Węgierski
                'hy' => 'Նշանակալի գործատու', // Ormiański
                'id' => 'Pemberi kerja unggulan', // Indonezyjski
                'is' => 'Áberandi vinnuveitandi', // Islandzki
                'it' => 'Datore di lavoro in evidenza', // Włoski
                'ja' => '注目の雇用主', // Japoński
                'ka' => 'გამორჩეული დამსაქმებელი', // Gruziński
                'km' => 'និយោជកដែលបានលេចធ្លោ', // Khmerski
                'ko' => '주목받는 고용주', // Koreański
                'lb' => 'Erausgestallte Patron', // Luksemburski
                'lo' => 'ຜູ້ຈ້າງງານທີ່ໄດ້ຮັບການເລືອກ', // Laotański
                'lt' => 'Pabrėžtas darbdavys', // Litewski
                'lv' => 'Izcelts darba devējs', // Łotewski
                'me' => 'Istaknuti poslodavac', // Czarnogórski
                'mk' => 'Издвоен работодавец', // Macedoński
                'mn' => 'Онцлох ажил олгогч', // Mongołski
                'ms' => 'Majikan unggul', // Malajski
                'my' => 'အထူးပြုအလုပ်ရှင်', // Birmański
                'ne' => 'विशेष रोजगारदाता', // Nepalski
                'nl' => 'Uitgelichte werkgever', // Holenderski
                'no' => 'Utvalgt arbeidsgiver', // Norweski
                'pl' => 'Wyróżniony pracodawca', // Polski
                'ps' => 'ځانګړی ګمارونکی', // Paszto
                'pt' => 'Empregador em destaque', // Portugalski
                'ro' => 'Angajator remarcat', // Rumuński
                'ru' => 'Выдающийся работодатель', // Rosyjski
                'si' => 'විශේෂිත රැකියා සපයන්නා', // Syngaleski
                'sk' => 'Významný zamestnávateľ', // Słowacki
                'sl' => 'Izpostavljen delodajalec', // Słoweński
                'sq' => 'Punëdhënësi i shquar', // Albański
                'sr' => 'Истакнути послодавац', // Serbski
                'sv' => 'Utvald arbetsgivare', // Szwedzki
                'tg' => 'Корфармои машҳур', // Tadżycki
                'th' => 'นายจ้างที่โดดเด่น', // Tajski
                'tk' => 'Tanalgyly Iş beriji', // Turkmeński
                'tr' => 'Öne Çıkan İşveren', // Turecki
                'uk' => 'Видатний роботодавець', // Ukraiński
                'uz' => 'Tanlangan ish beruvchi', // Uzbecki
                'vi' => 'Nhà tuyển dụng nổi bật', // Wietnamski
                'zh' => '特色雇主' // Chiński
            ]), 'price'=>8000.00,'product_type'=>'Extra','created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
            ['id' => 10, 'points'=>0,'type'=>json_encode([
                'am' => 'ተጨማሪ', // Amharski
                'ar' => 'إضافي', // Arabski
                'az' => 'Əlavə', // Azerski
                'be' => 'Дадатковае', // Białoruski
                'bg' => 'Допълнително', // Bułgarski
                'bn' => 'অতিরিক্ত', // Bengalski
                'bs' => 'Dodatno', // Bośniacki
                'ca' => 'Addicional', // Kataloński
                'cs' => 'Dodatečné', // Czeski
                'da' => 'Yderligere', // Duński
                'de' => 'Zusätzlich', // Niemiecki
                'dv' => 'އިތުރަށް', // Divehi
                'dz' => 'མང་བདེན།', // Dzongkha
                'el' => 'Πρόσθετο', // Grecki
                'en' => 'Additional', // Angielski
                'es' => 'Adicional', // Hiszpański
                'et' => 'Täiendav', // Estoński
                'fa' => 'اضافی', // Perski
                'fi' => 'Lisä-', // Fiński
                'fr' => 'Supplémentaire', // Francuski
                'he' => 'נוסף', // Hebrajski
                'hi' => 'अतिरिक्त', // Hindi
                'hr' => 'Dodatno', // Chorwacki
                'hu' => 'További', // Węgierski
                'hy' => 'Լրացուցիչ', // Ormiański
                'id' => 'Tambahan', // Indonezyjski
                'is' => 'Viðbótar', // Islandzki
                'it' => 'Aggiuntivo', // Włoski
                'ja' => '追加の', // Japoński
                'ka' => 'დამატებითი', // Gruziński
                'km' => 'បន្ថែម', // Khmerski
                'ko' => '추가', // Koreański
                'lb' => 'Zousätzlech', // Luksemburski
                'lo' => 'ເພີ່ມເຕີມ', // Laotański
                'lt' => 'Papildomas', // Litewski
                'lv' => 'Papildu', // Łotewski
                'me' => 'Dodatno', // Czarnogórski
                'mk' => 'Дополнително', // Macedoński
                'mn' => 'Нэмэлт', // Mongołski
                'ms' => 'Tambahan', // Malajski
                'my' => 'ထပ်ဆောင်း', // Birmański
                'ne' => 'थप', // Nepalski
                'nl' => 'Extra', // Holenderski
                'no' => 'Ekstra', // Norweski
                'pl' => 'Dodatkowe', // Polski
                'ps' => 'اضافي', // Paszto
                'pt' => 'Adicional', // Portugalski
                'ro' => 'Suplimentar', // Rumuński
                'ru' => 'Дополнительное', // Rosyjski
                'si' => 'අමතර', // Syngaleski
                'sk' => 'Dodatočné', // Słowacki
                'sl' => 'Dodatno', // Słoweński
                'sq' => 'Shtesë', // Albański
                'sr' => 'Додатно', // Serbski
                'sv' => 'Ytterligare', // Szwedzki
                'tg' => 'Иловагӣ', // Tadżycki
                'th' => 'เพิ่มเติม', // Tajski
                'tk' => 'Goşmaça', // Turkmeński
                'tr' => 'Ek', // Turecki
                'uk' => 'Додаткове', // Ukraiński
                'uz' => 'Qo\'shimcha', // Uzbecki
                'vi' => 'Bổ sung', // Wietnamski
                'zh' => '额外的' // Chiński
            ]), 'name'=>json_encode([
                'am' => 'ጽሑፍ', // Amharski
                'ar' => 'مقالة', // Arabski
                'az' => 'Məqalə', // Azerski
                'be' => 'Артыкул', // Białoruski
                'bg' => 'Статия', // Bułgarski
                'bn' => 'প্রবন্ধ', // Bengalski
                'bs' => 'Članak', // Bośniacki
                'ca' => 'Article', // Kataloński
                'cs' => 'Článek', // Czeski
                'da' => 'Artikel', // Duński
                'de' => 'Artikel', // Niemiecki
                'dv' => 'ތަކުންދެން', // Divehi
                'dz' => 'བསྡུར་བའི་བརྗོད་པ།', // Dzongkha
                'el' => 'Άρθρο', // Grecki
                'en' => 'Article', // Angielski
                'es' => 'Artículo', // Hiszpański
                'et' => 'Artikkel', // Estoński
                'fa' => 'مقاله', // Perski
                'fi' => 'Artikkeli', // Fiński
                'fr' => 'Article', // Francuski
                'he' => 'מאמר', // Hebrajski
                'hi' => 'लेख', // Hindi
                'hr' => 'Članak', // Chorwacki
                'hu' => 'Cikk', // Węgierski
                'hy' => 'Հոդված', // Ormiański
                'id' => 'Artikel', // Indonezyjski
                'is' => 'Grein', // Islandzki
                'it' => 'Articolo', // Włoski
                'ja' => '記事', // Japoński
                'ka' => 'სტატია', // Gruziński
                'km' => 'អត្ថបទ', // Khmerski
                'ko' => '기사', // Koreański
                'lb' => 'Artikel', // Luksemburski
                'lo' => 'ບົດຄວາມ', // Laotański
                'lt' => 'Straipsnis', // Litewski
                'lv' => 'Raksts', // Łotewski
                'me' => 'Članak', // Czarnogórski
                'mk' => 'Член', // Macedoński
                'mn' => 'Нийтлэл', // Mongołski
                'ms' => 'Artikel', // Malajski
                'my' => 'ဆောင်းပါး', // Birmański
                'ne' => 'लेख', // Nepalski
                'nl' => 'Artikel', // Holenderski
                'no' => 'Artikkel', // Norweski
                'pl' => 'Artykuł', // Polski
                'ps' => 'مقاله', // Paszto
                'pt' => 'Artigo', // Portugalski
                'ro' => 'Articol', // Rumuński
                'ru' => 'Статья', // Rosyjski
                'si' => 'ලිපිය', // Syngaleski
                'sk' => 'Článok', // Słowacki
                'sl' => 'Članek', // Słoweński
                'sq' => 'Artikull', // Albański
                'sr' => 'Чланак', // Serbski
                'sv' => 'Artikel', // Szwedzki
                'tg' => 'Мақола', // Tadżycki
                'th' => 'บทความ', // Tajski
                'tk' => 'Makala', // Turkmeński
                'tr' => 'Makale', // Turecki
                'uk' => 'Стаття', // Ukraiński
                'uz' => 'Maqola', // Uzbecki
                'vi' => 'Bài báo', // Wietnamski
                'zh' => '文章' // Chiński
            ]), 'price'=>6000.00,'product_type'=>'Extra','created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
            ['id' => 11, 'points'=>0,'type'=>json_encode([
                'am' => 'ተጨማሪ', // Amharski
                'ar' => 'إضافي', // Arabski
                'az' => 'Əlavə', // Azerski
                'be' => 'Дадатковае', // Białoruski
                'bg' => 'Допълнително', // Bułgarski
                'bn' => 'অতিরিক্ত', // Bengalski
                'bs' => 'Dodatno', // Bośniacki
                'ca' => 'Addicional', // Kataloński
                'cs' => 'Dodatečné', // Czeski
                'da' => 'Yderligere', // Duński
                'de' => 'Zusätzlich', // Niemiecki
                'dv' => 'އިތުރަށް', // Divehi
                'dz' => 'མང་བདེན།', // Dzongkha
                'el' => 'Πρόσθετο', // Grecki
                'en' => 'Additional', // Angielski
                'es' => 'Adicional', // Hiszpański
                'et' => 'Täiendav', // Estoński
                'fa' => 'اضافی', // Perski
                'fi' => 'Lisä-', // Fiński
                'fr' => 'Supplémentaire', // Francuski
                'he' => 'נוסף', // Hebrajski
                'hi' => 'अतिरिक्त', // Hindi
                'hr' => 'Dodatno', // Chorwacki
                'hu' => 'További', // Węgierski
                'hy' => 'Լրացուցիչ', // Ormiański
                'id' => 'Tambahan', // Indonezyjski
                'is' => 'Viðbótar', // Islandzki
                'it' => 'Aggiuntivo', // Włoski
                'ja' => '追加の', // Japoński
                'ka' => 'დამატებითი', // Gruziński
                'km' => 'បន្ថែម', // Khmerski
                'ko' => '추가', // Koreański
                'lb' => 'Zousätzlech', // Luksemburski
                'lo' => 'ເພີ່ມເຕີມ', // Laotański
                'lt' => 'Papildomas', // Litewski
                'lv' => 'Papildu', // Łotewski
                'me' => 'Dodatno', // Czarnogórski
                'mk' => 'Дополнително', // Macedoński
                'mn' => 'Нэмэлт', // Mongołski
                'ms' => 'Tambahan', // Malajski
                'my' => 'ထပ်ဆောင်း', // Birmański
                'ne' => 'थप', // Nepalski
                'nl' => 'Extra', // Holenderski
                'no' => 'Ekstra', // Norweski
                'pl' => 'Dodatkowe', // Polski
                'ps' => 'اضافي', // Paszto
                'pt' => 'Adicional', // Portugalski
                'ro' => 'Suplimentar', // Rumuński
                'ru' => 'Дополнительное', // Rosyjski
                'si' => 'අමතර', // Syngaleski
                'sk' => 'Dodatočné', // Słowacki
                'sl' => 'Dodatno', // Słoweński
                'sq' => 'Shtesë', // Albański
                'sr' => 'Додатно', // Serbski
                'sv' => 'Ytterligare', // Szwedzki
                'tg' => 'Иловагӣ', // Tadżycki
                'th' => 'เพิ่มเติม', // Tajski
                'tk' => 'Goşmaça', // Turkmeński
                'tr' => 'Ek', // Turecki
                'uk' => 'Додаткове', // Ukraiński
                'uz' => 'Qo\'shimcha', // Uzbecki
                'vi' => 'Bổ sung', // Wietnamski
                'zh' => '额外的' // Chiński
            ]),'name'=>json_encode([
                'am' => 'ማስታወቂያ ማህበራዊ ትራፊክ', // Amharski
                'ar' => 'الترويج الاجتماعي', // Arabski
                'az' => 'Sosial təbliğat', // Azerski
                'be' => 'Прасоўванне ў сацсетках', // Białoruski
                'bg' => 'Социално промотиране', // Bułgarski
                'bn' => 'সামাজিক প্রচার', // Bengalski
                'bs' => 'Promocija na društvenim mrežama', // Bośniacki
                'ca' => 'Promoció social', // Kataloński
                'cs' => 'Sociální propagace', // Czeski
                'da' => 'Social promovering', // Duński
                'de' => 'Soziale Werbung', // Niemiecki
                'dv' => 'ސޯސަލް ޕުރޮމޯޝަން', // Divehi
                'dz' => 'སྤེལ་མང་མང་དུ་གསར་སྤྲོད།', // Dzongkha
                'el' => 'Κοινωνική προώθηση', // Grecki
                'en' => 'Social promotion', // Angielski
                'es' => 'Promoción social', // Hiszpański
                'et' => 'Sotsiaalne reklaamimine', // Estoński
                'fa' => 'ترویج اجتماعی', // Perski
                'fi' => 'Sosiaalinen edistäminen', // Fiński
                'fr' => 'Promotion sociale', // Francuski
                'he' => 'קידום חברתי', // Hebrajski
                'hi' => 'सामाजिक प्रचार', // Hindi
                'hr' => 'Društveno promoviranje', // Chorwacki
                'hu' => 'Társadalmi promóció', // Węgierski
                'hy' => 'Սոցիալական առաջխաղացում', // Ormiański
                'id' => 'Promosi sosial', // Indonezyjski
                'is' => 'Félagsleg kynning', // Islandzki
                'it' => 'Promozione sociale', // Włoski
                'ja' => 'ソーシャルプロモーション', // Japoński
                'ka' => 'სოციალური პოპულარიზაცია', // Gruziński
                'km' => 'ការផ្សព្វផ្សាយសង្គម', // Khmerski
                'ko' => '사회적 홍보', // Koreański
                'lb' => 'Sozial Promotioun', // Luksemburski
                'lo' => 'ການໂຄສະນາສັງຄົມ', // Laotański
                'lt' => 'Socialinė reklama', // Litewski
                'lv' => 'Sociālā veicināšana', // Łotewski
                'me' => 'Promovisanje na društvenim mrežama', // Czarnogórski
                'mk' => 'Социјално промовирање', // Macedoński
                'mn' => 'Нийгмийн сурталчилгаа', // Mongołski
                'ms' => 'Promosi sosial', // Malajski
                'my' => 'လူမှုကွန်ယက်ကြော်ငြာ', // Birmański
                'ne' => 'सामाजिक प्रवर्द्धन', // Nepalski
                'nl' => 'Sociale promotie', // Holenderski
                'no' => 'Sosial promotering', // Norweski
                'pl' => 'Promowanie social', // Polski
                'ps' => 'ټولنیز تبلیغات', // Paszto
                'pt' => 'Promoção social', // Portugalski
                'ro' => 'Promovare socială', // Rumuński
                'ru' => 'Социальное продвижение', // Rosyjski
                'si' => 'සමාජ ප්‍රවර්ධනය', // Syngaleski
                'sk' => 'Sociálne propagovanie', // Słowacki
                'sl' => 'Promocija na družbenih omrežjih', // Słoweński
                'sq' => 'Promovim social', // Albański
                'sr' => 'Социјално промовисање', // Serbski
                'sv' => 'Social marknadsföring', // Szwedzki
                'tg' => 'Тарғиби иҷтимоӣ', // Tadżycki
                'th' => 'การส่งเสริมทางสังคม', // Tajski
                'tk' => 'Durmuş mahabaty', // Turkmeński
                'tr' => 'Sosyal tanıtım', // Turecki
                'uk' => 'Соціальне просування', // Ukraiński
                'uz' => 'Ijtimoiy targ‘ibot', // Uzbecki
                'vi' => 'Quảng bá xã hội', // Wietnamski
                'zh' => '社交推广' // Chiński
            ]), 'price'=>10000.00,'product_type'=>'Extra','created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
            ['id' => 12, 'points'=>0,'type'=>json_encode([
                'am' => 'ተጨማሪ', // Amharski
                'ar' => 'إضافي', // Arabski
                'az' => 'Əlavə', // Azerski
                'be' => 'Дадатковае', // Białoruski
                'bg' => 'Допълнително', // Bułgarski
                'bn' => 'অতিরিক্ত', // Bengalski
                'bs' => 'Dodatno', // Bośniacki
                'ca' => 'Addicional', // Kataloński
                'cs' => 'Dodatečné', // Czeski
                'da' => 'Yderligere', // Duński
                'de' => 'Zusätzlich', // Niemiecki
                'dv' => 'އިތުރަށް', // Divehi
                'dz' => 'མང་བདེན།', // Dzongkha
                'el' => 'Πρόσθετο', // Grecki
                'en' => 'Additional', // Angielski
                'es' => 'Adicional', // Hiszpański
                'et' => 'Täiendav', // Estoński
                'fa' => 'اضافی', // Perski
                'fi' => 'Lisä-', // Fiński
                'fr' => 'Supplémentaire', // Francuski
                'he' => 'נוסף', // Hebrajski
                'hi' => 'अतिरिक्त', // Hindi
                'hr' => 'Dodatno', // Chorwacki
                'hu' => 'További', // Węgierski
                'hy' => 'Լրացուցիչ', // Ormiański
                'id' => 'Tambahan', // Indonezyjski
                'is' => 'Viðbótar', // Islandzki
                'it' => 'Aggiuntivo', // Włoski
                'ja' => '追加の', // Japoński
                'ka' => 'დამატებითი', // Gruziński
                'km' => 'បន្ថែម', // Khmerski
                'ko' => '추가', // Koreański
                'lb' => 'Zousätzlech', // Luksemburski
                'lo' => 'ເພີ່ມເຕີມ', // Laotański
                'lt' => 'Papildomas', // Litewski
                'lv' => 'Papildu', // Łotewski
                'me' => 'Dodatno', // Czarnogórski
                'mk' => 'Дополнително', // Macedoński
                'mn' => 'Нэмэлт', // Mongołski
                'ms' => 'Tambahan', // Malajski
                'my' => 'ထပ်ဆောင်း', // Birmański
                'ne' => 'थप', // Nepalski
                'nl' => 'Extra', // Holenderski
                'no' => 'Ekstra', // Norweski
                'pl' => 'Dodatkowe', // Polski
                'ps' => 'اضافي', // Paszto
                'pt' => 'Adicional', // Portugalski
                'ro' => 'Suplimentar', // Rumuński
                'ru' => 'Дополнительное', // Rosyjski
                'si' => 'අමතර', // Syngaleski
                'sk' => 'Dodatočné', // Słowacki
                'sl' => 'Dodatno', // Słoweński
                'sq' => 'Shtesë', // Albański
                'sr' => 'Додатно', // Serbski
                'sv' => 'Ytterligare', // Szwedzki
                'tg' => 'Иловагӣ', // Tadżycki
                'th' => 'เพิ่มเติม', // Tajski
                'tk' => 'Goşmaça', // Turkmeński
                'tr' => 'Ek', // Turecki
                'uk' => 'Додаткове', // Ukraiński
                'uz' => 'Qo\'shimcha', // Uzbecki
                'vi' => 'Bổ sung', // Wietnamski
                'zh' => '额外的' // Chiński
            ]),'name'=>json_encode([
                'am' => 'የማረጋገጫ50/50', // Amharski
                'ar' => 'شهادة50/50', // Arabski
                'az' => 'Sertifikat50/50', // Azerski
                'be' => 'Сертыфікат50/50', // Białoruski
                'bg' => 'Сертификат50/50', // Bułgarski
                'bn' => 'সার্টিফিকেট50/50', // Bengalski
                'bs' => 'Certifikat50/50', // Bośniacki
                'ca' => 'Certificat50/50', // Kataloński
                'cs' => 'Certifikát50/50', // Czeski
                'da' => 'Certifikat50/50', // Duński
                'de' => 'Zertifikat50/50', // Niemiecki
                'dv' => 'ސަރޓިފިކޭޓް50/50', // Divehi
                'dz' => 'སེར་ཏི་ཕི་ཀཊ་50/50', // Dzongkha
                'el' => 'Πιστοποιητικό50/50', // Grecki
                'en' => 'Certificate50/50', // Angielski
                'es' => 'Certificado50/50', // Hiszpański
                'et' => 'Sertifikaat50/50', // Estoński
                'fa' => 'گواهی50/50', // Perski
                'fi' => 'Sertifikaatti50/50', // Fiński
                'fr' => 'Certificat50/50', // Francuski
                'he' => 'תעודה50/50', // Hebrajski
                'hi' => 'प्रमाणपत्र50/50', // Hindi
                'hr' => 'Certifikat50/50', // Chorwacki
                'hu' => 'Tanúsítvány50/50', // Węgierski
                'hy' => 'Սերտիֆիկատ50/50', // Ormiański
                'id' => 'Sertifikat50/50', // Indonezyjski
                'is' => 'Vottorð50/50', // Islandzki
                'it' => 'Certificato50/50', // Włoski
                'ja' => '証明書50/50', // Japoński
                'ka' => 'სერტიფიკატი50/50', // Gruziński
                'km' => 'វិញ្ញាបនបត្រ50/50', // Khmerski
                'ko' => '인증서50/50', // Koreański
                'lb' => 'Zertifikat50/50', // Luksemburski
                'lo' => 'ປະກອນສອບທຽບ50/50', // Laotański
                'lt' => 'Sertifikatas50/50', // Litewski
                'lv' => 'Sertifikāts50/50', // Łotewski
                'me' => 'Certifikat50/50', // Czarnogórski
                'mk' => 'Сертификат50/50', // Macedoński
                'mn' => 'Сертификат50/50', // Mongołski
                'ms' => 'Sijil50/50', // Malajski
                'my' => 'လက်မှတ်50/50', // Birmański
                'ne' => 'प्रमाणपत्र50/50', // Nepalski
                'nl' => 'Certificaat50/50', // Holenderski
                'no' => 'Sertifikat50/50', // Norweski
                'pl' => 'Certyfikat50/50', // Polski
                'ps' => 'سند50/50', // Paszto
                'pt' => 'Certificado50/50', // Portugalski
                'ro' => 'Certificat50/50', // Rumuński
                'ru' => 'Сертификат50/50', // Rosyjski
                'si' => 'සහතිකය50/50', // Syngaleski
                'sk' => 'Certifikát50/50', // Słowacki
                'sl' => 'Certifikat50/50', // Słoweński
                'sq' => 'Certifikatë50/50', // Albański
                'sr' => 'Сертификат50/50', // Serbski
                'sv' => 'Certifikat50/50', // Szwedzki
                'tg' => 'Сертификат50/50', // Tadżycki
                'th' => 'ใบรับรอง50/50', // Tajski
                'tk' => 'Şahadatnama50/50', // Turkmeński
                'tr' => 'Sertifika50/50', // Turecki
                'uk' => 'Сертифікат50/50', // Ukraiński
                'uz' => 'Sertifikat50/50', // Uzbecki
                'vi' => 'Chứng chỉ50/50', // Wietnamski
                'zh' => '证书50/50' // Chiński
            ]), 'price'=>2000.00,'product_type'=>'Extra','created_at' => date('Y-m-d H:i:s'), 'updated_at' =>date('Y-m-d H:i:s')],
        ];

        DB::table('products')->insert($products);

        Schema::enableForeignKeyConstraints();


    }
}
