<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Role::truncate();
        Permission::truncate();
        Role::create(['name' => 'firm']);
        $recruit = Role::create(['name' => 'recruit']);
        Role::create(['name' => 'worker']);
        Role::create(['name' => 'admin']);

        $p1 = Permission::create([
            'name' => 'adding projects', 'trans' => json_encode([
                'am' => 'ፕሮጀክቶችን መጨመር',
                'ar' => 'إضافة المشاريع',
                'az' => 'Layihələrin əlavə edilməsi',
                'be' => 'Даданне праектаў',
                'bg' => 'Добавяне на проекти',
                'bn' => 'প্রকল্প যোগ করা',
                'bs' => 'Dodavanje projekata',
                'ca' => 'Afegint projectes',
                'cs' => 'Přidávání projektů',
                'da' => 'Tilføjelse af projekter',
                'de' => 'Projekte hinzufügen',
                'dv' => 'ޕްރޮޖެކްޓުތަކަށް އިތުރަށް',
                'dz' => 'གཞི་རྟེན་སྒྲིག་པ་ཁ་སྐོང་',
                'el' => 'Προσθήκη έργων',
                'en' => 'Adding projects',
                'es' => 'Añadir proyectos',
                'et' => 'Projektide lisamine',
                'fa' => 'افزودن پروژه‌ها',
                'fi' => 'Projektien lisääminen',
                'fr' => 'Ajout de projets',
                'he' => 'הוספת פרויקטים',
                'hi' => 'परियोजनाएँ जोड़ना',
                'hr' => 'Dodavanje projekata',
                'hu' => 'Projektek hozzáadása',
                'hy' => 'Նախագծեր ավելացնել',
                'id' => 'Menambahkan proyek',
                'is' => 'Bæta við verkefnum',
                'it' => 'Aggiunta di progetti',
                'ja' => 'プロジェクトの追加',
                'ka' => 'პროექტების დამატება',
                'km' => 'ការបន្ថែមគម្រោង',
                'ko' => '프로젝트 추가',
                'lb' => 'Projeten derbäi setzen',
                'lo' => 'ເພີ່ມໂຄງການ',
                'lt' => 'Projektų pridėjimas',
                'lv' => 'Projektu pievienošana',
                'me' => 'Dodavanje projekata',
                'mk' => 'Додавање на проекти',
                'mn' => 'Төсөл нэмэх',
                'ms' => 'Menambah projek',
                'my' => 'စီမံကိန်းများထည့်သွင်းခြင်း',
                'ne' => 'परियोजना थप्दै',
                'nl' => 'Projecten toevoegen',
                'no' => 'Legge til prosjekter',
                'pl' => 'Dodawanie projektów',
                'ps' => 'پروژې اضافه کول',
                'pt' => 'Adição de projetos',
                'ro' => 'Adăugarea de proiecte',
                'ru' => 'Добавление проектов',
                'si' => 'ව්‍යාපෘති එකතු කිරීම',
                'sk' => 'Pridávanie projektov',
                'sl' => 'Dodajanje projektov',
                'sq' => 'Shtimi i projekteve',
                'sr' => 'Додавање пројеката',
                'sv' => 'Lägga till projekt',
                'tg' => 'Илова кардани лоиҳаҳо',
                'th' => 'การเพิ่มโครงการ',
                'tk' => 'Taslamalary goşmak',
                'tr' => 'Projeleri ekleme',
                'uk' => 'Додавання проєктів',
                'uz' => 'Loyihalarni qo‘shish',
                'vi' => 'Thêm dự án',
                'zh' => '添加项目'
            ])]);
        $p2 = Permission::create([
            'name' => 'editing projects', 'trans' => json_encode([
                'am' => 'እትም አቅርቦት', // Amharski
                'ar' => 'تحرير المشاريع', // Arabski
                'az' => 'Layihələri redaktə etmək', // Azerski
                'be' => 'Рэдагаванне праектаў', // Białoruski
                'bg' => 'Редактиране на проекти', // Bułgarski
                'bn' => 'প্রকল্প সম্পাদনা', // Bengalski
                'bs' => 'Uređivanje projekata', // Bośniacki
                'ca' => 'Editar projectes', // Kataloński
                'cs' => 'Úprava projektů', // Czeski
                'da' => 'Redigering af projekter', // Duński
                'de' => 'Projekte bearbeiten', // Niemiecki
                'dv' => 'ޕްރޮޖެކްޓުތަކަށް އެދިރާން', // Divehi
                'dz' => 'གཞི་རྟེན་འདྲ་བའི་བསྟན་ནི།', // Dzongkha
                'el' => 'Επεξεργασία έργων', // Grecki
                'en' => 'Editing projects', // Angielski
                'es' => 'Editar proyectos', // Hiszpański
                'et' => 'Projektide redigeerimine', // Estoński
                'fa' => 'ویرایش پروژه‌ها', // Perski
                'fi' => 'Projektien muokkaaminen', // Fiński
                'fr' => 'Édition de projets', // Francuski
                'he' => 'עריכת פרויקטים', // Hebrajski
                'hi' => 'परियोजनाओं को संपादित करें', // Hindi
                'hr' => 'Uređivanje projekata', // Chorwacki
                'hu' => 'Projektek szerkesztése', // Węgierski
                'hy' => 'Նախագծեր խմբագրել', // Ormiański
                'id' => 'Menyunting proyek', // Indonezyjski
                'is' => 'Breyta verkefni', // Islandzki
                'it' => 'Modifica progetti', // Włoski
                'ja' => 'プロジェクトの編集', // Japoński
                'ka' => 'პროექტების რედაქტირება', // Gruziński
                'km' => 'កែសម្រួលគម្រោង', // Khmerski
                'ko' => '프로젝트 편집', // Koreański
                'lb' => 'Projekten änneren', // Luksemburski
                'lo' => 'ແກ້ໄຂຂໍ້ສະເຫນີ', // Laotański
                'lt' => 'Projektų redagavimas', // Litewski
                'lv' => 'Projektu rediģēšana', // Łotewski
                'me' => 'Uređivanje projekata', // Czarnogórski
                'mk' => 'Уредување на проекти', // Macedoński
                'mn' => 'Төсөл засварлах', // Mongołski
                'ms' => 'Menyunting projek', // Malajski
                'my' => 'စီမံကိန်းများကိုပြင်ဆင်ပါ', // Birmański
                'ne' => 'परियोजना सम्पादन गर्नुहोस्', // Nepalski
                'nl' => 'Projecten bewerken', // Holenderski
                'no' => 'Redigere prosjekter', // Norweski
                'pl' => 'Edycja projektów', // Polski
                'ps' => 'پروژې سمول', // Paszto
                'pt' => 'Editar projetos', // Portugalski
                'ro' => 'Editarea proiectelor', // Rumuński
                'ru' => 'Редактирование проектов', // Rosyjski
                'si' => 'ව්‍යාපෘති සංස්කරණය', // Syngaleski
                'sk' => 'Úprava projektov', // Słowacki
                'sl' => 'Urejanje projektov', // Słoweński
                'sq' => 'Redaktimi i projekteve', // Albański
                'sr' => 'Уређивање пројеката', // Serbski
                'sv' => 'Redigera projekt', // Szwedzki
                'tg' => 'Лоиҳаҳоро таҳрир кардан', // Tadżycki
                'th' => 'แก้ไขโครงการ', // Tajski
                'tk' => 'Taslamalary redaktirlemek', // Turkmeński
                'tr' => 'Projeleri düzenleme', // Turecki
                'uk' => 'Редагування проектів', // Ukraiński
                'uz' => 'Loyihalarni tahrirlash', // Uzbecki
                'vi' => 'Chỉnh sửa dự án', // Wietnamski
                'zh' => '编辑项目' // Chiński
            ])]);
        $p3 = Permission::create([
            'name' => 'access to received CVs',
            'trans' => json_encode([
                'am' => 'እትም ወኪል', // Amharski
                'ar' => 'الوصول إلى السير الذاتية المستلمة', // Arabski
                'az' => 'Alınan CV-lərə giriş', // Azerski
                'be' => 'Доступ да атрыманых CV', // Białoruski
                'bg' => 'Достъп до получените автобиографии', // Bułgarski
                'bn' => 'প্রাপ্ত সিভি প্রবেশাধিকার', // Bengalski
                'bs' => 'Pristup primljenim CV-ovima', // Bośniacki
                'ca' => 'Accés als CV rebuts', // Kataloński
                'cs' => 'Přístup k přijatým životopisům', // Czeski
                'da' => 'Adgang til modtagne CVer', // Duński
                'de' => 'Zugriff auf empfangene Lebensläufe', // Niemiecki
                'dv' => 'އިންސަލާ ދައްކަން ގެ ހަމަޖެންތް', // Divehi
                'dz' => 'གནས་ཚུ་བསྟན་ནི།', // Dzongkha
                'el' => 'Πρόσβαση σε παραληφθέντα βιογραφικά σημειώματα', // Grecki
                'en' => 'Access to received CVs', // Angielski
                'es' => 'Acceso a los CV recibidos', // Hiszpański
                'et' => 'Ligipääs saadud CV-dele', // Estoński
                'fa' => 'دسترسی به رزومه‌های دریافتی', // Perski
                'fi' => 'Pääsy vastaanotettuihin CV:ihin', // Fiński
                'fr' => 'Accès aux CV reçus', // Francuski
                'he' => 'גישה לקורות חיים שהתקבלו', // Hebrajski
                'hi' => 'प्राप्त सीवी तक पहुँच', // Hindi
                'hr' => 'Pristup primljenim životopisima', // Chorwacki
                'hu' => 'Hozzáférés a kapott önéletrajzokhoz', // Węgierski
                'hy' => 'Ստացված CV-ների մուտք', // Ormiański
                'id' => 'Akses ke CV yang diterima', // Indonezyjski
                'is' => 'Aðgangur að mótteknu CV', // Islandzki
                'it' => 'Accesso ai CV ricevuti', // Włoski
                'ja' => '受け取った履歴書へのアクセス', // Japoński
                'ka' => 'მიღებული CV-ების ხელმისაწვდომობა', // Gruziński
                'km' => 'ចូលប្រើ CV ទទួលបាន', // Khmerski
                'ko' => '수신된 이력서에 대한 접근', // Koreański
                'lb' => 'Zougrouf opgeschonnene CVs', // Luksemburski
                'lo' => 'ການຂໍ້ມູນ CV ທີ່ຮັບມາ', // Laotański
                'lt' => 'Prieiga prie gautų CV', // Litewski
                'lv' => 'Piekļuve saņemtajiem CV', // Łotewski
                'me' => 'Pristup primljenim CV-ovima', // Czarnogórski
                'mk' => 'Пристап до примени CV', // Macedoński
                'mn' => 'Хүлээн авсан CV-тай нэвтрэх', // Mongołski
                'ms' => 'Akses kepada CV yang diterima', // Malajski
                'my' => 'လက်ခံထားသော CVs သို့ဝင်ရောက်ရန်', // Birmański
                'ne' => 'प्राप्त सीभीहरूमा पहुँच', // Nepalski
                'nl' => 'Toegang tot ontvangen CV\'s', // Holenderski
                'no' => 'Tilgang til mottatte CV-er', // Norweski
                'pl' => 'Dostęp do otrzymanych CV', // Polski
                'ps' => 'د ترلاسه شوي CVs ته لاسرسی', // Paszto
                'pt' => 'Acesso aos CVs recebidos', // Portugalski
                'ro' => 'Acces la CV-urile primite', // Rumuński
                'ru' => 'Доступ к полученным резюме', // Rosyjski
                'si' => 'ලැබුණු CVs වෙත ප්‍රවේශය', // Syngaleski
                'sk' => 'Prístup k prijatým životopisom', // Słowacki
                'sl' => 'Dostop do prejetih življenjepisov', // Słoweński
                'sq' => 'Aksesi në CV-të e pranuara', // Albański
                'sr' => 'Pristup primljenim CV-ovima', // Serbski
                'sv' => 'Åtkomst till mottagna CV:n', // Szwedzki
                'tg' => 'Доступ ба CV-и қабулшуда', // Tadżycki
                'th' => 'การเข้าถึง CV ที่ได้รับ', // Tajski
                'tk' => 'Alnan CV-lere giriş', // Turkmeński
                'tr' => 'Alınan CV\'lere erişim', // Turecki
                'uk' => 'Доступ до отриманих резюме', // Ukraiński
                'uz' => 'Qabul qilingan CV-larga kirish', // Uzbecki
                'vi' => 'Truy cập vào CV đã nhận', // Wietnamski
                'zh' => '访问收到的简历' // Chiński
            ])
        ]);
//        $p4 = Permission::create([
//            'name' => 'access to job posts from other recruiters',
//            'trans' => json_encode([
//                'am' => 'ከሌሎች ተመራቂዎች የስራ ቦታ ማስታወቂያዎች አቅርቦት', // Amharski
//                'ar' => 'الوصول إلى منشورات الوظائف من المجندين الآخرين', // Arabski
//                'az' => 'Digər işəgötürənlərdən iş elanlarına çıxış', // Azerski
//                'be' => 'Доступ да аб\'яўленняў аб працоўных месцах ад іншых наймальнікаў', // Białoruski
//                'bg' => 'Достъп до обяви за работа от други наематели', // Bułgarski
//                'bn' => 'অন্য রিক্রুটারদের কাছ থেকে চাকরি পোস্টে অ্যাক্সেস', // Bengalski
//                'bs' => 'Pristup objavama poslova od drugih regrutera', // Bośniacki
//                'ca' => 'Accés a les ofertes de feina d’altres reclutadors', // Kataloński
//                'cs' => 'Přístup k pracovním nabídkám od jiných náborářů', // Czeski
//                'da' => 'Adgang til jobopslag fra andre rekruttere', // Duński
//                'de' => 'Zugriff auf Stellenanzeigen von anderen Rekrutierern', // Niemiecki
//                'dv' => 'އިންސަލާ ދައްކަން ގެ የስራ ቦታ መልታዎች', // Divehi
//                'dz' => 'གནས་ཚུ་བསྟན་ནི།', // Dzongkha
//                'el' => 'Πρόσβαση σε αγγελίες εργασίας από άλλους εργοδότες', // Grecki
//                'en' => 'Access to job posts from other recruiters', // Angielski
//                'es' => 'Acceso a ofertas de trabajo de otros reclutadores', // Hiszpański
//                'et' => 'Ligipääs teiste värbajate töökuulutustele', // Estoński
//                'fa' => 'دسترسی به پست‌های شغلی از سایر استخدام‌کنندگان', // Perski
//                'fi' => 'Pääsy muiden rekrytoijien työpaikkailmoituksiin', // Fiński
//                'fr' => 'Accès aux offres d’emploi d’autres recruteurs', // Francuski
//                'he' => 'גישה לפוסטים של עבודות מראיינים אחרים', // Hebrajski
//                'hi' => 'अन्य भर्तीकर्ताओं से नौकरी पोस्ट्स तक पहुँच', // Hindi
//                'hr' => 'Pristup oglasima za posao od drugih regrutera', // Chorwacki
//                'hu' => 'Hozzáférés más toborzóktól származó álláshirdetésekhez', // Węgierski
//                'hy' => 'Մուտք դեպի մյուս գռիլեներներից ստացված աշխատանքի հայտարարությունները', // Ormiański
//                'id' => 'Akses ke pos lowongan pekerjaan dari perekrut lain', // Indonezyjski
//                'is' => 'Aðgangur að atvinnufrestum frá öðrum ráðningaraðilum', // Islandzki
//                'it' => 'Accesso agli annunci di lavoro da altri reclutatori', // Włoski
//                'ja' => '他の採用者からの求人情報へのアクセス', // Japoński
//                'ka' => 'მიღებული სამუშაო ადგილები სხვა რეკრუტერებისგან', // Gruziński
//                'km' => 'ចូលប្រើការផ្តល់ជូនការងារពីអ្នកជ្រើសរើសផ្សេងទៀត', // Khmerski
//                'ko' => '다른 채용 담당자의 직업 게시물에 액세스', // Koreański
//                'lb' => 'Zougrouf opgeschonnene Beschäftegungsoptiounen', // Luksemburski
//                'lo' => 'ການຂໍ້ມູນງານຈາກຕົວອື່ນ', // Laotański
//                'lt' => 'Prieiga prie kitų samdytojų darbo skelbimų', // Litewski
//                'lv' => 'Piekļuve darba sludinājumiem no citiem darba devējiem', // Łotewski
//                'me' => 'Pristup oglasima za posao od drugih regrutera', // Czarnogórski
//                'mk' => 'Пристап до работни огласи од други наемачи', // Macedoński
//                'mn' => 'Бусад ажилд авах хүмүүстэй холбогдсон ажлын байрны зар', // Mongołski
//                'ms' => 'Akses kepada jawatan pekerjaan dari perekrut lain', // Malajski
//                'my' => 'အခြားခေါင်းစဉ်များမှ အလုပ်စာပေများသို့ ဝင်ရောက်ခြင်း', // Birmański
//                'ne' => 'अन्य भर्तीकर्ताहरूबाट काम पोस्टहरूमा पहुँच', // Nepalski
//                'nl' => 'Toegang tot vacatures van andere recruiters', // Holenderski
//                'no' => 'Tilgang til jobbinnlegg fra andre rekrutterere', // Norweski
//                'pl' => 'Dostęp do ofert pracy od innych rekruterów', // Polski
//                'ps' => 'د نورو استخدام کونکو څخه د کار پوستونو ته لاسرسی', // Paszto
//                'pt' => 'Acesso a anúncios de emprego de outros recrutadores', // Portugalski
//                'ro' => 'Acces la postările de muncă ale altor recrutoare', // Rumuński
//                'ru' => 'Доступ к вакансиям от других рекрутеров', // Rosyjski
//                'si' => 'අනිත් බඳවා ගැනීම්වලින් රැකියා දැන්වීම් බලන්න', // Syngaleski
//                'sk' => 'Prístup k pracovným inzerátom od iných náborárov', // Słowacki
//                'sl' => 'Dostop do delovnih mest drugih rekruterjev', // Słoweński
//                'sq' => 'Aksesi në postimet e punës nga rekruterët e tjerë', // Albański
//                'sr' => 'Pristup radnim oglasima od drugih regrutera', // Serbski
//                'sv' => 'Åtkomst till jobbannonser från andra rekryterare', // Szwedzki
//                'tg' => 'Доступ ба корҳои рекрутерҳои дигар', // Tadżycki
//                'th' => 'การเข้าถึงโพสต์งานจากผู้สรรหาคนอื่น', // Tajski
//                'tk' => 'Başka işçi qəbul edənlərdən iş elanlarına giriş', // Turkmeński
//                'tr' => 'Diğer işe alım uzmanlarından iş ilanlarına erişim', // Turecki
//                'uk' => 'Доступ до вакансій від інших рекрутерів', // Ukraiński
//                'uz' => 'Boshqa ishga yollashlardan ish joyi postlariga kirish', // Uzbecki
//                'vi' => 'Truy cập vào các bài đăng công việc từ các nhà tuyển dụng khác', // Wietnamski
//                'zh' => '访问来自其他招聘者的职位发布' // Chiński
//            ])
//        ]);
//        $p5 = Permission::create([
//            'name' => 'access to other recruiters CVs',
//            'trans' => json_encode([
//                'am' => 'ከሌሎች ተመራቂዎች ኪቪኤስ ማስታወቂያዎች አቅርቦት', // Amharski
//                'ar' => 'الوصول إلى السير الذاتية للمجندين الآخرين', // Arabski
//                'az' => 'Digər işəgötürənlərin CV-lərinə çıxış', // Azerski
//                'be' => 'Доступ да рэзюмэ іншых наймальнікаў', // Białoruski
//                'bg' => 'Достъп до автобиографии на други наематели', // Bułgarski
//                'bn' => 'অন্যান্য রিক্রুটারদের সিভি অ্যাক্সেস করুন', // Bengalski
//                'bs' => 'Pristup životopisima drugih regrutera', // Bośniacki
//                'ca' => 'Accés als CV d’altres reclutadors', // Kataloński
//                'cs' => 'Přístup k životopisům od jiných náborářů', // Czeski
//                'da' => 'Adgang til CV’er fra andre rekruttere', // Duński
//                'de' => 'Zugriff auf Lebensläufe von anderen Rekrutierern', // Niemiecki
//                'dv' => 'އިންސަލާ ދައްކަން ގެ ኪቪኤስ', // Divehi
//                'dz' => 'གནས་ཚུ་བསྟན་ནི།', // Dzongkha
//                'el' => 'Πρόσβαση σε βιογραφικά άλλων εργοδότες', // Grecki
//                'en' => 'Access to other recruiters CVs', // Angielski
//                'es' => 'Acceso a los CV de otros reclutadores', // Hiszpański
//                'et' => 'Ligipääs teiste värbajate CV-dele', // Estoński
//                'fa' => 'دسترسی به رزومه‌های سایر استخدام‌کنندگان', // Perski
//                'fi' => 'Pääsy muiden rekrytoijien CV:ihin', // Fiński
//                'fr' => 'Accès aux CV d’autres recruteurs', // Francuski
//                'he' => 'גישה לקורות חיים של מגייסים אחרים', // Hebrajski
//                'hi' => 'अन्य भर्तीकर्ताओं के सीवी तक पहुँच', // Hindi
//                'hr' => 'Pristup životopisima drugih regrutera', // Chorwacki
//                'hu' => 'Hozzáférés más toborzók önéletrajzaihoz', // Węgierski
//                'hy' => 'Մուտք դեպի այլ ռեկրուտերի CV-ներ', // Ormiański
//                'id' => 'Akses ke CV perekrut lain', // Indonezyjski
//                'is' => 'Aðgangur að öðrum ráðningaraðilum CV-um', // Islandzki
//                'it' => 'Accesso ai CV di altri reclutatori', // Włoski
//                'ja' => '他の採用者の履歴書にアクセス', // Japoński
//                'ka' => 'მიღებული CV სხვა რეკრუტერებისგან', // Gruziński
//                'km' => 'ចូលប្រើស៊ីវីពីអ្នកជ្រើសរើសផ្សេងទៀត', // Khmerski
//                'ko' => '다른 채용 담당자의 이력서에 액세스', // Koreański
//                'lb' => 'Zougrouf opgeschonnene CVs vun anere Rekruteuren', // Luksemburski
//                'lo' => 'ການຂໍ້ມູນ CV ຈາກຕົວອື່ນ', // Laotański
//                'lt' => 'Prieiga prie kitų samdytojų CV', // Litewski
//                'lv' => 'Piekļuve citu darba devēju CV', // Łotewski
//                'me' => 'Pristup životopisima drugih regrutera', // Czarnogórski
//                'mk' => 'Пристап до CV-ја од други наемачи', // Macedoński
//                'mn' => 'Бусад ажилд авах хүмүүстэй холбогдсон CV', // Mongołski
//                'ms' => 'Akses kepada CV perekrut lain', // Malajski
//                'my' => 'အခြားခေါင်းစဉ်များမှ CV ကို ဝင်ရောက်ကြည့်ပါ', // Birmański
//                'ne' => 'अन्य भर्तीकर्ताहरूको CV मा पहुँच', // Nepalski
//                'nl' => 'Toegang tot CV’s van andere recruiters', // Holenderski
//                'no' => 'Tilgang til CV-er fra andre rekrutterere', // Norweski
//                'pl' => 'Dostęp do CV innych rekruterów', // Polski
//                'ps' => 'د نورو استخدام کونکو څخه د CV لاسرسی', // Paszto
//                'pt' => 'Acesso aos CVs de outros recrutadores', // Portugalski
//                'ro' => 'Acces la CV-urile altor recrutoare', // Rumuński
//                'ru' => 'Доступ к резюме от других рекрутеров', // Rosyjski
//                'si' => 'අනිත් බඳවා ගැනීම්වලට CV බලන්න', // Syngaleski
//                'sk' => 'Prístup k životopisom od iných náborárov', // Słowacki
//                'sl' => 'Dostop do življenjepisov drugih rekruterjev', // Słoweński
//                'sq' => 'Aksesi në CV-të e rekruterëve të tjerë', // Albański
//                'sr' => 'Pristup životopisima drugih regrutera', // Serbski
//                'sv' => 'Åtkomst till CV:n från andra rekryterare', // Szwedzki
//                'tg' => 'Доступ ба CV-ҳои рекрутерҳои дигар', // Tadżycki
//                'th' => 'การเข้าถึง CV จากผู้สรรหาคนอื่น', // Tajski
//                'tk' => 'Başka işəgötürənlərin CV-lərinə giriş', // Turkmeński
//                'tr' => 'Diğer işe alım uzmanlarının CV’lerine erişim', // Turecki
//                'uk' => 'Доступ до резюме інших рекрутерів', // Ukraiński
//                'uz' => 'Boshqa ishga yollashlarning CV-lariga kirish', // Uzbecki
//                'vi' => 'Truy cập CV của các nhà tuyển dụng khác', // Wietnamski
//                'zh' => '访问其他招聘者的简历' // Chiński
//            ])
//        ]);
//        $p6 = Permission::create([
//            'name' => 'sharing access to own CVs',
//            'trans' => json_encode([
//                'am' => 'ማታያያት አቅርቦት ወደ ራስ ማንኛውም CV', // Amharski
//                'ar' => 'مشاركة الوصول إلى السير الذاتية الخاصة بك', // Arabski
//                'az' => 'Öz CV-lərə paylaşım hüququ', // Azerski
//                'be' => 'Падзяліцца доступам да ўласных рэзюмэ', // Białoruski
//                'bg' => 'Споделяне на достъп до собствените CV', // Bułgarski
//                'bn' => 'নিজস্ব সিভি শেয়ার করার প্রবেশাধিকার', // Bengalski
//                'bs' => 'Dijeljenje pristupa vlastitim CV-ovima', // Bośniacki
//                'ca' => 'Compartir accés als propis CV', // Kataloński
//                'cs' => 'Sdílení přístupu k vlastním životopisům', // Czeski
//                'da' => 'Del adgang til egne CV\'er', // Duński
//                'de' => 'Zugang zu eigenen Lebensläufen teilen', // Niemiecki
//                'dv' => 'ކަމެއްވެރި ހަމަޖެން ކުރަންޝާން އެކިއަށް', // Divehi
//                'dz' => 'བརྗེ་བ་རིགས་འདི་  བསྐུར་བཏང་ཡོད', // Dzongkha
//                'el' => 'Μοιραστείτε την πρόσβαση στο δικό σας βιογραφικό', // Grecki
//                'en' => 'Sharing access to own CVs', // Angielski
//                'es' => 'Compartir acceso a los propios CV', // Hiszpański
//                'et' => 'Jagada oma CV-dele jagamisõigus', // Estoński
//                'fa' => 'اشتراک گذاری دسترسی به رزومه‌های خود', // Perski
//                'fi' => 'Oman CV:ni jakaminen', // Fiński
//                'fr' => 'Partager l’accès à ses propres CV', // Francuski
//                'he' => 'שיתוף גישה לקורות חיים שלך', // Hebrajski
//                'hi' => 'अपने सीवी को साझा करने का अधिकार', // Hindi
//                'hr' => 'Dijeljenje pristupa vlastitim životopisima', // Chorwacki
//                'hu' => 'Saját önéletrajzok hozzáférésének megosztása', // Węgierski
//                'hy' => 'Կիսվել սեփական CV-ներին հասանելիություն', // Ormiański
//                'id' => 'Berbagi akses ke CV sendiri', // Indonezyjski
//                'is' => 'Deila aðgangi að eigin CV', // Islandzki
//                'it' => 'Condividere l’accesso ai propri CV', // Włoski
//                'ja' => '自分の履歴書へのアクセスを共有', // Japoński
//                'ka' => 'წარმოადგინეთ თქვენი CV წვდომის გაზიარება', // Gruziński
//                'km' => 'ចែករំលែកការចូលប្រើ CV ផ្ទាល់ខ្លួន', // Khmerski
//                'ko' => '자신의 이력서 공유 접근', // Koreański
//                'lb' => 'Gedeelt vun Zougrouf op äigene CVs', // Luksemburski
//                'lo' => 'ການຂໍ້ມູນ CV ສໍາລັບຕົວເອງ', // Laotański
//                'lt' => 'Dalijimasis prieiga prie savo CV', // Litewski
//                'lv' => 'Dalīties ar piekļuvi saviem CV', // Łotewski
//                'me' => 'Podijelite pristup vlastitim CV', // Czarnogórski
//                'mk' => 'Сподели пристап до сопствени CV', // Macedoński
//                'mn' => 'Өөрийн CV-ийг хуваалцах эрх', // Mongołski
//                'ms' => 'Berbagi akses ke CV sendiri', // Malajski
//                'my' => 'မိမိ၏ CV များကိုမျှဝေခြင်း', // Birmański
//                'ne' => 'आफ्नो CV को पहुँच साझा गर्नुहोस्', // Nepalski
//                'nl' => 'Delen van toegang tot eigen CV\'s', // Holenderski
//                'no' => 'Deling av tilgang til egne CV-er', // Norweski
//                'pl' => 'Udostępnianie dostępu do własnych CV', // Polski
//                'ps' => 'د خپل CV ته لاسرسی شریکول', // Paszto
//                'pt' => 'Compartilhar acesso aos próprios CVs', // Portugalski
//                'ro' => 'Partajarea accesului la propriile CV-uri', // Rumuński
//                'ru' => 'Общий доступ к своим резюме', // Rosyjski
//                'si' => 'ඔබගේ CV හි පිවිසුම බෙදා හරිනවා', // Syngaleski
//                'sk' => 'Zdieľanie prístupu k vlastným životopisom', // Słowacki
//                'sl' => 'Dajanje dostopa do lastnih življenjepisov', // Słoweński
//                'sq' => 'Ndaje aksesin në CV-të tuaja', // Albański
//                'sr' => 'Deljenje pristupa sopstvenim CV-ovima', // Serbski
//                'sv' => 'Dela åtkomst till egna CV:n', // Szwedzki
//                'tg' => 'Шарик кардани дастрасӣ ба CV-и худ', // Tadżycki
//                'th' => 'การแบ่งปันการเข้าถึงประวัติย่อของคุณ', // Tajski
//                'tk' => 'Öz CV-lərinizə girişi paylaşmaq', // Turkmeński
//                'tr' => 'Kendi CV\'lerinize erişimi paylaşma', // Turecki
//                'uk' => 'Спільний доступ до власних резюме', // Ukraiński
//                'uz' => 'O‘z CV-lariga kirishni ulashish', // Uzbecki
//                'vi' => 'Chia sẻ quyền truy cập vào CV của chính mình', // Wietnamski
//                'zh' => '共享访问自己的简历' // Chiński
//            ])
//        ]);
//        $p7 = Permission::create([
//            'name' => 'sharing access to own projects',
//            'trans' => json_encode([
//                'am' => 'ማታያያት አቅርቦት ለእራስ ፕሮጀክቶች', // Amharski
//                'ar' => 'مشاركة الوصول إلى المشاريع الخاصة بك', // Arabski
//                'az' => 'Öz layihələrə paylaşım hüququ', // Azerski
//                'be' => 'Падзяліцца доступам да ўласных праектаў', // Białoruski
//                'bg' => 'Споделяне на достъп до собствени проекти', // Bułgarski
//                'bn' => 'নিজস্ব প্রকল্পগুলি শেয়ার করার প্রবেশাধিকার', // Bengalski
//                'bs' => 'Dijeljenje pristupa vlastitim projektima', // Bośniacki
//                'ca' => 'Compartir accés als propis projectes', // Kataloński
//                'cs' => 'Sdílení přístupu k vlastním projektům', // Czeski
//                'da' => 'Del adgang til egne projekter', // Duński
//                'de' => 'Zugang zu eigenen Projekten teilen', // Niemiecki
//                'dv' => 'ކަމެއްވެރި ހަމަޖެން ކުރަންޝާން އެކިއަށް', // Divehi
//                'dz' => 'བརྗེ་བ་རིགས་འདི་  བསྐུར་བཏང་ཡོད', // Dzongkha
//                'el' => 'Μοιραστείτε την πρόσβαση στα δικά σας έργα', // Grecki
//                'en' => 'Sharing access to own projects', // Angielski
//                'es' => 'Compartir acceso a los propios proyectos', // Hiszpański
//                'et' => 'Jagada oma projektide jagamisõigus', // Estoński
//                'fa' => 'اشتراک گذاری دسترسی به پروژه‌های خود', // Perski
//                'fi' => 'Oman projektin jakaminen', // Fiński
//                'fr' => 'Partager l’accès à ses propres projets', // Francuski
//                'he' => 'שיתוף גישה לפרויקטים שלך', // Hebrajski
//                'hi' => 'अपने प्रोजेक्ट को साझा करने का अधिकार', // Hindi
//                'hr' => 'Dijeljenje pristupa vlastitim projektima', // Chorwacki
//                'hu' => 'Saját projektek hozzáférésének megosztása', // Węgierski
//                'hy' => 'Կիսվել սեփական նախագծերին հասանելիություն', // Ormiański
//                'id' => 'Berbagi akses ke proyek sendiri', // Indonezyjski
//                'is' => 'Deila aðgangi að eigin verkefnum', // Islandzki
//                'it' => 'Condividere l’accesso ai propri progetti', // Włoski
//                'ja' => '自分のプロジェクトへのアクセスを共有', // Japoński
//                'ka' => 'წარმოადგინეთ თქვენი პროექტების წვდომის გაზიარება', // Gruziński
//                'km' => 'ចែករំលែកការចូលប្រើគម្រោងផ្ទាល់ខ្លួន', // Khmerski
//                'ko' => '자신의 프로젝트 공유 접근', // Koreański
//                'lb' => 'Gedeelt vun Zougrouf op äigene Projeten', // Luksemburski
//                'lo' => 'ການຂໍ້ມູນ CV ສໍາລັບຕົວເອງ', // Laotański
//                'lt' => 'Dalijimasis prieiga prie savo projektų', // Litewski
//                'lv' => 'Dalīties ar piekļuvi saviem projektiem', // Łotewski
//                'me' => 'Podijelite pristup vlastitim projektima', // Czarnogórski
//                'mk' => 'Сподели пристап до сопствени проекти', // Macedoński
//                'mn' => 'Өөрийн төслүүд рүү хандах эрх хуваалцах', // Mongołski
//                'ms' => 'Berbagi akses ke projek sendiri', // Malajski
//                'my' => 'မိမိ၏ စီမံကိန်းများကိုမျှဝေခြင်း', // Birmański
//                'ne' => 'आफ्नो परियोजनाको पहुँच साझा गर्नुहोस्', // Nepalski
//                'nl' => 'Delen van toegang tot eigen projecten', // Holenderski
//                'no' => 'Deling av tilgang til egne prosjekter', // Norweski
//                'pl' => 'Udostępnianie dostępu do własnych projektów', // Polski
//                'ps' => 'د خپل پروژو ته لاسرسی شریکول', // Paszto
//                'pt' => 'Compartilhar acesso aos próprios projetos', // Portugalski
//                'ro' => 'Partajarea accesului la propriile proiecte', // Rumuński
//                'ru' => 'Общий доступ к собственным проектам', // Rosyjski
//                'si' => 'ඔබගේ ව්‍යාපෘතීන් වෙත පිවිසුම බෙදා හරිනවා', // Syngaleski
//                'sk' => 'Zdieľanie prístupu k vlastným projektom', // Słowacki
//                'sl' => 'Dajanje dostopa do lastnih projektov', // Słoweński
//                'sq' => 'Ndaje aksesin në projektet tuaja', // Albański
//                'sr' => 'Deljenje pristupa sopstvenim projektima', // Serbski
//                'sv' => 'Dela åtkomst till egna projekt', // Szwedzki
//                'tg' => 'Шарик кардани дастрасӣ ба лоиҳаҳои худ', // Tadżycki
//                'th' => 'การแบ่งปันการเข้าถึงโครงการของคุณ', // Tajski
//                'tk' => 'Öz layihələrinizə girişi paylaşmak', // Turkmeński
//                'tr' => 'Kendi projelerinize erişimi paylaşma', // Turecki
//                'uk' => 'Спільний доступ до власних проектів', // Ukraiński
//                'uz' => 'O‘z loyihalaringizga kirishni ulashish', // Uzbecki
//                'vi' => 'Chia sẻ quyền truy cập vào các dự án của bạn', // Wietnamski
//                'zh' => '共享访问自己的项目' // Chiński
//            ])
//        ]);
//        $p8 = Permission::create([
//            'name' => 'data transfer between recruiters',
//            'trans' => json_encode([
//                'am' => 'ማታያያት አቅርቦት በሪኩርተርዎች መካከል', // Amharski
//                'ar' => 'نقل البيانات بين المجندين', // Arabski
//                'az' => 'Rekruterlər arasında məlumat ötürülməsi', // Azerski
//                'be' => 'Перадача дадзеных паміж рэкрутэрамі', // Białoruski
//                'bg' => 'Прехвърляне на данни между рекрутъри', // Bułgarski
//                'bn' => 'রিক্রুটারদের মধ্যে ডেটা স্থানান্তর', // Bengalski
//                'bs' => 'Prenos podataka između regrutera', // Bośniacki
//                'ca' => 'Transfer de dades entre reclutadors', // Kataloński
//                'cs' => 'Přenos dat mezi náboráři', // Czeski
//                'da' => 'Dataoverførsel mellem rekrutterere', // Duński
//                'de' => 'Datenübertragung zwischen Recruitern', // Niemiecki
//                'dv' => 'މަދު ދެއްކެވެ ދައްކަން ރިކުޓަރެރަދް', // Divehi
//                'dz' => 'རྒྱུན་ལུང་སྤུངས་བའི་སྐད་འཛུལ་ནི།', // Dzongkha
//                'el' => 'Μεταφορά δεδομένων μεταξύ των προσλήψεων', // Grecki
//                'en' => 'Data transfer between recruiters', // Angielski
//                'es' => 'Transferencia de datos entre reclutadores', // Hiszpański
//                'et' => 'Andmete ülekandmine värbajate vahel', // Estoński
//                'fa' => 'انتقال داده بین استخدام‌کنندگان', // Perski
//                'fi' => 'Tietojen siirto rekrytoijien välillä', // Fiński
//                'fr' => 'Transfert de données entre recruteurs', // Francuski
//                'he' => 'העברת נתונים בין מגייסים', // Hebrajski
//                'hi' => 'भर्ती करने वालों के बीच डेटा स्थानांतरण', // Hindi
//                'hr' => 'Prijenos podataka između regrutera', // Chorwacki
//                'hu' => 'Adatátvitel a toborzók között', // Węgierski
//                'hy' => 'Տվյալների փոխանցում վարձակալների միջև', // Ormiański
//                'id' => 'Transfer data antar perekrut', // Indonezyjski
//                'is' => 'Gagnamiðlun milli ráðningaraðila', // Islandzki
//                'it' => 'Trasferimento dati tra i reclutatori', // Włoski
//                'ja' => 'リクルーター間でのデータ転送', // Japoński
//                'ka' => 'დონატორი მონაცემთა გადაცემა', // Gruziński
//                'km' => 'ការផ្ទេរទិន្នន័យរវាងអ្នកជ្រើសរើស', // Khmerski
//                'ko' => '채용 담당자 간 데이터 전송', // Koreański
//                'lb' => 'Daten Iwwerdroung tëscht Rekruter', // Luksemburski
//                'lo' => 'ການຖາມຄໍາສັບເພື່ອທົດສອບຂໍ້ມູນ', // Laotański
//                'lt' => 'Duomenų perdavimas tarp atrankų', // Litewski
//                'lv' => 'Datu pārsūtīšana starp rekrūtiem', // Łotewski
//                'me' => 'Prijenos podataka između regrutera', // Czarnogórski
//                'mk' => 'Пренос на податоци помеѓу ангажерите', // Macedoński
//                'mn' => 'Бүртгэгчид хооронд мэдээлэл шилжүүлэх', // Mongołski
//                'ms' => 'Pemindahan data antara perekrut', // Malajski
//                'my' => 'အလုပ်သမားများအကြား ဒေတာပြောင်းလဲမှု', // Birmański
//                'ne' => 'भर्तीकर्ताहरू बीच डेटा स्थानान्तरण', // Nepalski
//                'nl' => 'Gegevensoverdracht tussen recruiters', // Holenderski
//                'no' => 'Datatransfer mellom rekrutterere', // Norweski
//                'pl' => 'Transfer danych między rekruterami', // Polski
//                'ps' => 'د ګمارونکي ترمنځ د معلوماتو لیږد', // Paszto
//                'pt' => 'Transferência de dados entre recrutadores', // Portugalski
//                'ro' => 'Transfer de date între recrutorii', // Rumuński
//                'ru' => 'Передача данных между рекрутерами', // Rosyjski
//                'si' => 'ඉදිරිපත් කිරීම පෙන්වන්න', // Syngaleski
//                'sk' => 'Prenos dát medzi náborármi', // Słowacki
//                'sl' => 'Prenos podatkov med rekruterji', // Słoweński
//                'sq' => 'Transferi i të dhënave ndërmjet rekrutuesve', // Albański
//                'sr' => 'Prenos podataka između regrutera', // Serbski
//                'sv' => 'Datatransfer mellan rekryterare', // Szwedzki
//                'tg' => 'Таъсири дода шодакунӣ байни ҷалби назар', // Tadżycki
//                'th' => 'การโอนข้อมูลระหว่างผู้สรรหา', // Tajski
//                'tk' => 'Rekruterler arasynda maglumat transferi', // Turkmeński
//                'tr' => 'Rekrüterler arasında veri transferi', // Turecki
//                'uk' => 'Передача даних між рекрутерами', // Ukraiński
//                'uz' => 'Rekruterlar o‘rtasida ma’lumot uzatish', // Uzbecki
//                'vi' => 'Chuyển dữ liệu giữa các nhà tuyển dụng', // Wietnamski
//                'zh' => '招聘人员之间的数据传输' // Chiński
//            ])
//        ]);
        $p9 = Permission::create([
            'name' => 'application status',
            'trans' => json_encode([
                'am' => 'የመተግበሪያ ሁኔታ', // Amharski
                'ar' => 'حالة التطبيق', // Arabski
                'az' => 'Tətbiq vəziyyəti', // Azerski
                'be' => 'Статус заяўкі', // Białoruski
                'bg' => 'Състояние на приложението', // Bułgarski
                'bn' => 'আবেদন স্থিতি', // Bengalski
                'bs' => 'Status aplikacije', // Bośniacki
                'ca' => 'Estat de la sol·licitud', // Kataloński
                'cs' => 'Stav aplikace', // Czeski
                'da' => 'Ansøgningsstatus', // Duński
                'de' => 'Anwendungsstatus', // Niemiecki
                'dv' => 'އެޕްލިކޭޝަން ސްޓޭޓަސް', // Divehi
                'dz' => 'ཞུ་བ་གནས་ཚད།', // Dzongkha
                'el' => 'Κατάσταση αίτησης', // Grecki
                'en' => 'Application status', // Angielski
                'es' => 'Estado de la aplicación', // Hiszpański
                'et' => 'Rakenduse olek', // Estoński
                'fa' => 'وضعیت برنامه', // Perski
                'fi' => 'Sovelluksen tila', // Fiński
                'fr' => 'Statut de la demande', // Francuski
                'he' => 'סטטוס יישום', // Hebrajski
                'hi' => 'आवेदन की स्थिति', // Hindi
                'hr' => 'Status aplikacije', // Chorwacki
                'hu' => 'Alkalmazás állapota', // Węgierski
                'hy' => 'Դիմումի կարգավիճակը', // Ormiański
                'id' => 'Status aplikasi', // Indonezyjski
                'is' => 'Staða umsóknar', // Islandzki
                'it' => 'Stato dell\'applicazione', // Włoski
                'ja' => 'アプリケーションのステータス', // Japoński
                'ka' => 'აპლიკაციის სტატუსი', // Gruziński
                'km' => 'ស្ថានភាពពាក្យស្នើ', // Khmerski
                'ko' => '애플리케이션 상태', // Koreański
                'lb' => 'Uwendungsstatus', // Luksemburski
                'lo' => 'ສະຖານະໃບສະໝັກ', // Laotański
                'lt' => 'Programos būsena', // Litewski
                'lv' => 'Lietotnes statuss', // Łotewski
                'me' => 'Status aplikacije', // Czarnogórski
                'mk' => 'Статус на апликацијата', // Macedoński
                'mn' => 'Програмын төлөв', // Mongołski
                'ms' => 'Status permohonan', // Malajski
                'my' => 'လျှောက်လွှာအခြေအနေ', // Birmański
                'ne' => 'अनुप्रयोग स्थिति', // Nepalski
                'nl' => 'Toepassingsstatus', // Holenderski
                'no' => 'Applikasjonsstatus', // Norweski
                'pl' => 'Status aplikacji', // Polski
                'ps' => 'د غوښتنلیک حالت', // Paszto
                'pt' => 'Status da aplicação', // Portugalski
                'ro' => 'Stare aplicație', // Rumuński
                'ru' => 'Статус приложения', // Rosyjski
                'si' => 'අයදුම් පිළිවෙල', // Syngaleski
                'sk' => 'Stav aplikácie', // Słowacki
                'sl' => 'Status aplikacije', // Słoweński
                'sq' => 'Statusi i aplikacionit', // Albański
                'sr' => 'Status aplikacije', // Serbski
                'sv' => 'Ansökningsstatus', // Szwedzki
                'tg' => 'Вазъи барнома', // Tadżycki
                'th' => 'สถานะการสมัคร', // Tajski
                'tk' => 'Arza ýagdaýy', // Turkmeński
                'tr' => 'Başvuru durumu', // Turecki
                'uk' => 'Статус заявки', // Ukraiński
                'uz' => 'Ilova holati', // Uzbecki
                'vi' => 'Trạng thái ứng dụng', // Wietnamski
                'zh' => '申请状态' // Chiński
            ])
        ]);
        $p10 = Permission::create([
            'name' => 'contacting candidates',
            'trans' => json_encode([
                'am' => 'ማታያያት አቅርቦት ስለእንግዶች እንቆቅልሽ', // Amharski
                'ar' => 'الاتصال بالمرشحين', // Arabski
                'az' => 'Namizədlərlə əlaqə', // Azerski
                'be' => 'Кантактаванне з кандыдатамі', // Białoruski
                'bg' => 'Контактуване с кандидати', // Bułgarski
                'bn' => 'প্রার্থীদের সাথে যোগাযোগ করুন', // Bengalski
                'bs' => 'Kontaktiranje kandidata', // Bośniacki
                'ca' => 'Contactar amb els candidats', // Kataloński
                'cs' => 'Kontaktování kandidátů', // Czeski
                'da' => 'Kontakt med kandidater', // Duński
                'de' => 'Kontaktaufnahme mit Kandidaten', // Niemiecki
                'dv' => 'ކަމަށް ހެދިބާލު ކުރެވޭ', // Divehi
                'dz' => 'བསྟན་ནི། ལས་འཛུལ་དང་མི་རུས་སྐོར།', // Dzongkha
                'el' => 'Επικοινωνία με υποψηφίους', // Grecki
                'en' => 'Contacting candidates', // Angielski
                'es' => 'Contactar con los candidatos', // Hiszpański
                'et' => 'Kandidaatidega ühendust võtmine', // Estoński
                'fa' => 'تماس با نامزدها', // Perski
                'fi' => 'Yhteydenottaminen ehdokkaisiin', // Fiński
                'fr' => 'Contacter les candidats', // Francuski
                'he' => 'יצירת קשר עם מועמדים', // Hebrajski
                'hi' => 'उम्मीदवारों से संपर्क करना', // Hindi
                'hr' => 'Kontaktiranje kandidata', // Chorwacki
                'hu' => 'Jelöltek megkeresése', // Węgierski
                'hy' => 'Հաղորդակցություն թեկնածուների հետ', // Ormiański
                'id' => 'Menghubungi kandidat', // Indonezyjski
                'is' => 'Hafa samband við frambjóðendur', // Islandzki
                'it' => 'Contattare i candidati', // Włoski
                'ja' => '候補者に連絡', // Japoński
                'ka' => 'კონტაქტი კანდიდატებთან', // Gruziński
                'km' => 'ទំនាក់ទំនងជាមួយអ្នកដាក់ពាក្យ', // Khmerski
                'ko' => '후보자와 연락하기', // Koreański
                'lb' => 'Kontaktéieren mat Kandidaten', // Luksemburski
                'lo' => 'ຕິດຕໍ່ກັບຜູ້ສະເຫຼີມຄິດ', // Laotański
                'lt' => 'Kontaktavimas su kandidatais', // Litewski
                'lv' => 'Sazināties ar kandidātiem', // Łotewski
                'me' => 'Kontaktiranje kandidata', // Czarnogórski
                'mk' => 'Контактирање со кандидати', // Macedoński
                'mn' => 'Бүртгүүлэгчидтэй холбоо барих', // Mongołski
                'ms' => 'Menghubungi calon', // Malajski
                'my' => 'လျှောက်ထားသူများနှင့်ဆက်သွယ်ခြင်း', // Birmański
                'ne' => 'प्रत्याशीहरूलाई सम्पर्क गर्नुहोस्', // Nepalski
                'nl' => 'Contact opnemen met kandidaten', // Holenderski
                'no' => 'Kontakte kandidater', // Norweski
                'pl' => 'Kontaktowanie się z kandydatami', // Polski
                'ps' => 'د کاندیدانو سره اړیکه ونیسئ', // Paszto
                'pt' => 'Entrar em contato com os candidatos', // Portugalski
                'ro' => 'Contactarea candidaților', // Rumuński
                'ru' => 'Связь с кандидатами', // Rosyjski
                'si' => 'අයදුම්කාරයන්සහ සම්බන්ධ වීම', // Syngaleski
                'sk' => 'Kontaktovanie s kandidátmi', // Słowacki
                'sl' => 'Kontaktiranje s kandidati', // Słoweński
                'sq' => 'Kontakti me kandidatët', // Albański
                'sr' => 'Kontaktiranje kandidata', // Serbski
                'sv' => 'Kontakta kandidater', // Szwedzki
                'tg' => 'Бо номзадон тамос гиред', // Tadżycki
                'th' => 'ติดต่อผู้สมัคร', // Tajski
                'tk' => 'Adaylar bilen aragatnaşyk', // Turkmeński
                'tr' => 'Adaylarla iletişime geçmek', // Turecki
                'uk' => 'Зв\'язок з кандидатами', // Ukraiński
                'uz' => 'Nomzodlar bilan bog\'lanish', // Uzbecki
                'vi' => 'Liên hệ với ứng viên', // Wietnamski
                'zh' => '与候选人联系', // Chiński
            ])
        ]);
        $p11 = Permission::create([
            'name' => 'candidate evaluation',
            'trans' => json_encode([
                'am' => 'ማታያያት አቅርቦት እንዲሁም መለኪያ', // Amharski
                'ar' => 'تقييم المرشحين', // Arabski
                'az' => 'Namizədin qiymətləndirilməsi', // Azerski
                'be' => 'Ацэнка кандыдата', // Białoruski
                'bg' => 'Оценка на кандидата', // Bułgarski
                'bn' => 'প্রার্থী মূল্যায়ন', // Bengalski
                'bs' => 'Evaluacija kandidata', // Bośniacki
                'ca' => 'Avaluació del candidat', // Kataloński
                'cs' => 'Hodnocení kandidáta', // Czeski
                'da' => 'Vurdering af kandidater', // Duński
                'de' => 'Bewerterstellung von Kandidaten', // Niemiecki
                'dv' => 'ކަމަށް ހެދިބާލު ކުރެވޭ ވަށް', // Divehi
                'dz' => 'བསྟན་ནི། ལས་འཛུལ་དང་མི་རུས་སྐོར།', // Dzongkha
                'el' => 'Αξιολόγηση υποψηφίου', // Grecki
                'en' => 'Candidate evaluation', // Angielski
                'es' => 'Evaluación de candidatos', // Hiszpański
                'et' => 'Kandidaadi hindamine', // Estoński
                'fa' => 'ارزیابی نامزدها', // Perski
                'fi' => 'Ehdokkaiden arviointi', // Fiński
                'fr' => 'Évaluation des candidats', // Francuski
                'he' => 'הערכת מועמדים', // Hebrajski
                'hi' => 'उम्मीदवार मूल्यांकन', // Hindi
                'hr' => 'Evaluacija kandidata', // Chorwacki
                'hu' => 'Jelölt értékelés', // Węgierski
                'hy' => 'Հայտարարություն իրականացրեք', // Ormiański
                'id' => 'Penilaian kandidat', // Indonezyjski
                'is' => 'Mat á meta frambjóðendur', // Islandzki
                'it' => 'Valutazione del candidato', // Włoski
                'ja' => '候補者評価', // Japoński
                'ka' => 'კანდიდატის შეფასება', // Gruziński
                'km' => 'ការវាយតម្លៃអ្នកដាក់ពាក្យ', // Khmerski
                'ko' => '후보자 평가', // Koreański
                'lb' => 'Kandidat bewäerten', // Luksemburski
                'lo' => 'ການປະເມີນຜູ້ສະເຫຼີມຄິດ', // Laotański
                'lt' => 'Kandidato vertinimas', // Litewski
                'lv' => 'Kandidāta novērtēšana', // Łotewski
                'me' => 'Evaluacija kandidata', // Czarnogórski
                'mk' => 'Оценување на кандидат', // Macedoński
                'mn' => 'Бүртгүүлэгчийн үнэлгээ', // Mongołski
                'ms' => 'Penilaian calon', // Malajski
                'my' => 'လျှောက်ထားသူများကိုအကဲဖြတ်ခြင်း', // Birmański
                'ne' => 'उम्मीदवारको मूल्याङ्कन गर्नुहोस्', // Nepalski
                'nl' => 'Beoordeling van kandidaten', // Holenderski
                'no' => 'Vurdering av kandidater', // Norweski
                'pl' => 'Ocena kandydatów', // Polski
                'ps' => 'د کاندیدانو ارزونه', // Paszto
                'pt' => 'Avaliação de candidatos', // Portugalski
                'ro' => 'Evaluarea candidaților', // Rumuński
                'ru' => 'Оценка кандидатов', // Rosyjski
                'si' => 'ඉදිරිපත් කිරීම පෙන්වන්න', // Syngaleski
                'sk' => 'Hodnotenie kandidátov', // Słowacki
                'sl' => 'Ocena kandidatov', // Słoweński
                'sq' => 'Vlerësimi i kandidatëve', // Albański
                'sr' => 'Evaluacija kandidata', // Serbski
                'sv' => 'Utvärdering av kandidater', // Szwedzki
                'tg' => 'Ба номзадҳо баҳогузорӣ кардан', // Tadżycki
                'th' => 'การประเมินผู้สมัคร', // Tajski
                'tk' => 'Adayların değerlendirilmesi', // Turkmeński
                'tr' => 'Aday değerlendirmesi', // Turecki
                'uk' => 'Оцінка кандидатів', // Ukraiński
                'uz' => 'Nomzodlar baholash', // Uzbecki
                'vi' => 'Đánh giá ứng viên', // Wietnamski
                'zh' => '候选人评估', // Chiński
            ])
        ]);
        $p12 = Permission::create([
            'name' => 'creating recruitment questions',
            'trans' => json_encode([
                'am' => 'ማታያያት አቅርቦት እንዲሁም መለኪያ', // Amharski
                'ar' => 'إنشاء أسئلة التوظيف', // Arabski
                'az' => 'İşə qəbul sualları yaratmaq', // Azerski
                'be' => 'Стварэнне пытанняў для набору', // Białoruski
                'bg' => 'Създаване на въпроси за наемане', // Bułgarski
                'bn' => 'নিয়োগ প্রশ্ন তৈরি করা', // Bengalski
                'bs' => 'Kreiranje pitanja za zapošljavanje', // Bośniacki
                'ca' => 'Creació de preguntes de reclutament', // Kataloński
                'cs' => 'Vytváření otázek pro nábor', // Czeski
                'da' => 'Oprettelse af rekrutteringsspørgsmål', // Duński
                'de' => 'Erstellung von Rekrutierungsfragen', // Niemiecki
                'dv' => 'ކަމަށް ހެދިބާލު ކުރެވޭ ވަށް', // Divehi
                'dz' => 'བསྟན་ནི། ལས་འཛུལ་དང་མི་རུས་སྐོར།', // Dzongkha
                'el' => 'Δημιουργία ερωτήσεων πρόσληψης', // Grecki
                'en' => 'Creating recruitment questions', // Angielski
                'es' => 'Creación de preguntas de reclutamiento', // Hiszpański
                'et' => 'Töötajate värbamise küsimuste loomine', // Estoński
                'fa' => 'ایجاد سوالات استخدام', // Perski
                'fi' => 'Rekrytointikysymysten luominen', // Fiński
                'fr' => 'Création de questions de recrutement', // Francuski
                'he' => 'יצירת שאלות גיוס', // Hebrajski
                'hi' => 'भर्ती प्रश्नों का निर्माण', // Hindi
                'hr' => 'Izrada pitanja za zapošljavanje', // Chorwacki
                'hu' => 'Toborzási kérdések létrehozása', // Węgierski
                'hy' => 'Աշխատանքի ընդունման հարցերի ստեղծում', // Ormiański
                'id' => 'Membuat pertanyaan perekrutan', // Indonezyjski
                'is' => 'Búa til ráðningarmála', // Islandzki
                'it' => 'Creazione di domande di reclutamento', // Włoski
                'ja' => '採用質問の作成', // Japoński
                'ka' => 'დასაქმების კითხვების შექმნა', // Gruziński
                'km' => 'បង្កើតសំណួរជ្រើសរើស', // Khmerski
                'ko' => '채용 질문 만들기', // Koreański
                'lb' => 'Erstellen vun Rekrutement Froen', // Luksemburski
                'lo' => 'ສ້າງຄຳຖາມການຮັບຜູ້ສະເຫຼີມ', // Laotański
                'lt' => 'Įdarbinimo klausimų kūrimas', // Litewski
                'lv' => 'Rekrutēšanas jautājumu izveidošana', // Łotewski
                'me' => 'Kreiranje pitanja za zapošljavanje', // Czarnogórski
                'mk' => 'Создавање прашања за вработување', // Macedoński
                'mn' => 'Ажиллын асуултуудыг бий болгох', // Mongołski
                'ms' => 'Membuat soalan pengambilan', // Malajski
                'my' => 'အလုပ်အကိုင်မေးခွန်းများကိုဖန်တီးသည်', // Birmański
                'ne' => 'भर्ती प्रश्नहरू सिर्जना गर्नुहोस्', // Nepalski
                'nl' => 'Vragen voor wervings maken', // Holenderski
                'no' => 'Oppretting av rekrutteringsspørsmål', // Norweski
                'pl' => 'Tworzenie pytań rekrutacyjnych', // Polski
                'ps' => 'د ګمارنې پوښتنې جوړول', // Paszto
                'pt' => 'Criando perguntas de recrutamento', // Portugalski
                'ro' => 'Crearea întrebărilor de recrutare', // Rumuński
                'ru' => 'Создание вопросов для набора персонала', // Rosyjski
                'si' => 'ආයතන ප්‍රශ්න නිර්මාණය', // Syngaleski
                'sk' => 'Vytváranie náborových otázok', // Słowacki
                'sl' => 'Ustvarjanje vprašanj za zaposlovanje', // Słoweński
                'sq' => 'Krijimi i pyetjeve të rekrutimit', // Albański
                'sr' => 'Kreiranje pitanja za zapošljavanje', // Serbski
                'sv' => 'Skapa rekryteringsfrågor', // Szwedzki
                'tg' => 'Саволҳои ҷалби кормандонро эҷод кунед', // Tadżycki
                'th' => 'สร้างคำถามการสรรหางาน', // Tajski
                'tk' => 'Işgäriz soraglaryny döretmek', // Turkmeński
                'tr' => 'İşe alım soruları oluşturmak', // Turecki
                'uk' => 'Створення запитань для набору', // Ukraiński
                'uz' => 'Ishga qabul qilish savollarini yaratish', // Uzbecki
                'vi' => 'Tạo câu hỏi tuyển dụng', // Wietnamski
                'zh' => '创建招聘问题', // Chiński
            ])
        ]);
        $p13 = Permission::create([
            'name' => 'sharing job offers on social media',
            'trans' => json_encode([
                'am' => 'ማታያያት አቅርቦት እንዲሁም መለኪያ', // Amharski
                'ar' => 'مشاركة عروض العمل على وسائل التواصل الاجتماعي', // Arabski
                'az' => 'İş təkliflərini sosial şəbəkələrdə paylaşmaq', // Azerski
                'be' => 'Падзяліцца прапановамі працы ў сацыяльных сетках', // Białoruski
                'bg' => 'Споделяне на обяви за работа в социалните медии', // Bułgarski
                'bn' => 'সামাজিক মাধ্যমে চাকরির অফার শেয়ার করা', // Bengalski
                'bs' => 'Dijeljenje ponuda za posao na društvenim mrežama', // Bośniacki
                'ca' => 'Compartir ofertes de feina a les xarxes socials', // Kataloński
                'cs' => 'Sdílení pracovních nabídek na sociálních médiích', // Czeski
                'da' => 'Del jobtilbud på sociale medier', // Duński
                'de' => 'Jobangebote in sozialen Medien teilen', // Niemiecki
                'dv' => 'މަސްޝާދު ކަމަށް އިން ޚިދާ ހެދިބާލު', // Divehi
                'dz' => 'སྣོད་བསྟན་ནི། ལས་འཛུལ་བསྟེན་ནི།', // Dzongkha
                'el' => 'Μοιραστείτε τις αγγελίες εργασίας στα μέσα κοινωνικής δικτύωσης', // Grecki
                'en' => 'Sharing job offers on social media', // Angielski
                'es' => 'Compartir ofertas de trabajo en redes sociales', // Hiszpański
                'et' => 'Töötukohapakkumiste jagamine sotsiaalmeedias', // Estoński
                'fa' => 'به اشتراک گذاری پیشنهادات شغلی در شبکه‌های اجتماعی', // Perski
                'fi' => 'Työpaikkatarjousten jakaminen sosiaalisessa mediassa', // Fiński
                'fr' => 'Partager des offres d\'emploi sur les réseaux sociaux', // Francuski
                'he' => 'שיתוף הצעות עבודה ברשתות החברתיות', // Hebrajski
                'hi' => 'सामाजिक मीडिया पर नौकरी के प्रस्ताव साझा करें', // Hindi
                'hr' => 'Dijeljenje ponuda za posao na društvenim mrežama', // Chorwacki
                'hu' => 'Álláshirdetések megosztása a közösségi médiában', // Węgierski
                'hy' => 'Աշխատանքի առաջարկների բաժանորդագրում սոցիալական մեդիայում', // Ormiański
                'id' => 'Membagikan tawaran pekerjaan di media sosial', // Indonezyjski
                'is' => 'Deila atvinnutilboðum á samfélagsmiðlum', // Islandzki
                'it' => 'Condividere offerte di lavoro sui social media', // Włoski
                'ja' => 'ソーシャルメディアで求人情報を共有する', // Japoński
                'ka' => 'შეიზიარე სამუშაოს შეთავაზებები სოციალურ მედიაში', // Gruziński
                'km' => 'ចែករំលែកការផ្ដល់ជូនការងារ នៅលើបណ្តាញសង្គម', // Khmerski
                'ko' => '소셜 미디어에 구인 제안을 공유하기', // Koreański
                'lb' => 'Jobsofferen op sozialen Medien deelen', // Luksemburski
                'lo' => 'ການແບ່ງປັນຂໍ້ສະເຫຼີມການງານທາງສັງຄົມ', // Laotański
                'lt' => 'Darbų pasiūlymų dalijimasis socialiniuose tinkluose', // Litewski
                'lv' => 'Darba piedāvājumu dalīšana sociālajos medijos', // Łotewski
                'me' => 'Deljenje ponuda za posao na društvenim mrežama', // Czarnogórski
                'mk' => 'Споделување на понуди за работа на социјалните медиуми', // Macedoński
                'mn' => 'Ажлын саналуудаа нийгмийн медиа дээр хуваалцах', // Mongołski
                'ms' => 'Kongsi tawaran pekerjaan di media sosial', // Malajski
                'my' => 'လူမှုမီဒီယာတွင် အလုပ်အကိုင် အဆိုပြုချက်များကို ပူးတွဲပါ', // Birmański
                'ne' => 'सामाजिक मिडियामा रोजगारी प्रस्ताव साझा गर्नुहोस्', // Nepalski
                'nl' => 'Deel werk aanbiedingen op sociale media', // Holenderski
                'no' => 'Del jobtilbud på sosiale medier', // Norweski
                'pl' => 'Udostępnianie ofert pracy w mediach społecznościowych', // Polski
                'ps' => 'د کار وړاندیزونه په ټولنیزو رسنیو کې شریک کړئ', // Paszto
                'pt' => 'Compartilhar ofertas de trabalho nas redes sociais', // Portugalski
                'ro' => 'Distribuirea ofertelor de muncă pe rețelele sociale', // Rumuński
                'ru' => 'Поделиться вакансиями в социальных сетях', // Rosyjski
                'si' => 'සමාජ මාධ්‍ය හරහා රැකියා යෝජනා බෙදාගන්න', // Syngaleski
                'sk' => 'Zdieľanie pracovných ponúk na sociálnych sieťach', // Słowacki
                'sl' => 'Deljenje ponudb za delo na družbenih omrežjih', // Słoweński
                'sq' => 'Shpërndarja e ofertave të punës në mediat sociale', // Albański
                'sr' => 'Deljenje ponuda za posao na društvenim mrežama', // Serbski
                'sv' => 'Dela jobberbjudanden på sociala medier', // Szwedzki
                'tg' => 'Пешниҳодҳоро дар шабакаҳои иҷтимоӣ ба ҳамроҳ кунед', // Tadżycki
                'th' => 'แบ่งปันข้อเสนองานในโซเชียลมีเดีย', // Tajski
                'tk' => 'Iş təkliflərini sosial mediada paylaş', // Turkmeński
                'tr' => 'İş tekliflerini sosyal medyada paylaşmak', // Turecki
                'uk' => 'Поділитися вакансіями в соціальних мережах', // Ukraiński
                'uz' => 'Ish takliflarini ijtimoiy tarmoqlarda ulashish', // Uzbecki
                'vi' => 'Chia sẻ cơ hội việc làm trên mạng xã hội', // Wietnamski
                'zh' => '在社交媒体上分享职位空缺' // Chiński
            ])
        ]);
        $p14 = Permission::create([
            'name' => 'access to personal recruitment calendar',
            'trans' => json_encode([
                'am' => 'እግር ባል ማታያያት የተገለጸ አቅርቦት', // Amharski
                'ar' => 'الوصول إلى تقويم التوظيف الشخصي', // Arabski
                'az' => 'Şəxsi işə qəbul təqviminə daxil olmaq', // Azerski
                'be' => 'Доступ да асабістага календара набору', // Białoruski
                'bg' => 'Достъп до личния календар за подбор', // Bułgarski
                'bn' => 'ব্যক্তিগত নিয়োগ ক্যালেন্ডারে প্রবেশাধিকার', // Bengalski
                'bs' => 'Pristup osobnom kalendaru zapošljavanja', // Bośniacki
                'ca' => 'Accés al calendari personal de contractació', // Kataloński
                'cs' => 'Přístup k osobnímu náborovému kalendáři', // Czeski
                'da' => 'Adgang til personlig rekrutteringskalender', // Duński
                'de' => 'Zugriff auf den persönlichen Rekrutierungskalender', // Niemiecki
                'dv' => 'ހިންތަމަޝަދު ލިކޯ ކަލިކަނދެ', // Divehi
                'dz' => 'སྣོད་བསྟན་ནི། ལས་འཛུལ་བསྟེན་ནི།', // Dzongkha
                'el' => 'Πρόσβαση στο προσωπικό ημερολόγιο πρόσληψης', // Grecki
                'en' => 'Access to personal recruitment calendar', // Angielski
                'es' => 'Acceso al calendario de reclutamiento personal', // Hiszpański
                'et' => 'Juurdepääs isiklikule värbamiskalendrile', // Estoński
                'fa' => 'دسترسی به تقویم استخدام شخصی', // Perski
                'fi' => 'Pääsy henkilökohtaiseen rekrytointikalenteriin', // Fiński
                'fr' => 'Accès au calendrier de recrutement personnel', // Francuski
                'he' => 'גישה ליומן הגיוס האישי', // Hebrajski
                'hi' => 'व्यक्तिगत भर्ती कैलेंडर तक पहुंच', // Hindi
                'hr' => 'Pristup osobnom kalendaru zapošljavanja', // Chorwacki
                'hu' => 'Hozzáférés a személyes toborzási naptárhoz', // Węgierski
                'hy' => 'Անձնական հավաքագրում օրացույցին մուտք ունենալ', // Ormiański
                'id' => 'Akses ke kalender rekrutmen pribadi', // Indonezyjski
                'is' => 'Aðgangur að persónulega ráðningardagskránni', // Islandzki
                'it' => 'Accesso al calendario di reclutamento personale', // Włoski
                'ja' => '個人の採用カレンダーにアクセスする', // Japoński
                'ka' => 'პერსონალური მიღების კალენდრის წვდომა', // Gruziński
                'km' => 'ការចូលដំណើរការពិគ្រោះការងារប្រចាំផ្ទាល់ខ្លួន', // Khmerski
                'ko' => '개인 채용 일정 접근', // Koreański
                'lb' => 'Zougiff un perséinleche Rekrutéierungs-Kalender', // Luksemburski
                'lo' => 'ການຈົດຕື່ມກັບປະຕິເວລາສົງຄາມການຮັບລົງ', // Laotański
                'lt' => 'Prieiga prie asmeninio įdarbinimo kalendoriaus', // Litewski
                'lv' => 'Piekļuve personīgajam pieņemšanas kalendāram', // Łotewski
                'me' => 'Pristup osobnom kalendaru zapošljavanja', // Czarnogórski
                'mk' => 'Достап до личниот календар за вработување', // Macedoński
                'mn' => 'Хувийн ажилд авах хуанлийн нэвтрэх эрх', // Mongołski
                'ms' => 'Akses ke kalendar pengambilan peribadi', // Malajski
                'my' => 'Akses kepada kalendar pengambilan peribadi', // Birmański
                'ne' => 'व्यक्तिगत भर्ती क्यालेन्डरमा पहुँच', // Nepalski
                'nl' => 'Toegang tot persoonlijk wervingskalender', // Holenderski
                'no' => 'Tilgang til personlig rekrutteringskalender', // Norweski
                'pl' => 'Dostęp do osobistego kalendarza rekrutacji', // Polski
                'ps' => 'د شخصي جذب تقویم ته لاسرسی', // Paszto
                'pt' => 'Acesso ao calendário de recrutamento pessoal', // Portugalski
                'ro' => 'Acces la calendarul personal de recrutare', // Rumuński
                'ru' => 'Доступ к личному календарю набора', // Rosyjski
                'si' => 'පෞද්ගලික රැකියා පද්ධති සඳහා ප්‍රවේශය', // Syngaleski
                'sk' => 'Prístup k osobnému kalendáru náboru', // Słowacki
                'sl' => 'Dostop do osebnega koledarja za zaposlovanje', // Słoweński
                'sq' => 'Aksesi në kalendarin personal të rekrutimit', // Albański
                'sr' => 'Pristup ličnom kalendaru zapošljavanja', // Serbski
                'sv' => 'Tillgång till personlig rekryteringskalender', // Szwedzki
                'tg' => 'Доступ ба тартиби шахсии нагариш', // Tadżycki
                'th' => 'การเข้าถึงปฏิทินการสรรหาส่วนบุคคล', // Tajski
                'tk' => 'Şahsy işe kabul kalendaryna girmek', // Turkmeński
                'tr' => 'Kişisel işe alım takvimine erişim', // Turecki
                'uk' => 'Доступ до особистого календаря набору', // Ukraiński
                'uz' => 'Shaxsiy ishga qabul kalendariga kirish', // Uzbecki
                'vi' => 'Truy cập vào lịch tuyển dụng cá nhân', // Wietnamski
                'zh' => '访问个人招聘日历' // Chiński
            ])
        ]);
        $p15 = Permission::create([
            'name' => 'access to all recruiters calendar',
            'trans' => json_encode([
                'am' => 'እግር ባል ማታያያት ለሁሉም አስተማሪ ቀን ማቅረብ', // Amharski
                'ar' => 'الوصول إلى تقويم جميع المجندين', // Arabski
                'az' => 'Bütün işə qəbul edənlərin təqviminə daxil olmaq', // Azerski
                'be' => 'Доступ да календара ўсіх рэкрутэраў', // Białoruski
                'bg' => 'Достъп до календара на всички рекрутери', // Bułgarski
                'bn' => 'সমস্ত নিয়োগকারীর ক্যালেন্ডারে প্রবেশাধিকার', // Bengalski
                'bs' => 'Pristup kalendaru svih regrutera', // Bośniacki
                'ca' => 'Accés al calendari de tots els reclutadors', // Kataloński
                'cs' => 'Přístup ke kalendáři všech náborářů', // Czeski
                'da' => 'Adgang til alle rekrutteringskalendere', // Duński
                'de' => 'Zugriff auf den Kalender aller Recruiter', // Niemiecki
                'dv' => 'ހިންތަމަޝަދު ލިކޯ ކަލިކަނދެ', // Divehi
                'dz' => 'སྣོད་བསྟན་ནི། ལས་འཛུལ་བསྟེན་ནི།', // Dzongkha
                'el' => 'Πρόσβαση στο ημερολόγιο όλων των υπεύθυνων προσλήψεων', // Grecki
                'en' => 'Access to all recruiters calendar', // Angielski
                'es' => 'Acceso al calendario de todos los reclutadores', // Hiszpański
                'et' => 'Juurdepääs kõigi värbajate kalendrisse', // Estoński
                'fa' => 'دسترسی به تقویم همه جذب کنندگان', // Perski
                'fi' => 'Pääsy kaikkien rekrytoijien kalenteriin', // Fiński
                'fr' => 'Accès au calendrier de tous les recruteurs', // Francuski
                'he' => 'גישה ליומן כל המגייסים', // Hebrajski
                'hi' => 'सभी भर्तीकर्ताओं के कैलेंडर तक पहुंच', // Hindi
                'hr' => 'Pristup kalendaru svih regrutera', // Chorwacki
                'hu' => 'Hozzáférés minden toborzó naptárához', // Węgierski
                'hy' => 'Մուտք դեպի բոլոր հավաքագրողների օրացույցը', // Ormiański
                'id' => 'Akses ke kalender semua perekrut', // Indonezyjski
                'is' => 'Aðgangur að öllum ráðningarmanneskju dagbókum', // Islandzki
                'it' => 'Accesso al calendario di tutti i reclutatori', // Włoski
                'ja' => 'すべての採用担当者のカレンダーにアクセスする', // Japoński
                'ka' => 'ყველა რექტორის კალენდერში წვდომა', // Gruziński
                'km' => 'ការចូលដំណើរការពិគ្រោះការងារប្រចាំផ្ទាល់ខ្លួន', // Khmerski
                'ko' => '모든 채용 담당자의 일정 접근', // Koreański
                'lb' => 'Zougiff un perséinleche Rekrutéierungs-Kalender', // Luksemburski
                'lo' => 'ການຈົດຕື່ມກັບປະຕິເວລາສົງຄາມການຮັບລົງ', // Laotański
                'lt' => 'Prieiga prie visų verbuotojų kalendoriaus', // Litewski
                'lv' => 'Piekļuve visu rekruteru kalendāram', // Łotewski
                'me' => 'Pristup kalendaru svih regrutera', // Czarnogórski
                'mk' => 'Достап до календарот на сите рекрутери', // Macedoński
                'mn' => 'Бүх ажилд авах хуанлийн нэвтрэх эрх', // Mongołski
                'ms' => 'Akses ke kalendar semua perekrut', // Malajski
                'my' => 'Akses kepada kalendar semua pengambilan pekerja', // Birmański
                'ne' => 'सबै भर्ती क्यालेन्डरमा पहुँच', // Nepalski
                'nl' => 'Toegang tot de kalender van alle recruiters', // Holenderski
                'no' => 'Tilgang til kalenderen for alle rekrutterere', // Norweski
                'pl' => 'Dostęp do kalendarza wszystkich rekruterów', // Polski
                'ps' => 'د ټولو ګمارونکو کيلنڈر ته لاسرسی', // Paszto
                'pt' => 'Acesso ao calendário de todos os recrutadores', // Portugalski
                'ro' => 'Acces la calendarul tuturor recrutorilor', // Rumuński
                'ru' => 'Доступ к календарю всех рекрутеров', // Rosyjski
                'si' => 'සියළු රැකියා භාණ්ඩය සඳහා යෝජනාවලීන් පෙන්වන්න', // Syngaleski
                'sk' => 'Prístup ku kalendáru všetkých náborárov', // Słowacki
                'sl' => 'Dostop do koledarja vseh zaposlovalcev', // Słoweński
                'sq' => 'Aksesi në kalendarin e të gjithëve rekrutuesve', // Albański
                'sr' => 'Pristup kalendaru svih regrutera', // Serbski
                'sv' => 'Tillgång till alla rekryterares kalendrar', // Szwedzki
                'tg' => 'Доступ ба тартиби шахсии тамоми нагаришгарон', // Tadżycki
                'th' => 'การเข้าถึงปฏิทินของผู้สรรหาทุกคน', // Tajski
                'tk' => 'Ähli işe kabulçileriň kalendaryna girmek', // Turkmeński
                'tr' => 'Tüm işe alımcıların takvimine erişim', // Turecki
                'uk' => 'Доступ до календаря всіх рекрутерів', // Ukraiński
                'uz' => 'Barcha ishga qabul qiluvchilarning kalendariga kirish', // Uzbecki
                'vi' => 'Truy cập vào lịch của tất cả các nhà tuyển dụng', // Wietnamski
                'zh' => '访问所有招聘人员的日历' // Chiński
            ])
        ]);
        $p16 = Permission::create([
            'name' => 'automated messages for candidates',
            'trans' => json_encode([
                'am' => 'መልእክቶች ለምርመራ ሰራተኞች', // Amharski
                'ar' => 'رسائل آلية للمرشحين', // Arabski
                'az' => 'Namizədlər üçün avtomat mesajlar', // Azerski
                'be' => 'Аўтаматычныя паведамленні для кандыдатаў', // Białoruski
                'bg' => 'Автоматизирани съобщения за кандидати', // Bułgarski
                'bn' => 'প্রার্থীদের জন্য স্বয়ংক্রিয় বার্তা', // Bengalski
                'bs' => 'Automatizirane poruke za kandidate', // Bośniacki
                'ca' => 'Missatges automatitzats per a candidats', // Kataloński
                'cs' => 'Automatizované zprávy pro kandidáty', // Czeski
                'da' => 'Automatiske beskeder til kandidater', // Duński
                'de' => 'Automatisierte Nachrichten für Bewerber', // Niemiecki
                'dv' => 'ކަލަދެއް އާ ޝައި ކަބަލި', // Divehi
                'dz' => 'མཐའི་གསུང་འབད་འཛིན་ཀྱི་ཚིག་འདེད་འཇིག', // Dzongkha
                'el' => 'Αυτόματα μηνύματα για υποψηφίους', // Grecki
                'en' => 'Automated messages for candidates', // Angielski
                'es' => 'Mensajes automatizados para candidatos', // Hiszpański
                'et' => 'Automaatmesaged kandidaadile', // Estoński
                'fa' => 'پیام‌های خودکار برای نامزدها', // Perski
                'fi' => 'Automaattiset viestit hakijoille', // Fiński
                'fr' => 'Messages automatisés pour les candidats', // Francuski
                'he' => 'הודעות אוטומטיות למועמדים', // Hebrajski
                'hi' => 'उम्मीदवारों के लिए स्वचालित संदेश', // Hindi
                'hr' => 'Automatizirane poruke za kandidate', // Chorwacki
                'hu' => 'Automatikus üzenetek jelölteknek', // Węgierski
                'hy' => 'Ավտոմատ հաղորդագրություններ թեկնածուների համար', // Ormiański
                'id' => 'Pesan otomatis untuk kandidat', // Indonezyjski
                'is' => 'Sjálfvirk skilaboð fyrir frambjóðendur', // Islandzki
                'it' => 'Messaggi automatizzati per i candidati', // Włoski
                'ja' => '候補者への自動メッセージ', // Japoński
                'ka' => 'ავტომატური შეტყობინებები კანდიდატებისთვის', // Gruziński
                'km' => 'សារស្វ័យប្រវត្តិសម្រាប់បេក្ខជន', // Khmerski
                'ko' => '후보자에게 자동 메시지', // Koreański
                'lb' => 'Automatesch Noriichten fir Kandidaten', // Luksemburski
                'lo' => 'ຂໍ້ຄວາມອັດຕະມັດສຳລັບຜູ້ສະຫຼຸບ', // Laotański
                'lt' => 'Automatizuoti pranešimai kandidatams', // Litewski
                'lv' => 'Automatizēti ziņojumi kandidātiem', // Łotewski
                'me' => 'Automatska poruka za kandidate', // Czarnogórski
                'mk' => 'Автоматски пораки за кандидати', // Macedoński
                'mn' => 'Кандидатуудад зориулсан автоматаар илгээсэн мессежүүд', // Mongołski
                'ms' => 'Mesej automatik untuk calon', // Malajski
                'my' => 'mesej automatik untuk calon', // Birmański
                'ne' => 'उम्मेदवारको लागि स्वचालित सन्देशहरू', // Nepalski
                'nl' => 'Geautomatiseerde berichten voor kandidaten', // Holenderski
                'no' => 'Automatiserte meldinger for kandidater', // Norweski
                'pl' => 'Automatyczne wiadomości dla kandydatów', // Polski
                'ps' => 'د نوماندانو لپاره اتوماتیک پیغامونه', // Paszto
                'pt' => 'Mensagens automatizadas para candidatos', // Portugalski
                'ro' => 'Mesaje automate pentru candidați', // Rumuński
                'ru' => 'Автоматические сообщения для кандидатов', // Rosyjski
                'si' => 'අවශ්‍ය පණිවිඩ පෙන්වන්න', // Syngaleski
                'sk' => 'Automatizované správy pre kandidátov', // Słowacki
                'sl' => 'Avtomatizirane sporočila za kandidate', // Słoweński
                'sq' => 'Mesazhe automatike për kandidatët', // Albański
                'sr' => 'Automatske poruke za kandidate', // Serbski
                'sv' => 'Automatiserade meddelanden för kandidater', // Szwedzki
                'tg' => 'Паёмҳои автоматӣ барои номзадҳо', // Tadżycki
                'th' => 'ข้อความอัตโนมัติสำหรับผู้สมัคร', // Tajski
                'tk' => 'Adaylar üçin awtomatiki hatlar', // Turkmeński
                'tr' => 'Adaylar için otomatik mesajlar', // Turecki
                'uk' => 'Автоматизовані повідомлення для кандидатів', // Ukraiński
                'uz' => 'Nomzodlar uchun avtomatik xabarlar', // Uzbecki
                'vi' => 'Tin nhắn tự động cho ứng viên', // Wietnamski
                'zh' => '候选人的自动消息' // Chiński
            ])
        ]);
        $p17 = Permission::create([
            'name' => 'CV templates for job offers',
            'trans' => json_encode([
                'am' => 'ኮስተም ቪ ማቅረብ ስለ ስራ ማስታወቂያዎች', // Amharski
                'ar' => 'نموذج السيرة الذاتية لفرص العمل', // Arabski
                'az' => 'İş təklifləri üçün CV şablonları', // Azerski
                'be' => 'Рэзюмэ шаблоны для прапаноў працы', // Białoruski
                'bg' => 'Шаблони за автобиографии за работни предложения', // Bułgarski
                'bn' => 'চাকরির প্রস্তাবের জন্য সিভি টেমপ্লেট', // Bengalski
                'bs' => 'CV predlošci za ponude za posao', // Bośniacki
                'ca' => 'Plantilles de CV per ofertes de feina', // Kataloński
                'cs' => 'Šablony životopisů pro pracovní nabídky', // Czeski
                'da' => 'CV-skabeloner til jobtilbud', // Duński
                'de' => 'Lebenslauf-Vorlagen für Stellenangebote', // Niemiecki
                'dv' => 'ކޮސެޓެމު ވި ސިރާ ޙާލު ޝައި ސަރައި', // Divehi
                'dz' => 'སོན་པ་ཁྲིམས་གཟུངས་ཀྱི་བརྗེ་ཁུངས', // Dzongkha
                'el' => 'Πρότυπα βιογραφικών για θέσεις εργασίας', // Grecki
                'en' => 'CV templates for job offers', // Angielski
                'es' => 'Plantillas de CV para ofertas de trabajo', // Hiszpański
                'et' => 'CV mallid tööpakkumiste jaoks', // Estoński
                'fa' => 'الگوهای رزومه برای پیشنهادات شغلی', // Perski
                'fi' => 'CV-mallit työpaikkatarjouksille', // Fiński
                'fr' => 'Modèles de CV pour les offres d\'emploi', // Francuski
                'he' => 'תבניות קורות חיים עבור הצעות עבודה', // Hebrajski
                'hi' => 'नौकरी प्रस्तावों के लिए सीवी टेम्पलेट्स', // Hindi
                'hr' => 'CV predlošci za ponude za posao', // Chorwacki
                'hu' => 'Önéletrajz sablonok álláshirdetésekhez', // Węgierski
                'hy' => 'CV շաբլոններ աշխատանքի առաջարկների համար', // Ormiański
                'id' => 'Template CV untuk tawaran pekerjaan', // Indonezyjski
                'is' => 'CV sniðmát fyrir atvinnuauglýsingar', // Islandzki
                'it' => 'Modelli di CV per offerte di lavoro', // Włoski
                'ja' => '求人情報用の履歴書テンプレート', // Japoński
                'ka' => 'სამუშაო შეთავაზებისთვის CV შაბლონები', // Gruziński
                'km' => 'ស្តង់ដារ CV សម្រាប់ការផ្តល់ជូនការងារ', // Khmerski
                'ko' => '구직 제안에 대한 이력서 템플릿', // Koreański
                'lb' => 'CV-Vorlagen fir Aarbechtsangebote', // Luksemburski
                'lo' => 'ເຫົາຫວິລາປະສົງກັບຄວາມສຸດຂອງສີບທາງ', // Laotański
                'lt' => 'CV šablonai darbo pasiūlymams', // Litewski
                'lv' => 'CV veidnes darba piedāvājumiem', // Łotewski
                'me' => 'CV predlošci za ponude za posao', // Czarnogórski
                'mk' => 'CV шаблони за понуди за работа', // Macedoński
                'mn' => 'Ажлын саналд зориулсан CV загварууд', // Mongołski
                'ms' => 'Templat CV untuk tawaran pekerjaan', // Malajski
                'my' => 'အလုပ်အကိုင်များအတွက် CV template များ', // Birmański
                'ne' => 'रोजगारको प्रस्तावहरूको लागि CV टेम्पलेटहरू', // Nepalski
                'nl' => 'CV-sjablonen voor vacatures', // Holenderski
                'no' => 'CV-maler for jobbtilbud', // Norweski
                'pl' => 'Szablony CV dla ofert pracy', // Polski
                'ps' => 'د کار وړاندیزونو لپاره CV ټیمپلیټونه', // Paszto
                'pt' => 'Modelos de CV para ofertas de emprego', // Portugalski
                'ro' => 'Șabloane CV pentru oferte de muncă', // Rumuński
                'ru' => 'Шаблоны резюме для вакансий', // Rosyjski
                'si' => 'රැකියා යෝජනා සඳහා CV ආකෘති', // Syngaleski
                'sk' => 'Šablóny životopisov pre pracovné ponuky', // Słowacki
                'sl' => 'CV predloge za delovne ponudbe', // Słoweński
                'sq' => 'Shabllone CV për oferta pune', // Albański
                'sr' => 'CV predlošci za ponude za posao', // Serbski
                'sv' => 'CV-mallar för jobberbjudanden', // Szwedzki
                'tg' => 'CV шоҳидҳо барои пешниҳодҳои кор', // Tadżycki
                'th' => 'เทมเพลต CV สำหรับข้อเสนอการงาน', // Tajski
                'tk' => 'Iş təklifləri üçün CV şablonları', // Turkmeński
                'tr' => 'İş teklifleri için CV şablonları', // Turecki
                'uk' => 'Шаблони резюме для вакансій', // Ukraiński
                'uz' => 'Ish takliflari uchun CV shablonlari', // Uzbecki
                'vi' => 'Mẫu CV cho các cơ hội việc làm', // Wietnamski
                'zh' => '职位申请模板简历', // Chiński
            ])
        ]);
        $p18 = Permission::create([
            'name' => 'sharing projects on other platforms',
            'trans' => json_encode([
                'am' => 'ፕሮጀክቶችን በሌላ መድረኮች ላይ ማጋራት', // Amharski
                'ar' => 'مشاركة المشاريع على منصات أخرى', // Arabski
                'az' => 'Layihələri digər platformalarda paylaşmaq', // Azerski
                'be' => 'Падзяліцца праектамі на іншых платформах', // Białoruski
                'bg' => 'Споделяне на проекти на други платформи', // Bułgarski
                'bn' => 'অন্যান্য প্ল্যাটফর্মে প্রকল্প শেয়ার করা', // Bengalski
                'bs' => 'Dijeljenje projekata na drugim platformama', // Bośniacki
                'ca' => 'Compartir projectes en altres plataformes', // Kataloński
                'cs' => 'Sdílení projektů na jiných platformách', // Czeski
                'da' => 'Deling af projekter på andre platforme', // Duński
                'de' => 'Projekte auf anderen Plattformen teilen', // Niemiecki
                'dv' => 'ޕްރޮޖެކިޓޯރ ތްރެކް ޝަކާ ގިން ކުންށް', // Divehi
                'dz' => 'བྱ་སོར་འབྲེལ་ཡོད།', // Dzongkha
                'el' => 'Μοιραστείτε έργα σε άλλες πλατφόρμες', // Grecki
                'en' => 'Sharing projects on other platforms', // Angielski
                'es' => 'Compartir proyectos en otras plataformas', // Hiszpański
                'et' => 'Projektide jagamine teistel platvormidel', // Estoński
                'fa' => 'به اشتراک گذاری پروژه‌ها در پلتفرم‌های دیگر', // Perski
                'fi' => 'Projektien jakaminen muilla alustoilla', // Fiński
                'fr' => 'Partager des projets sur d\'autres plateformes', // Francuski
                'he' => 'שיתוף פרויקטים בפלטפורמות אחרות', // Hebrajski
                'hi' => 'अन्य प्लेटफार्मों पर परियोजनाओं को साझा करना', // Hindi
                'hr' => 'Dijeljenje projekata na drugim platformama', // Chorwacki
                'hu' => 'Projektek megosztása más platformokon', // Węgierski
                'hy' => 'Հավաքել նախագծեր այլ հարթակներում', // Ormiański
                'id' => 'Berbagi proyek di platform lain', // Indonezyjski
                'is' => 'Deila verkefni á öðrum pöllum', // Islandzki
                'it' => 'Condividere progetti su altre piattaforme', // Włoski
                'ja' => '他のプラットフォームでプロジェクトを共有する', // Japoński
                'ka' => 'პროექტების გაზიარება სხვა პლატფორმებზე', // Gruziński
                'km' => 'ចែករំលែកគម្រោងនៅលើផ្លាតហ្វ័រមានផ្សេងទៀត', // Khmerski
                'ko' => '다른 플랫폼에서 프로젝트 공유', // Koreański
                'lb' => 'Projekter deelen op anere Plattformen', // Luksemburski
                'lo' => 'ການແບ່ງປັນງານຜົນງານຢູ່ກັບພລັດເຟອມອື່ນ', // Laotański
                'lt' => 'Projektų dalijimasis kitose platformose', // Litewski
                'lv' => 'Projektu kopīgošana citās platformās', // Łotewski
                'me' => 'Podijelite projekte na drugim platformama', // Czarnogórski
                'mk' => 'Споделување на проекти на други платформи', // Macedoński
                'mn' => 'Төсөлүүдийг бусад платформ дээр хуваалцах', // Mongołski
                'ms' => 'Kongsi projek di platform lain', // Malajski
                'my' => 'ပရောဂျက်များကို အခြား ပလက်ဖောင်းများတွင် မျှဝေရန်', // Birmański
                'ne' => 'अन्य प्लेटफार्महरूमा परियोजनाहरू साझेदारी गर्नुहोस्', // Nepalski
                'nl' => 'Projecten delen op andere platforms', // Holenderski
                'no' => 'Dele prosjekter på andre plattformer', // Norweski
                'pl' => 'Udostępnianie projektów na innych platformach', // Polski
                'ps' => 'پر نورو پلاتفورمونو کې پروژې شریکول', // Paszto
                'pt' => 'Compartilhar projetos em outras plataformas', // Portugalski
                'ro' => 'Partajarea proiectelor pe alte platforme', // Rumuński
                'ru' => 'Делиться проектами на других платформах', // Rosyjski
                'si' => 'වෙනත් මංසන්ධිවල ව්‍යාපෘති බෙදා හරිනු', // Syngaleski
                'sk' => 'Zdieľanie projektov na iných platformách', // Słowacki
                'sl' => 'Deljenje projektov na drugih platformah', // Słoweński
                'sq' => 'Ndaj projektet në platforma të tjera', // Albański
                'sr' => 'Deljenje projekata na drugim platformama', // Serbski
                'sv' => 'Dela projekt på andra plattformar', // Szwedzki
                'tg' => 'Пайванд кардани лоиҳаҳо дар дигар платформаҳо', // Tadżycki
                'th' => 'แชร์โครงการบนแพลตฟอร์มอื่น', // Tajski
                'tk' => 'Başqa platformalarda layihələri paylaşmak', // Turkmeński
                'tr' => 'Diğer platformlarda projeleri paylaşmak', // Turecki
                'uk' => 'Ділення проектами на інших платформах', // Ukraiński
                'uz' => 'Boshqa platformalarda loyihalarni ulashish', // Uzbecki
                'vi' => 'Chia sẻ dự án trên các nền tảng khác', // Wietnamski
                'zh' => '在其他平台上分享项目' // Chiński
            ])
        ]);


        $recruit->givePermissionTo([$p1,$p2,$p3,$p9,$p10,$p11,$p12,$p13,$p14,$p15,$p16,$p17,$p18]);


        Schema::enableForeignKeyConstraints();
    }
}
