<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class WelcomeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('welcomes')->truncate();

        $welcomes = [
            [
                'id' => 1,
                'name' => json_encode([
                    'am' => 'የኢንዱስትሪ ማረጋገጫዎች', // Amharski
                    'ar' => 'شهادات الصناعة', // Arabski
                    'az' => 'Sənaye sertifikatları', // Azerski
                    'be' => 'Прамысловыя сертыфікаты', // Białoruski
                    'bg' => 'Индустриални сертификати', // Bułgarski
                    'bn' => 'শিল্প শংসাপত্র', // Bengalski
                    'bs' => 'Industrijski certifikati', // Bośniacki
                    'ca' => 'Certificats industrials', // Kataloński
                    'cs' => 'Průmyslové certifikáty', // Czeski
                    'da' => 'Industrielle certifikater', // Duński
                    'de' => 'Industriezertifikate', // Niemiecki
                    'dv' => 'އިންޑަސްޓްރީ ސަރޓިފިކެޓްތަކުން', // Divehi (Malediwy)
                    'dz' => 'རིགས་ལུགས་སྤྱོད་མཁན་ཐོ་ཡིག', // Dzongkha (Bhutan)
                    'el' => 'Βιομηχανικά πιστοποιητικά', // Grecki
                    'en' => 'Industry certificates', // Angielski
                    'es' => 'Certificados de la industria', // Hiszpański
                    'et' => 'Tööstussertifikaadid', // Estoński
                    'fa' => 'گواهینامه‌های صنعتی', // Perski
                    'fi' => 'Teollisuuden sertifikaatit', // Fiński
                    'fr' => 'Certificats industriels', // Francuski
                    'he' => 'תעודות תעשייה', // Hebrajski
                    'hi' => 'उद्योग प्रमाणपत्र', // Hindi
                    'hr' => 'Industrijski certifikati', // Chorwacki
                    'hu' => 'Ipari tanúsítványok', // Węgierski
                    'hy' => 'Արդյունաբերական սերտիֆիկատներ', // Ormiański
                    'id' => 'Sertifikat industri', // Indonezyjski
                    'is' => 'Iðnaðarvottorð', // Islandzki
                    'it' => 'Certificati industriali', // Włoski
                    'ja' => '業界認定証', // Japoński
                    'ka' => 'სამრეწველო სერტიფიკატები', // Gruziński
                    'km' => 'វិញ្ញាបនបត្រឧស្សាហកម្ម', // Khmerski
                    'ko' => '산업 인증서', // Koreański
                    'lb' => 'Industrie Zertifikater', // Luksemburski
                    'lo' => 'ໃບຢັ້ງຢືນອຸດສາຫະກໍາ', // Laotański
                    'lt' => 'Pramonės sertifikatai', // Litewski
                    'lv' => 'Nozares sertifikāti', // Łotewski
                    'me' => 'Industrijski certifikati', // Czarnogórski
                    'mk' => 'Индустриски сертификати', // Macedoński
                    'mn' => 'Салбарын гэрчилгээ', // Mongołski
                    'ms' => 'Sijil industri', // Malajski
                    'my' => 'စက်မှုလက်မှတ်', // Birmański
                    'ne' => 'उद्योग प्रमाणपत्रहरू', // Nepalski
                    'nl' => 'Industriecertificaten', // Holenderski
                    'no' => 'Industrielle sertifikater', // Norweski
                    'pl' => 'Certyfikaty branżowe', // Polski
                    'ps' => 'د صنعت سندونه', // Paszto
                    'pt' => 'Certificados industriais', // Portugalski
                    'ro' => 'Certificate industriale', // Rumuński
                    'ru' => 'Промышленные сертификаты', // Rosyjski
                    'si' => 'කාර්මික සහතික', // Syngaleski
                    'sk' => 'Priemyselné certifikáty', // Słowacki
                    'sl' => 'Industrijski certifikati', // Słoweński
                    'sq' => 'Certifikata të industrisë', // Albański
                    'sr' => 'Индустријски сертификати', // Serbski
                    'sv' => 'Industricertifikat', // Szwedzki
                    'tg' => 'Шаҳодатномаҳои саноатӣ', // Tadżycki
                    'th' => 'ใบรับรองอุตสาหกรรม', // Tajski
                    'tk' => 'Senagat şahadatnamalary', // Turkmeński
                    'tr' => 'Endüstri sertifikaları', // Turecki
                    'uk' => 'Промислові сертифікати', // Ukraiński
                    'uz' => 'Sanoat sertifikatlari', // Uzbecki
                    'vi' => 'Chứng chỉ ngành', // Wietnamski
                    'zh' => '行业认证' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 2,
                'name' => json_encode([
                    'am' => 'የድህረ ምረቃ ትምህርቶች ወይም ተጨማሪ የስራ ስልጠናዎች', // Amharski
                    'ar' => 'الدراسات العليا أو الدورات المهنية الإضافية', // Arabski
                    'az' => 'Məzun tədqiqatları və ya əlavə peşə kursları', // Azerski
                    'be' => 'Аспірантура або дадатковыя курсы', // Białoruski
                    'bg' => 'Следдипломна квалификация или допълнителни професионални курсове', // Bułgarski
                    'bn' => 'স্নাতকোত্তর অধ্যয়ন বা অতিরিক্ত পেশাদার কোর্স', // Bengalski
                    'bs' => 'Postdiplomske studije ili dodatni stručni kursevi', // Bośniacki
                    'ca' => 'Estudis de postgrau o cursos professionals addicionals', // Kataloński
                    'cs' => 'Postgraduální studium nebo další odborné kurzy', // Czeski
                    'da' => 'Efteruddannelse eller yderligere branchekurser', // Duński
                    'de' => 'Aufbaustudium oder zusätzliche Fachkurse', // Niemiecki
                    'dv' => 'ޕޯސްޓްގުރޭޑު ސްޓަޑީތައް ނުވަތަ އައު ސަރުކުރުންގެ ކޯސްތައް', // Divehi
                    'dz' => 'ངོས་རྟགས་བཟོ་རྒྱུ་ནང་དུ་མགོ་མཐུན་ཞུགས་རོགས་སྤྱོད་', // Dzongkha
                    'el' => 'Μεταπτυχιακές σπουδές ή επιπλέον επαγγελματικά μαθήματα', // Grecki
                    'en' => 'Postgraduate studies or additional professional courses', // Angielski
                    'es' => 'Estudios de posgrado o cursos profesionales adicionales', // Hiszpański
                    'et' => 'Magistriõpe või täiendavad erialakursused', // Estoński
                    'fa' => 'تحصیلات تکمیلی یا دوره‌های حرفه‌ای اضافی', // Perski
                    'fi' => 'Jatko-opinnot tai lisäammattikurssit', // Fiński
                    'fr' => 'Études de troisième cycle ou cours professionnels supplémentaires', // Francuski
                    'he' => 'לימודים לתארים מתקדמים או קורסים מקצועיים נוספים', // Hebrajski
                    'hi' => 'स्नातकोत्तर अध्ययन या अतिरिक्त व्यावसायिक पाठ्यक्रम', // Hindi
                    'hr' => 'Poslijediplomski studiji ili dodatni stručni tečajevi', // Chorwacki
                    'hu' => 'Posztgraduális tanulmányok vagy további szakmai kurzusok', // Węgierski
                    'hy' => 'Հետդիպլոմային կրթություն կամ լրացուցիչ մասնագիտական դասընթացներ', // Ormiański
                    'id' => 'Studi pascasarjana atau kursus profesional tambahan', // Indonezyjski
                    'is' => 'Framhaldsnám eða viðbótarnámskeið', // Islandzki
                    'it' => 'Studi post-laurea o corsi professionali aggiuntivi', // Włoski
                    'ja' => '大学院の研究または追加の専門コース', // Japoński
                    'ka' => 'ასპირანტურა ან დამატებითი პროფესიული კურსები', // Gruziński
                    'km' => 'ការសិក្សាជាន់ខ្ពស់ឬវគ្គសិក្សាផ្នែកវិជ្ជាជីវៈបន្ថែម', // Khmerski
                    'ko' => '대학원 공부 또는 추가 전문 과정', // Koreański
                    'lb' => 'Postgradual Studien oder zousätzlech Fachcoursen', // Luksemburski
                    'lo' => 'ສຶກສາຂະແໜງພິເສດຫຼືຄອສວິຊາຊີບເພີ່ມເຕີມ', // Laotański
                    'lt' => 'Magistrantūra arba papildomi profesiniai kursai', // Litewski
                    'lv' => 'Pēcdiploma studijas vai papildu profesionālie kursi', // Łotewski
                    'me' => 'Postdiplomske studije ili dodatni stručni kursevi', // Czarnogórski
                    'mk' => 'Постдипломски студии или дополнителни професионални курсеви', // Macedoński
                    'mn' => 'Магистрын судалгаа эсвэл нэмэлт мэргэжлийн сургалтууд', // Mongołski
                    'ms' => 'Pengajian pascasiswazah atau kursus profesional tambahan', // Malajski
                    'my' => 'ဘွဲ့လွန် သင်ကြားမှု သို့မဟုတ် ထပ်တိုးမော်ကွန်းသင်တန်းများ', // Birmański
                    'ne' => 'स्नातकोत्तर अध्ययन वा अतिरिक्त व्यावसायिक पाठ्यक्रमहरू', // Nepalski
                    'nl' => 'Postdoctorale studies of aanvullende vakcursussen', // Holenderski
                    'no' => 'Videreutdanning eller tilleggskurs', // Norweski
                    'pl' => 'Studia podyplomowe lub dodatkowe kursy branżowe', // Polski
                    'ps' => 'د ماسټرۍ زده کړې یا اضافي مسلکي کورسونه', // Paszto
                    'pt' => 'Estudos de pós-graduação ou cursos profissionais adicionais', // Portugalski
                    'ro' => 'Studii postuniversitare sau cursuri profesionale suplimentare', // Rumuński
                    'ru' => 'Аспирантура или дополнительные профессиональные курсы', // Rosyjski
                    'si' => 'පශ්චාත් උපාධි අධ්‍යාපන හෝ අමතර වෘත්තීය පාඨමාලා', // Syngaleski
                    'sk' => 'Postgraduálne štúdium alebo ďalšie odborné kurzy', // Słowacki
                    'sl' => 'Podiplomski študij ali dodatni strokovni tečaji', // Słoweński
                    'sq' => 'Studime pasuniversitare ose kurse shtesë profesionale', // Albański
                    'sr' => 'Постдипломске студије или додатни стручни курсеви', // Serbski
                    'sv' => 'Postgraduate studier eller ytterligare yrkeskurser', // Szwedzki
                    'tg' => 'Таҳсилоти баъдидипломӣ ё курсҳои касбии иловагӣ', // Tadżycki
                    'th' => 'การศึกษาระดับบัณฑิตศึกษา หรือหลักสูตรวิชาชีพเพิ่มเติม', // Tajski
                    'tk' => 'Aspirantura ýa-da goşmaça hünär kurslary', // Turkmeński
                    'tr' => 'Lisansüstü eğitim veya ek meslek kursları', // Turecki
                    'uk' => 'Аспірантура або додаткові професійні курси', // Ukraiński
                    'uz' => 'Aspirantura yoki qo‘shimcha kasbiy kurslar', // Uzbecki
                    'vi' => 'Học sau đại học hoặc các khóa học chuyên nghiệp bổ sung', // Wietnamski
                    'zh' => '研究生学习或额外的专业课程' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 3,
                'name' => json_encode([
                    'am' => 'የሁለተኛ ቋንቋ ዕውቀት', // Amharski
                    'ar' => 'إتقان لغة أجنبية ثانية', // Arabski
                    'az' => 'İkinci xarici dili bilmək', // Azerski
                    'be' => 'Веданне другой замежнай мовы', // Białoruski
                    'bg' => 'Владеене на втори чужд език', // Bułgarski
                    'bn' => 'দ্বিতীয় বিদেশী ভাষার জ্ঞান', // Bengalski
                    'bs' => 'Poznavanje drugog stranog jezika', // Bośniacki
                    'ca' => 'Coneixement d’un segon idioma estranger', // Kataloński
                    'cs' => 'Znalost druhého cizího jazyka', // Czeski
                    'da' => 'Kendskab til et andet fremmedsprog', // Duński
                    'de' => 'Kenntnisse einer zweiten Fremdsprache', // Niemiecki
                    'dv' => 'ނުވަތަ ތެރުވި ބަދަލުގެ ނިންމައަށް', // Divehi
                    'dz' => 'ཕྱི་མི་སྐད་ཡག་དག་ཚན་བཟོ་ནི', // Dzongkha
                    'el' => 'Γνώση δεύτερης ξένης γλώσσας', // Grecki
                    'en' => 'Knowledge of a second foreign language', // Angielski
                    'es' => 'Conocimiento de un segundo idioma extranjero', // Hiszpański
                    'et' => 'Teise võõrkeele oskus', // Estoński
                    'fa' => 'آشنایی با زبان خارجی دوم', // Perski
                    'fi' => 'Toisen vieraan kielen taito', // Fiński
                    'fr' => 'Connaissance d’une deuxième langue étrangère', // Francuski
                    'he' => 'ידע בשפה זרה שנייה', // Hebrajski
                    'hi' => 'दूसरी विदेशी भाषा का ज्ञान', // Hindi
                    'hr' => 'Poznavanje drugog stranog jezika', // Chorwacki
                    'hu' => 'Második idegen nyelv ismerete', // Węgierski
                    'hy' => 'Երկրորդ օտար լեզվի իմացություն', // Ormiański
                    'id' => 'Pengetahuan tentang bahasa asing kedua', // Indonezyjski
                    'is' => 'Þekking á öðru erlendu tungumáli', // Islandzki
                    'it' => 'Conoscenza di una seconda lingua straniera', // Włoski
                    'ja' => '第二外国語の知識', // Japoński
                    'ka' => 'მეორე უცხო ენის ცოდნა', // Gruziński
                    'km' => 'ចំណេះដឹងភាសាបរទេសទីពីរ', // Khmerski
                    'ko' => '두 번째 외국어 지식', // Koreański
                    'lb' => 'Wësse vun enger zweeter Friemsprooch', // Luksemburski
                    'lo' => 'ຄວາມຮູ້ຄວາມສາມາດໃນພາສາຕ່າງປະເທດທີສອງ', // Laotański
                    'lt' => 'Antrosios užsienio kalbos žinios', // Litewski
                    'lv' => 'Otrās svešvalodas zināšanas', // Łotewski
                    'me' => 'Poznavanje drugog stranog jezika', // Czarnogórski
                    'mk' => 'Познавање на втор странски јазик', // Macedoński
                    'mn' => 'Хоёр дахь гадаад хэлийг мэдэх', // Mongołski
                    'ms' => 'Pengetahuan bahasa asing kedua', // Malajski
                    'my' => 'ဒုတိယ နိုင်ငံခြားဘာသာစကား၏ အတတ်ရည်', // Birmański
                    'ne' => 'दोस्रो विदेशी भाषाको ज्ञान', // Nepalski
                    'nl' => 'Kennis van een tweede vreemde taal', // Holenderski
                    'no' => 'Kunnskap om et annet fremmedspråk', // Norweski
                    'pl' => 'Znajomość drugiego języka obcego', // Polski
                    'ps' => 'د دوهم بهرني ژبې پوهه', // Paszto
                    'pt' => 'Conhecimento de um segundo idioma estrangeiro', // Portugalski
                    'ro' => 'Cunoașterea unei a doua limbi străine', // Rumuński
                    'ru' => 'Знание второго иностранного языка', // Rosyjski
                    'si' => 'දෙවන විදෙස් භාෂාවක නුවණ', // Syngaleski
                    'sk' => 'Znalosť druhého cudzieho jazyka', // Słowacki
                    'sl' => 'Znanje drugega tujega jezika', // Słoweński
                    'sq' => 'Njohja e një gjuhe të dytë të huaj', // Albański
                    'sr' => 'Познавање другог страног језика', // Serbski
                    'sv' => 'Kunskap om ett andra främmande språk', // Szwedzki
                    'tg' => 'Донистани забони дувуми хориҷӣ', // Tadżycki
                    'th' => 'ความรู้ภาษาต่างประเทศที่สอง', // Tajski
                    'tk' => 'Ikinji daşary ýurt dilini bilmek', // Turkmeński
                    'tr' => 'İkinci bir yabancı dili bilmek', // Turecki
                    'uk' => 'Знання другої іноземної мови', // Ukraiński
                    'uz' => 'Ikkinchi chet tilini bilish', // Uzbecki
                    'vi' => 'Kiến thức về ngôn ngữ nước ngoài thứ hai', // Wietnamski
                    'zh' => '掌握第二外语' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 4,
                'name' => json_encode([
                    'am' => 'በተመሳሳይ ክፍለ ሥራ የሥራ ልምድ', // Amharski
                    'ar' => 'الخبرة في العمل في منصب مماثل', // Arabski
                    'az' => 'Oxşar vəzifədə iş təcrübəsi', // Azerski
                    'be' => 'Вопыт працы на аналагічнай пасадзе', // Białoruski
                    'bg' => 'Опит в работа на подобна позиция', // Bułgarski
                    'bn' => 'সদৃশ পদে কাজ করার অভিজ্ঞতা', // Bengalski
                    'bs' => 'Iskustvo u radu na sličnoj poziciji', // Bośniacki
                    'ca' => 'Experiència en treballar en una posició similar', // Kataloński
                    'cs' => 'Zkušenosti s prací na podobné pozici', // Czeski
                    'da' => 'Erfaring med at arbejde i en lignende stilling', // Duński
                    'de' => 'Erfahrung in einer ähnlichen Position', // Niemiecki
                    'dv' => 'އައުތަކުގެ ބަދަލު ދަނޑުގައި ބަލަކުން ސަބަބަށް', // Divehi
                    'dz' => 'མཚམས་གཉིས་ལ་གནས་ལུགས་ཅན་བཟོ་བཅོས་མཛོད་པ', // Dzongkha
                    'el' => 'Εμπειρία σε εργασία σε παρόμοια θέση', // Grecki
                    'en' => 'Experience working in a similar position', // Angielski
                    'es' => 'Experiencia trabajando en un puesto similar', // Hiszpański
                    'et' => 'Kogemus töötamisel sarnasel ametikohal', // Estoński
                    'fa' => 'تجربه کار در موقعیت مشابه', // Perski
                    'fi' => 'Kokemus työskentelystä samankaltaisessa tehtävässä', // Fiński
                    'fr' => 'Expérience de travail dans un poste similaire', // Francuski
                    'he' => 'ניסיון בעבודה בתפקיד דומה', // Hebrajski
                    'hi' => 'समान पद पर काम करने का अनुभव', // Hindi
                    'hr' => 'Iskustvo u radu na sličnoj poziciji', // Chorwacki
                    'hu' => 'Tapasztalat hasonló munkakörben', // Węgierski
                    'hy' => 'Փորձ նման պաշտոնում աշխատելու', // Ormiański
                    'id' => 'Pengalaman bekerja di posisi serupa', // Indonezyjski
                    'is' => 'Reynsla af vinnu í svipaðri stöðu', // Islandzki
                    'it' => 'Esperienza di lavoro in una posizione simile', // Włoski
                    'ja' => '類似の職位での勤務経験', // Japoński
                    'ka' => 'მუშაობის გამოცდილება მსგავს თანამდებობაზე', // Gruziński
                    'km' => 'បទពិសោធន៍ការងារនៅតំណែងស្រដៀងกัน', // Khmerski
                    'ko' => '유사한 직책에서의 근무 경험', // Koreański
                    'lb' => 'Erfahrung an enger ähnlecher Positioun', // Luksemburski
                    'lo' => 'ປະສົບການໃນການເຮັດວຽກໃນຕຳແໜ່ງທີ່ຄ້າຍຄືກັນ', // Laotański
                    'lt' => 'Darbo patirtis panašioje pozicijoje', // Litewski
                    'lv' => 'Pieredze darbā līdzīgā amatā', // Łotewski
                    'me' => 'Iskustvo u radu na sličnoj poziciji', // Czarnogórski
                    'mk' => 'Искуство во работа на слична позиција', // Macedoński
                    'mn' => 'Төстэй албан тушаал дээр ажилласан туршлага', // Mongołski
                    'ms' => 'Pengalaman bekerja di jawatan yang sama', // Malajski
                    'my' => 'တူညီသောရာထူးတွင်လုပ်ကိုင်မှုအတွေ့အကြုံ', // Birmański
                    'ne' => 'समान पदमा काम गर्ने अनुभव', // Nepalski
                    'nl' => 'Ervaring in een vergelijkbare functie', // Holenderski
                    'no' => 'Erfaring med arbeid i en lignende stilling', // Norweski
                    'pl' => 'Doświadczenie w pracy na podobnym stanowisku', // Polski
                    'ps' => 'په ورته مقام کې د کار تجربه', // Paszto
                    'pt' => 'Experiência de trabalho em uma posição semelhante', // Portugalski
                    'ro' => 'Experiență de lucru într-o poziție similară', // Rumuński
                    'ru' => 'Опыт работы на аналогичной должности', // Rosyjski
                    'si' => 'එමන තනතුරක වැඩ කිරීමේ අත්දැකීම්', // Syngaleski
                    'sk' => 'Skúsenosti s prácou na podobnej pozícii', // Słowacki
                    'sl' => 'Izkušnje z delom na podobnem položaju', // Słoweński
                    'sq' => 'Përvoja e punës në një pozitë të ngjashme', // Albański
                    'sr' => 'Искуство у раду на сличној позицији', // Serbski
                    'sv' => 'Erfarenhet av arbete i en liknande position', // Szwedzki
                    'tg' => 'Таҷрибаи кор дар мансаби шабеҳ', // Tadżycki
                    'th' => 'ประสบการณ์การทำงานในตำแหน่งที่คล้ายกัน', // Tajski
                    'tk' => 'Meňzeş wezipede iş tejribesi', // Turkmeński
                    'tr' => 'Benzer bir pozisyonda çalışma deneyimi', // Turecki
                    'uk' => 'Досвід роботи на аналогічній посаді', // Ukraiński
                    'uz' => 'O‘xshash lavozimda ishlash tajribasi', // Uzbecki
                    'vi' => 'Kinh nghiệm làm việc ở vị trí tương tự', // Wietnamski
                    'zh' => '在类似职位上的工作经验' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 5,
                'name' => json_encode([
                    'am' => 'የሥራ አስፈላጊ ስርዓቶችን እና ፕሮግራሞችን የማወቅ', // Amharski
                    'ar' => 'معرفة الأنظمة والبرامج الخاصة بالصناعة', // Arabski
                    'az' => 'Sənaye sistemləri və proqramlarını bilmək', // Azerski
                    'be' => 'Веданне сістэм і праграм галіны', // Białoruski
                    'bg' => 'Познанства със системите и програмите на индустрията', // Bułgarski
                    'bn' => 'শিল্প সম্পর্কিত সিস্টেম এবং প্রোগ্রামগুলির জ্ঞান', // Bengalski
                    'bs' => 'Poznavanje sistema i programa industrije', // Bośniacki
                    'ca' => 'Coneixement dels sistemes i programes de la indústria', // Kataloński
                    'cs' => 'Znalost systémů a programů v oboru', // Czeski
                    'da' => 'Kendskab til branchens systemer og programmer', // Duński
                    'de' => 'Kenntnisse der Systeme und Programme der Branche', // Niemiecki
                    'dv' => 'އިންދަތަކަށް ހަދިޔާރުވުރެއްދުވި ސިސްޓެމްތައް ނުވަތަ ޕްރޮގްރަމްތައް', // Divehi
                    'dz' => 'ཁྲིམས་རིམ་དང་གནས་སྟངས་བཟོ་བཅོས་ནི་ལུ་དེ་རྟོགས་ཡོད་པ།', // Dzongkha
                    'el' => 'Γνώση συστημάτων και προγραμμάτων του κλάδου', // Grecki
                    'en' => 'Knowledge of industry systems and programs', // Angielski
                    'es' => 'Conocimiento de sistemas y programas de la industria', // Hiszpański
                    'et' => 'Tööstussüsteemide ja -programmide tundmine', // Estoński
                    'fa' => 'آشنایی با سیستم‌ها و برنامه‌های صنعت', // Perski
                    'fi' => 'Alan järjestelmien ja ohjelmien tuntemus', // Fiński
                    'fr' => 'Connaissance des systèmes et programmes de l’industrie', // Francuski
                    'he' => 'ידע במערכות ותוכנות תעשייתיות', // Hebrajski
                    'hi' => 'उद्योग प्रणाली और कार्यक्रमों का ज्ञान', // Hindi
                    'hr' => 'Poznavanje sustava i programa u industriji', // Chorwacki
                    'hu' => 'Iparági rendszerek és programok ismerete', // Węgierski
                    'hy' => 'Ոլորտի համակարգերի և ծրագրերի իմացություն', // Ormiański
                    'id' => 'Pengetahuan tentang sistem dan program industri', // Indonezyjski
                    'is' => 'Þekking á kerfum og forritum í greininni', // Islandzki
                    'it' => 'Conoscenza dei sistemi e dei programmi di settore', // Włoski
                    'ja' => '業界システムとプログラムの知識', // Japoński
                    'ka' => 'ინდუსტრიული სისტემების და პროგრამების ცოდნა', // Gruziński
                    'km' => 'ចំណេះដឹងអំពីប្រព័ន្ធ និងកម្មវិធីឧស្សាហកម្ម', // Khmerski
                    'ko' => '산업 시스템 및 프로그램에 대한 지식', // Koreański
                    'lb' => 'Wëssen iwwer Systemer a Programmer aus der Industrie', // Luksemburski
                    'lo' => 'ຄວາມຮູ້ກ່ຽວກັບລະບົບ ແລະໂຄງການຂອງອຸດສາຫະກໍາ', // Laotański
                    'lt' => 'Pramonės sistemų ir programų žinios', // Litewski
                    'lv' => 'Nozares sistēmu un programmu zināšanas', // Łotewski
                    'me' => 'Poznavanje sistema i programa u industriji', // Czarnogórski
                    'mk' => 'Познавање на системи и програми во индустријата', // Macedoński
                    'mn' => 'Үйлдвэрийн систем, хөтөлбөрийн мэдлэг', // Mongołski
                    'ms' => 'Pengetahuan tentang sistem dan program industri', // Malajski
                    'my' => 'စက်မှုဇုန်စနစ်များနှင့်အစီအစဉ်များ၏အသိပညာ', // Birmański
                    'ne' => 'उद्योग प्रणाली र कार्यक्रमहरूको ज्ञान', // Nepalski
                    'nl' => 'Kennis van systemen en programma\'s uit de industrie', // Holenderski
                    'no' => 'Kunnskap om systemer og programmer i industrien', // Norweski
                    'pl' => 'Znajomość systemów i programów branżowych', // Polski
                    'ps' => 'د صنعت سیسټمونو او پروګرامونو پوهه', // Paszto
                    'pt' => 'Conhecimento de sistemas e programas da indústria', // Portugalski
                    'ro' => 'Cunoștințe despre sistemele și programele industriei', // Rumuński
                    'ru' => 'Знание систем и программ отрасли', // Rosyjski
                    'si' => 'ඉංජිනේරු පද්ධති සහ වැඩසටහන් පිළිබඳ අවබෝධය', // Syngaleski
                    'sk' => 'Znalosť systémov a programov v odvetví', // Słowacki
                    'sl' => 'Poznavanje sistemov in programov v industriji', // Słoweński
                    'sq' => 'Njohuri mbi sistemet dhe programet e industrisë', // Albański
                    'sr' => 'Познавање система и програма у индустрији', // Serbski
                    'sv' => 'Kunskap om system och program inom branschen', // Szwedzki
                    'tg' => 'Донистани системаҳо ва барномаҳои соҳа', // Tadżycki
                    'th' => 'ความรู้เกี่ยวกับระบบและโปรแกรมในอุตสาหกรรม', // Tajski
                    'tk' => 'Senagat ulgamlaryny we programmalaryny bilmek', // Turkmeński
                    'tr' => 'Endüstri sistemleri ve programları bilgisi', // Turecki
                    'uk' => 'Знання систем і програм галузі', // Ukraiński
                    'uz' => 'Sanoat tizimlari va dasturlarini bilish', // Uzbecki
                    'vi' => 'Kiến thức về hệ thống và chương trình ngành', // Wietnamski
                    'zh' => '行业系统和程序的知识' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 6,
                'name' => json_encode([
                    'am' => 'በዘመናዊ ቴክኖሎጂዎች ላይ ፍላጎት', // Amharski
                    'ar' => 'الاهتمام بالتكنولوجيا الحديثة', // Arabski
                    'az' => 'Müasir texnologiyalara maraq', // Azerski
                    'be' => 'Інтарэс да сучасных тэхналогій', // Białoruski
                    'bg' => 'Интерес към съвременните технологии', // Bułgarski
                    'bn' => 'আধুনিক প্রযুক্তির প্রতি আগ্রহ', // Bengalski
                    'bs' => 'Interes za savremene tehnologije', // Bośniacki
                    'ca' => 'Interès per les tecnologies modernes', // Kataloński
                    'cs' => 'Zájem o moderní technologie', // Czeski
                    'da' => 'Interesse for moderne teknologi', // Duński
                    'de' => 'Interesse an modernen Technologien', // Niemiecki
                    'dv' => 'އައުބަލަށްވަރު ޓެކްނޮލޮޖީތަކަށް ތަޢާރަފުޅޭ', // Divehi
                    'dz' => 'མདོང་དུ་དམངས་གསར་གསར་མའི་ཐོན་རིམ་གཅིག་དགོས་པ', // Dzongkha
                    'el' => 'Ενδιαφέρον για τις σύγχρονες τεχνολογίες', // Grecki
                    'en' => 'Interest in modern technologies', // Angielski
                    'es' => 'Interés por las tecnologías modernas', // Hiszpański
                    'et' => 'Huvi kaasaegsete tehnoloogiate vastu', // Estoński
                    'fa' => 'علاقه‌مندی به فناوری‌های مدرن', // Perski
                    'fi' => 'Kiinnostus nykyaikaisiin teknologioihin', // Fiński
                    'fr' => 'Intérêt pour les technologies modernes', // Francuski
                    'he' => 'עניין בטכנולוגיות חדשות', // Hebrajski
                    'hi' => 'आधुनिक तकनीकों में रुचि', // Hindi
                    'hr' => 'Interes za moderne tehnologije', // Chorwacki
                    'hu' => 'Érdeklődés a modern technológiák iránt', // Węgierski
                    'hy' => 'Հետաքրքրություն ժամանակակից տեխնոլոգիաների նկատմամբ', // Ormiański
                    'id' => 'Minat pada teknologi modern', // Indonezyjski
                    'is' => 'Áhugi á nútímatækni', // Islandzki
                    'it' => 'Interesse per le tecnologie moderne', // Włoski
                    'ja' => '最新技術への関心', // Japoński
                    'ka' => 'თანამედროვე ტექნოლოგიებით დაინტერესება', // Gruziński
                    'km' => 'ការចាប់អារម្មណ៍លើបច្ចេកវិទ្យាទំនើប', // Khmerski
                    'ko' => '최신 기술에 대한 관심', // Koreański
                    'lb' => 'Interesse un moderne Technologien', // Luksemburski
                    'lo' => 'ຄວາມສົນໃຈໃນເຕັກໂນໂລຢສະໄໝ', // Laotański
                    'lt' => 'Susidomėjimas šiuolaikinėmis technologijomis', // Litewski
                    'lv' => 'Interese par modernajām tehnoloģijām', // Łotewski
                    'me' => 'Interesovanje za moderne tehnologije', // Czarnogórski
                    'mk' => 'Интерес за современите технологии', // Macedoński
                    'mn' => 'Орчин үеийн технологид сонирхолтой', // Mongołski
                    'ms' => 'Minat terhadap teknologi moden', // Malajski
                    'my' => 'ခေတ်မီနည်းပညာများအပေါ်စိတ်ဝင်စားမှု', // Birmański
                    'ne' => 'आधुनिक प्रविधिमा चासो', // Nepalski
                    'nl' => 'Interesse in moderne technologieën', // Holenderski
                    'no' => 'Interesse for moderne teknologier', // Norweski
                    'pl' => 'Zainteresowanie nowoczesnymi technologiami', // Polski
                    'ps' => 'په عصري ټکنالوژیو کې علاقه', // Paszto
                    'pt' => 'Interesse por tecnologias modernas', // Portugalski
                    'ro' => 'Interes pentru tehnologiile moderne', // Rumuński
                    'ru' => 'Интерес к современным технологиям', // Rosyjski
                    'si' => 'නවීන තාක්‍ෂණයට ඇති උනන්දුව', // Syngaleski
                    'sk' => 'Záujem o moderné technológie', // Słowacki
                    'sl' => 'Zanimanje za sodobne tehnologije', // Słoweński
                    'sq' => 'Interesi për teknologjitë moderne', // Albański
                    'sr' => 'Интересовање за савремене технологије', // Serbski
                    'sv' => 'Intresse för modern teknik', // Szwedzki
                    'tg' => 'Манфиат ба технологияҳои муосир', // Tadżycki
                    'th' => 'ความสนใจในเทคโนโลยีสมัยใหม่', // Tajski
                    'tk' => 'Häzirki zaman tehnologiýalaryna gyzyklanma', // Turkmeński
                    'tr' => 'Modern teknolojilere ilgi', // Turecki
                    'uk' => 'Інтерес до сучасних технологій', // Ukraiński
                    'uz' => 'Zamonaviy texnologiyalarga qiziqish', // Uzbecki
                    'vi' => 'Sự quan tâm đến công nghệ hiện đại', // Wietnamski
                    'zh' => '对现代技术的兴趣' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 7,
                'name' => json_encode([
                    'am' => 'በኢንዱስትሪ ውስጥ ወቅታዊ ዘይቤዎችን መረዳት', // Amharski
                    'ar' => 'معرفة الاتجاهات في الصناعة', // Arabski
                    'az' => 'Sənayedəki trendləri bilmək', // Azerski
                    'be' => 'Веданне трэндаў у галіны', // Białoruski
                    'bg' => 'Познанства с тенденциите в индустрията', // Bułgarski
                    'bn' => 'শিল্পের প্রবণতা সম্পর্কে জ্ঞান', // Bengalski
                    'bs' => 'Poznavanje trendova u industriji', // Bośniacki
                    'ca' => 'Coneixement de les tendències en la indústria', // Kataloński
                    'cs' => 'Znalost trendů v oboru', // Czeski
                    'da' => 'Kendskab til trends i branchen', // Duński
                    'de' => 'Kenntnis der Branchentrends', // Niemiecki
                    'dv' => 'އިންދަތަކަށްވަރު ޓްރެންޑުތައްނުވަތަކުރުންގެ ލިޔުންކޮށްފައިވާ', // Divehi
                    'dz' => 'མདོང་དུ་སྤེལ་གཞི་གཞིགས་ཐོན་རིམ་གཅིག་དགོས་པ།', // Dzongkha
                    'el' => 'Γνώση των τάσεων στη βιομηχανία', // Grecki
                    'en' => 'Knowledge of industry trends', // Angielski
                    'es' => 'Conocimiento de las tendencias de la industria', // Hiszpański
                    'et' => 'Tööstuse trendide tundmine', // Estoński
                    'fa' => 'آگاهی از روندهای صنعت', // Perski
                    'fi' => 'Alan trendien tuntemus', // Fiński
                    'fr' => 'Connaissance des tendances de l’industrie', // Francuski
                    'he' => 'ידע על מגמות בתעשייה', // Hebrajski
                    'hi' => 'उद्योग के रुझानों का ज्ञान', // Hindi
                    'hr' => 'Poznavanje trendova u industriji', // Chorwacki
                    'hu' => 'Az ipari trendek ismerete', // Węgierski
                    'hy' => 'Ոլորտի թրենդների իմացություն', // Ormiański
                    'id' => 'Pengetahuan tentang tren industri', // Indonezyjski
                    'is' => 'Þekking á þróun í greininni', // Islandzki
                    'it' => 'Conoscenza delle tendenze del settore', // Włoski
                    'ja' => '業界動向の知識', // Japoński
                    'ka' => 'ინდუსტრიული ტენდენციების ცოდნა', // Gruziński
                    'km' => 'ចំណេះដឹងអំពីនិន្នាការនៅក្នុងឧស្សាហកម្ម', // Khmerski
                    'ko' => '산업 동향에 대한 지식', // Koreański
                    'lb' => 'Wëssen iwwer Trends an der Industrie', // Luksemburski
                    'lo' => 'ຄວາມຮູ້ກ່ຽວກັບແນວໂນ້ມໃນອຸດສາຫະກໍາ', // Laotański
                    'lt' => 'Pramonės tendencijų išmanymas', // Litewski
                    'lv' => 'Zināšanas par nozares tendencēm', // Łotewski
                    'me' => 'Poznavanje trendova u industriji', // Czarnogórski
                    'mk' => 'Познавање на трендовите во индустријата', // Macedoński
                    'mn' => 'Үйлдвэрийн чиг хандлагын мэдлэг', // Mongołski
                    'ms' => 'Pengetahuan tentang trend dalam industri', // Malajski
                    'my' => 'စက်မှုလုပ်ငန်းတွင်လမ်းညွှန်မှုအတတ်ပညာ', // Birmański
                    'ne' => 'उद्योगका प्रवृत्तिहरूको ज्ञान', // Nepalski
                    'nl' => 'Kennis van trends in de industrie', // Holenderski
                    'no' => 'Kunnskap om trender i bransjen', // Norweski
                    'pl' => 'Znajomość trendów w branży', // Polski
                    'ps' => 'په صنعت کې د رجحانونو پوهه', // Paszto
                    'pt' => 'Conhecimento de tendências na indústria', // Portugalski
                    'ro' => 'Cunoașterea tendințelor din industrie', // Rumuński
                    'ru' => 'Знание тенденций в отрасли', // Rosyjski
                    'si' => 'කර්මාන්තයේ ප්‍රවණතා පිළිබඳ දැනුම', // Syngaleski
                    'sk' => 'Znalosť trendov v priemysle', // Słowacki
                    'sl' => 'Poznavanje trendov v industriji', // Słoweński
                    'sq' => 'Njohuri mbi tendencat në industri', // Albański
                    'sr' => 'Познавање трендова у индустрији', // Serbski
                    'sv' => 'Kunskap om trender i branschen', // Szwedzki
                    'tg' => 'Донистани тамоюлҳои соҳа', // Tadżycki
                    'th' => 'ความรู้เกี่ยวกับแนวโน้มในอุตสาหกรรม', // Tajski
                    'tk' => 'Senagat tendensiýalaryny bilmek', // Turkmeński
                    'tr' => 'Sektördeki trendler hakkında bilgi', // Turecki
                    'uk' => 'Знання трендів у галузі', // Ukraiński
                    'uz' => 'Sanoatdagi tendentsiyalarni bilish', // Uzbecki
                    'vi' => 'Kiến thức về xu hướng ngành', // Wietnamski
                    'zh' => '了解行业趋势' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 8,
                'name' => json_encode([
                    'pl' => 'Doświadczenie w pracy w zespołach międzynarodowych',
                    'en' => 'Experience working in international teams'
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 9,
                'name' => json_encode([
                    'am' => 'በዓለም አቀፍ ቡድኖች ውስጥ የሥራ ልምድ', // Amharski
                    'ar' => 'الخبرة في العمل في فرق دولية', // Arabski
                    'az' => 'Beynəlxalq qruplarda iş təcrübəsi', // Azerski
                    'be' => 'Вопыт працы ў міжнародных камандах', // Białoruski
                    'bg' => 'Опит в работа в международни екипи', // Bułgarski
                    'bn' => 'আন্তর্জাতিক দলগুলিতে কাজ করার অভিজ্ঞতা', // Bengalski
                    'bs' => 'Iskustvo u radu u međunarodnim timovima', // Bośniacki
                    'ca' => 'Experiència en treballar en equips internacionals', // Kataloński
                    'cs' => 'Zkušenosti s prací v mezinárodních týmech', // Czeski
                    'da' => 'Erfaring med at arbejde i internationale teams', // Duński
                    'de' => 'Erfahrung in der Arbeit in internationalen Teams', // Niemiecki
                    'dv' => 'އެންޑުސްޓްރީތަކުގައި އެންޑަރަޝަނަލް ޓީމުގައި ވަކިވަނީ', // Divehi
                    'dz' => 'ཕྱི་རྒྱལ་ལས་ཚོགས་དུ་ལས་བྱེད་མཁན་གྱི་མཛོད་པ།', // Dzongkha
                    'el' => 'Εμπειρία εργασίας σε διεθνείς ομάδες', // Grecki
                    'en' => 'Experience working in international teams', // Angielski
                    'es' => 'Experiencia trabajando en equipos internacionales', // Hiszpański
                    'et' => 'Kogemus töötamisel rahvusvahelistes meeskondades', // Estoński
                    'fa' => 'تجربه کار در تیم‌های بین‌المللی', // Perski
                    'fi' => 'Kokemus työskentelystä kansainvälisissä tiimeissä', // Fiński
                    'fr' => 'Expérience de travail dans des équipes internationales', // Francuski
                    'he' => 'ניסיון בעבודה בצוותים בינלאומיים', // Hebrajski
                    'hi' => 'अंतरराष्ट्रीय टीमों में काम करने का अनुभव', // Hindi
                    'hr' => 'Iskustvo u radu u međunarodnim timovima', // Chorwacki
                    'hu' => 'Tapasztalat nemzetközi csapatokban való munkában', // Węgierski
                    'hy' => 'Փորձ աշխատելու միջազգային թիմերում', // Ormiański
                    'id' => 'Pengalaman bekerja dalam tim internasional', // Indonezyjski
                    'is' => 'Reynsla af vinnu í alþjóðlegum teymum', // Islandzki
                    'it' => 'Esperienza di lavoro in team internazionali', // Włoski
                    'ja' => '国際チームでの勤務経験', // Japoński
                    'ka' => 'მუშაობის გამოცდილება საერთაშორისო გუნდებში', // Gruziński
                    'km' => 'បទពិសោធន៍ការងារនៅក្នុងក្រុមអន្តរជាតិ', // Khmerski
                    'ko' => '국제 팀에서의 근무 경험', // Koreański
                    'lb' => 'Erfarung an internationale Teams', // Luksemburski
                    'lo' => 'ປະສົບການໃນການເຮັດວຽກໃນທີມງານລະດັບສາກົນ', // Laotański
                    'lt' => 'Darbo patirtis tarptautinėse komandose', // Litewski
                    'lv' => 'Pieredze darbā starptautiskās komandās', // Łotewski
                    'me' => 'Iskustvo u radu u međunarodnim timovima', // Czarnogórski
                    'mk' => 'Искуство во работа во меѓународни тимови', // Macedoński
                    'mn' => 'Олон улсын багуудад ажилласан туршлага', // Mongołski
                    'ms' => 'Pengalaman bekerja dalam pasukan antarabangsa', // Malajski
                    'my' => 'အပြည်ပြည်ဆိုင်ရာအသင်းအဖွဲ့များတွင်လုပ်ကိုင်မှုအတွေ့အကြုံ', // Birmański
                    'ne' => 'अन्तर्राष्ट्रिय टोलीहरूमा काम गर्ने अनुभव', // Nepalski
                    'nl' => 'Ervaring met werken in internationale teams', // Holenderski
                    'no' => 'Erfaring med arbeid i internasjonale team', // Norweski
                    'pl' => 'Doświadczenie w pracy w zespołach międzynarodowych', // Polski
                    'ps' => 'په نړیوالو ټیمونو کې د کار کولو تجربه', // Paszto
                    'pt' => 'Experiência de trabalho em equipes internacionais', // Portugalski
                    'ro' => 'Experiență de lucru în echipe internaționale', // Rumuński
                    'ru' => 'Опыт работы в международных командах', // Rosyjski
                    'si' => 'ජාත්‍යන්තර කණ්ඩායම් සමඟ වැඩ කළ අත්දැකීම්', // Syngaleski
                    'sk' => 'Skúsenosti s prácou v medzinárodných tímoch', // Słowacki
                    'sl' => 'Izkušnje pri delu v mednarodnih timih', // Słoweński
                    'sq' => 'Përvoja në punë në ekipe ndërkombëtare', // Albański
                    'sr' => 'Искуство у раду у међународним тимовима', // Serbski
                    'sv' => 'Erfarenhet av att arbeta i internationella team', // Szwedzki
                    'tg' => 'Таҷрибаи кор дар гурӯҳҳои байналмилалӣ', // Tadżycki
                    'th' => 'ประสบการณ์การทำงานในทีมระหว่างประเทศ', // Tajski
                    'tk' => 'Halkara toparlarda iş tejribesi', // Turkmeński
                    'tr' => 'Uluslararası ekiplerde çalışma deneyimi', // Turecki
                    'uk' => 'Досвід роботи у міжнародних командах', // Ukraiński
                    'uz' => 'Xalqaro jamoalarda ishlash tajribasi', // Uzbecki
                    'vi' => 'Kinh nghiệm làm việc trong các nhóm quốc tế', // Wietnamski
                    'zh' => '在国际团队中的工作经验' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 10,
                'name' => json_encode([
                    'am' => 'በቡድን አስተዳደር የሥራ ልምድ', // Amharski
                    'ar' => 'الخبرة في إدارة الفريق', // Arabski
                    'az' => 'Komanda idarəetmə təcrübəsi', // Azerski
                    'be' => 'Вопыт кіравання камандай', // Białoruski
                    'bg' => 'Опит в управлението на екип', // Bułgarski
                    'bn' => 'দল ব্যবস্থাপনার অভিজ্ঞতা', // Bengalski
                    'bs' => 'Iskustvo u vođenju tima', // Bośniacki
                    'ca' => 'Experiència en la gestió d’equips', // Kataloński
                    'cs' => 'Zkušenosti s vedením týmu', // Czeski
                    'da' => 'Erfaring med teamledelse', // Duński
                    'de' => 'Erfahrung in der Teamleitung', // Niemiecki
                    'dv' => 'ޓީމުގެ މަނަކުން ހަދަނީކޮށް ވަކިވަނީ', // Divehi
                    'dz' => 'ཚོགས་སྡེ་གཏང་སྐྱོང་གི་མཛོད་པ།', // Dzongkha
                    'el' => 'Εμπειρία στη διαχείριση ομάδας', // Grecki
                    'en' => 'Experience in team management', // Angielski
                    'es' => 'Experiencia en la gestión de equipos', // Hiszpański
                    'et' => 'Kogemus meeskonna juhtimisel', // Estoński
                    'fa' => 'تجربه در مدیریت تیم', // Perski
                    'fi' => 'Kokemus tiimin johtamisesta', // Fiński
                    'fr' => 'Expérience en gestion d’équipe', // Francuski
                    'he' => 'ניסיון בניהול צוות', // Hebrajski
                    'hi' => 'टीम प्रबंधन में अनुभव', // Hindi
                    'hr' => 'Iskustvo u upravljanju timom', // Chorwacki
                    'hu' => 'Csapatvezetési tapasztalat', // Węgierski
                    'hy' => 'Փորձ թիմի կառավարման ոլորտում', // Ormiański
                    'id' => 'Pengalaman dalam manajemen tim', // Indonezyjski
                    'is' => 'Reynsla af teymisstjórnun', // Islandzki
                    'it' => 'Esperienza nella gestione di team', // Włoski
                    'ja' => 'チーム管理の経験', // Japoński
                    'ka' => 'ჯგუფის მართვის გამოცდილება', // Gruziński
                    'km' => 'បទពិសោធន៍ក្នុងការគ្រប់គ្រងក្រុម', // Khmerski
                    'ko' => '팀 관리 경험', // Koreański
                    'lb' => 'Erfarung an der Teamleitung', // Luksemburski
                    'lo' => 'ປະສົບການໃນການຄຸ້ມຄອງທີມ', // Laotański
                    'lt' => 'Patirtis vadovaujant komandai', // Litewski
                    'lv' => 'Pieredze komandas vadībā', // Łotewski
                    'me' => 'Iskustvo u vođenju tima', // Czarnogórski
                    'mk' => 'Искуство во управување со тим', // Macedoński
                    'mn' => 'Баг удирдах туршлага', // Mongołski
                    'ms' => 'Pengalaman dalam pengurusan pasukan', // Malajski
                    'my' => 'အသင်းအဖွဲ့စီမံခန့်ခွဲမှုအတွေ့အကြုံ', // Birmański
                    'ne' => 'टोली व्यवस्थापनमा अनुभव', // Nepalski
                    'nl' => 'Ervaring in teammanagement', // Holenderski
                    'no' => 'Erfaring med teamledelse', // Norweski
                    'pl' => 'Doświadczenie w zarządzaniu zespołem', // Polski
                    'ps' => 'په ټیم مدیریت کې تجربه', // Paszto
                    'pt' => 'Experiência em gestão de equipe', // Portugalski
                    'ro' => 'Experiență în managementul echipei', // Rumuński
                    'ru' => 'Опыт управления командой', // Rosyjski
                    'si' => 'කණ්ඩායම් කළමනාකරණයේ අත්දැකීම්', // Syngaleski
                    'sk' => 'Skúsenosti s riadením tímu', // Słowacki
                    'sl' => 'Izkušnje pri vodenju ekipe', // Słoweński
                    'sq' => 'Përvojë në menaxhimin e ekipit', // Albański
                    'sr' => 'Искуство у управљању тимом', // Serbski
                    'sv' => 'Erfarenhet av teamledning', // Szwedzki
                    'tg' => 'Таҷрибаи идоракунии гурӯҳ', // Tadżycki
                    'th' => 'ประสบการณ์ในการบริหารทีม', // Tajski
                    'tk' => 'Topar dolandyryş tejribesi', // Turkmeński
                    'tr' => 'Ekip yönetiminde deneyim', // Turecki
                    'uk' => 'Досвід управління командою', // Ukraiński
                    'uz' => 'Jamoani boshqarish tajribasi', // Uzbecki
                    'vi' => 'Kinh nghiệm quản lý nhóm', // Wietnamski
                    'zh' => '团队管理经验' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 11,
                'name' => json_encode([
                    'am' => 'በኢንዱስትሪ ክፍለ ጊዜ የሕግ ደንቦችን እውቀት', // Amharski
                    'ar' => 'معرفة اللوائح القانونية في مجال الصناعة', // Arabski
                    'az' => 'Sənaye ilə bağlı hüquqi qaydaları bilmək', // Azerski
                    'be' => 'Веданне прававых нормаў у галіне', // Białoruski
                    'bg' => 'Познанства с правните разпоредби в индустрията', // Bułgarski
                    'bn' => 'শিল্প সম্পর্কিত আইনগত বিধিগুলির জ্ঞান', // Bengalski
                    'bs' => 'Poznavanje pravnih propisa u industriji', // Bośniacki
                    'ca' => 'Coneixement de les normatives legals del sector', // Kataloński
                    'cs' => 'Znalost právních předpisů v oboru', // Czeski
                    'da' => 'Kendskab til lovgivningen inden for branchen', // Duński
                    'de' => 'Kenntnis der rechtlichen Vorschriften in der Branche', // Niemiecki
                    'dv' => 'އިންދަތަކަށް ތަޢާރަފުޅު ތަރީޚީގެ ލިޔުންކޮށްފައިވާ', // Divehi
                    'dz' => 'མི་ཚུགས་སྲིད་འཛིན་གཞི་རྟེན་གཞིགས་དགའ་ཞེན།', // Dzongkha
                    'el' => 'Γνώση των νομικών διατάξεων του κλάδου', // Grecki
                    'en' => 'Knowledge of legal regulations in the industry', // Angielski
                    'es' => 'Conocimiento de las normativas legales del sector', // Hiszpański
                    'et' => 'Tööstusharu õigusnormide tundmine', // Estoński
                    'fa' => 'آشنایی با مقررات قانونی در حوزه صنعت', // Perski
                    'fi' => 'Alan lakisääteisten määräysten tuntemus', // Fiński
                    'fr' => 'Connaissance des réglementations juridiques dans le secteur', // Francuski
                    'he' => 'ידע בתקנות משפטיות בתחום', // Hebrajski
                    'hi' => 'उद्योग के कानूनी नियमों का ज्ञान', // Hindi
                    'hr' => 'Poznavanje pravnih propisa u industriji', // Chorwacki
                    'hu' => 'Iparági jogszabályok ismerete', // Węgierski
                    'hy' => 'Ոլորտում իրավական նորմերի իմացություն', // Ormiański
                    'id' => 'Pengetahuan tentang peraturan hukum di industri', // Indonezyjski
                    'is' => 'Þekking á lagareglum í greininni', // Islandzki
                    'it' => 'Conoscenza delle normative legali nel settore', // Włoski
                    'ja' => '業界の法的規制に関する知識', // Japoński
                    'ka' => 'ინდუსტრიის სამართლებრივი რეგულაციების ცოდნა', // Gruziński
                    'km' => 'ចំណេះដឹងអំពីបទបញ្ជានីតិវិធីក្នុងឧស្សាហកម្ម', // Khmerski
                    'ko' => '산업 내 법적 규제에 대한 지식', // Koreański
                    'lb' => 'Wëssen iwwer juristesch Reglementer an der Industrie', // Luksemburski
                    'lo' => 'ຄວາມຮູ້ກ່ຽວກັບຂໍ້ກໍານົດດ້ານກົດໝາຍໃນອຸດສາຫະກໍາ', // Laotański
                    'lt' => 'Teisinių normų išmanymas pramonėje', // Litewski
                    'lv' => 'Zināšanas par nozares tiesiskajiem noteikumiem', // Łotewski
                    'me' => 'Poznavanje pravnih propisa u industriji', // Czarnogórski
                    'mk' => 'Познавање на правните прописи во индустријата', // Macedoński
                    'mn' => 'Үйлдвэрийн хууль эрх зүйн журам мэдэх', // Mongołski
                    'ms' => 'Pengetahuan tentang peraturan undang-undang dalam industri', // Malajski
                    'my' => 'စက်မှုလုပ်ငန်းနယ်ပယ်မှ ဥပဒေတရားများကို အသိပညာ', // Birmański
                    'ne' => 'उद्योगका कानूनी नियमहरूको ज्ञान', // Nepalski
                    'nl' => 'Kennis van juridische regelgeving in de industrie', // Holenderski
                    'no' => 'Kunnskap om juridiske forskrifter i bransjen', // Norweski
                    'pl' => 'Znajomość przepisów prawnych z zakresu branży', // Polski
                    'ps' => 'د صنعت قانوني مقرراتو پوهه', // Paszto
                    'pt' => 'Conhecimento das regulamentações legais na indústria', // Portugalski
                    'ro' => 'Cunoștințe despre reglementările legale în industrie', // Rumuński
                    'ru' => 'Знание правовых норм в отрасли', // Rosyjski
                    'si' => 'කර්මාන්තය සඳහා නීතිමය නියෝග පිළිබඳ දැනුම', // Syngaleski
                    'sk' => 'Znalosť právnych predpisov v odvetví', // Słowacki
                    'sl' => 'Poznavanje pravnih predpisov v industriji', // Słoweński
                    'sq' => 'Njohuri për rregulloret ligjore në industri', // Albański
                    'sr' => 'Познавање правних прописа у индустрији', // Serbski
                    'sv' => 'Kunskap om juridiska föreskrifter inom branschen', // Szwedzki
                    'tg' => 'Донистани қоидаҳои ҳуқуқӣ дар соҳа', // Tadżycki
                    'th' => 'ความรู้เกี่ยวกับข้อบังคับทางกฎหมายในอุตสาหกรรม', // Tajski
                    'tk' => 'Senagat boýunça hukuk düzgünlerini bilmek', // Turkmeński
                    'tr' => 'Sektördeki yasal düzenlemeler hakkında bilgi', // Turecki
                    'uk' => 'Знання правових норм у галузі', // Ukraiński
                    'uz' => 'Sanoatga oid huquqiy me\'yorlarni bilish', // Uzbecki
                    'vi' => 'Kiến thức về các quy định pháp lý trong ngành', // Wietnamski
                    'zh' => '了解行业的法律法规' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 12,
                'name' => json_encode([
                    'am' => 'በሪፖርት ውስጥ የሥራ ልምድ', // Amharski
                    'ar' => 'الخبرة في إعداد التقارير', // Arabski
                    'az' => 'Hesabat vermək təcrübəsi', // Azerski
                    'be' => 'Вопыт у справаздачнасці', // Białoruski
                    'bg' => 'Опит в съставянето на доклади', // Bułgarski
                    'bn' => 'রিপোর্টিংয়ে অভিজ্ঞতা', // Bengalski
                    'bs' => 'Iskustvo u izradi izvještaja', // Bośniacki
                    'ca' => 'Experiència en la preparació d’informes', // Kataloński
                    'cs' => 'Zkušenosti s vytvářením zpráv', // Czeski
                    'da' => 'Erfaring med rapportering', // Duński
                    'de' => 'Erfahrung im Berichtswesen', // Niemiecki
                    'dv' => 'ރިޕޯޓްކޮށްފައިވާ މާލަކުން ހަދަނީކޮށް ވަކިވަނީ', // Divehi
                    'dz' => 'དྲུང་ལུ་སྤྲིན་གྱི་མཛོད་པ།', // Dzongkha
                    'el' => 'Εμπειρία στην αναφορά', // Grecki
                    'en' => 'Experience in reporting', // Angielski
                    'es' => 'Experiencia en elaboración de informes', // Hiszpański
                    'et' => 'Kogemus aruandluses', // Estoński
                    'fa' => 'تجربه در گزارش‌دهی', // Perski
                    'fi' => 'Kokemus raportoinnista', // Fiński
                    'fr' => 'Expérience en reporting', // Francuski
                    'he' => 'ניסיון בדיווח', // Hebrajski
                    'hi' => 'रिपोर्टिंग में अनुभव', // Hindi
                    'hr' => 'Iskustvo u izvještavanju', // Chorwacki
                    'hu' => 'Tapasztalat jelentések készítésében', // Węgierski
                    'hy' => 'Փորձ հաշվետվությունների ներկայացման գործում', // Ormiański
                    'id' => 'Pengalaman dalam pelaporan', // Indonezyjski
                    'is' => 'Reynsla í skýrslugerð', // Islandzki
                    'it' => 'Esperienza nella reportistica', // Włoski
                    'ja' => '報告業務の経験', // Japoński
                    'ka' => 'ანგარიშგების გამოცდილება', // Gruziński
                    'km' => 'បទពិសោធន៍ក្នុងការរាយការណ៍', // Khmerski
                    'ko' => '보고 경험', // Koreański
                    'lb' => 'Erfarung am Berichterstattung', // Luksemburski
                    'lo' => 'ປະສົບການໃນການລາຍງານ', // Laotański
                    'lt' => 'Patirtis teikiant ataskaitas', // Litewski
                    'lv' => 'Pieredze ziņošanā', // Łotewski
                    'me' => 'Iskustvo u izvještavanju', // Czarnogórski
                    'mk' => 'Искуство во известување', // Macedoński
                    'mn' => 'Тайлан гаргах туршлага', // Mongołski
                    'ms' => 'Pengalaman dalam pelaporan', // Malajski
                    'my' => 'အစီရင်ခံမှုလုပ်ငန်းတွင်အတွေ့အကြုံ', // Birmański
                    'ne' => 'प्रतिवेदनमा अनुभव', // Nepalski
                    'nl' => 'Ervaring met rapportage', // Holenderski
                    'no' => 'Erfaring med rapportering', // Norweski
                    'pl' => 'Doświadczenie w raportowaniu', // Polski
                    'ps' => 'د راپور ورکولو تجربه', // Paszto
                    'pt' => 'Experiência em relatórios', // Portugalski
                    'ro' => 'Experiență în raportare', // Rumuński
                    'ru' => 'Опыт работы с отчетностью', // Rosyjski
                    'si' => 'වාර්තා සකස් කිරීමේ අත්දැකීම්', // Syngaleski
                    'sk' => 'Skúsenosti s reportovaním', // Słowacki
                    'sl' => 'Izkušnje z poročanjem', // Słoweński
                    'sq' => 'Përvojë në raportim', // Albański
                    'sr' => 'Искуство у извештавању', // Serbski
                    'sv' => 'Erfarenhet av rapportering', // Szwedzki
                    'tg' => 'Таҷрибаи гузоришдиҳӣ', // Tadżycki
                    'th' => 'ประสบการณ์ในการรายงาน', // Tajski
                    'tk' => 'Hasabat bermek tejribesi', // Turkmeński
                    'tr' => 'Raporlama deneyimi', // Turecki
                    'uk' => 'Досвід у звітності', // Ukraiński
                    'uz' => 'Hisobot berish tajribasi', // Uzbecki
                    'vi' => 'Kinh nghiệm báo cáo', // Wietnamski
                    'zh' => '报告经验' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 13,
                'name' => json_encode([
                    'am' => 'በተለያዩ ቦታዎች የስራ ጉዞ ለማድረግ ዝግጁነት', // Amharski
                    'ar' => 'الاستعداد للسفر في مهام عمل إلى مواقع مختلفة', // Arabski
                    'az' => 'Fərqli yerlərə işgüzar səfərlərə hazır olmaq', // Azerski
                    'be' => 'Гатоўнасць да службовых паездак у розныя месцы', // Białoruski
                    'bg' => 'Готовност за служебни пътувания до различни места', // Bułgarski
                    'bn' => 'বিভিন্ন স্থানে ব্যবসায়িক ভ্রমণে প্রস্তুতি', // Bengalski
                    'bs' => 'Spremnost na poslovna putovanja na različite lokacije', // Bośniacki
                    'ca' => 'Disponibilitat per a viatges de treball a diferents llocs', // Kataloński
                    'cs' => 'Připravenost na pracovní cesty na různá místa', // Czeski
                    'da' => 'Villighed til forretningsrejser til forskellige lokationer', // Duński
                    'de' => 'Bereitschaft zu Geschäftsreisen an verschiedene Standorte', // Niemiecki
                    'dv' => 'އައުދަމުގައި މަތިވެރި މަންޒަރުތައްގައި ބައިވަނީ', // Divehi
                    'dz' => 'གཞི་སྒྲིག་འབད་ཞིང་སྤྱིར་བཏང་བྱ་གཞི་གང་ལས་ཀྱི་འགྱོ་སྤར་འདེགས་སྒྲིག', // Dzongkha
                    'el' => 'Ετοιμότητα για επαγγελματικά ταξίδια σε διαφορετικές τοποθεσίες', // Grecki
                    'en' => 'Willingness to travel for business to various locations', // Angielski
                    'es' => 'Disponibilidad para viajar por trabajo a diferentes ubicaciones', // Hiszpański
                    'et' => 'Valmidus ärireisideks erinevatesse asukohtadesse', // Estoński
                    'fa' => 'آمادگی برای سفرهای کاری به مکان‌های مختلف', // Perski
                    'fi' => 'Valmius työmatkoihin eri paikkoihin', // Fiński
                    'fr' => 'Disponibilité pour des déplacements professionnels dans divers endroits', // Francuski
                    'he' => 'מוכנות לנסיעות עבודה במיקומים שונים', // Hebrajski
                    'hi' => 'विभिन्न स्थानों पर व्यावसायिक यात्राओं के लिए तत्परता', // Hindi
                    'hr' => 'Spremnost na službena putovanja na različite lokacije', // Chorwacki
                    'hu' => 'Készen áll üzleti utakra különböző helyszíneken', // Węgierski
                    'hy' => 'Պատրաստակամություն գործուղումների տարբեր վայրեր', // Ormiański
                    'id' => 'Kesediaan untuk perjalanan bisnis ke berbagai lokasi', // Indonezyjski
                    'is' => 'Vilji til að fara í viðskiptaferðir á mismunandi staði', // Islandzki
                    'it' => 'Disponibilità a viaggi di lavoro in diverse località', // Włoski
                    'ja' => 'さまざまな場所への出張への準備', // Japoński
                    'ka' => 'სხვადასხვა ადგილას საქმიანი მოგზაურობის მზადყოფნა', // Gruziński
                    'km' => 'ភាពរួសរាយក្នុងការធ្វើដំណើរការងារទៅទីតាំងផ្សេងៗ', // Khmerski
                    'ko' => '다양한 지역으로의 출장 준비', // Koreański
                    'lb' => 'Bereetschaft fir Geschäftsreesen op verschiddene Plazen', // Luksemburski
                    'lo' => 'ຄວາມພ້ອມທີ່ຈະດຳເນີນການທ່ອງທ່ຽວທຸລະກິດໄປສະຖານທີ່ຕ່າງໆ', // Laotański
                    'lt' => 'Pasirengimas darbo kelionėms į įvairias vietas', // Litewski
                    'lv' => 'Gatavība doties komandējumos uz dažādām vietām', // Łotewski
                    'me' => 'Spremnost za službena putovanja na različite lokacije', // Czarnogórski
                    'mk' => 'Подготвеност за службени патувања на различни локации', // Macedoński
                    'mn' => 'Өөр өөр байршилд ажлын айлчлал хийх бэлэн байдал', // Mongołski
                    'ms' => 'Kesediaan untuk perjalanan perniagaan ke pelbagai lokasi', // Malajski
                    'my' => 'အခြားတည်နေရာများသို့လုပ်ငန်းခရီးသွားရန်အဆင်သင့်ဖြစ်ခြင်း', // Birmański
                    'ne' => 'विभिन्न स्थानहरूमा व्यावसायिक यात्राको तयारी', // Nepalski
                    'nl' => 'Bereidheid om voor werk naar verschillende locaties te reizen', // Holenderski
                    'no' => 'Villighet til å reise i jobbsammenheng til forskjellige steder', // Norweski
                    'pl' => 'Gotowość do wyjazdów służbowych w różnych lokalizacjach', // Polski
                    'ps' => 'په مختلفو ځایونو کې د سوداګریز سفر لپاره چمتووالی', // Paszto
                    'pt' => 'Disponibilidade para viagens de trabalho a várias localizações', // Portugalski
                    'ro' => 'Disponibilitate pentru deplasări de serviciu în diferite locații', // Rumuński
                    'ru' => 'Готовность к командировкам в разные локации', // Rosyjski
                    'si' => 'විවිධ ස්ථානවලට සේවා මූලික සංචාර සඳහා සූදානම්', // Syngaleski
                    'sk' => 'Pripravenosť na služobné cesty na rôzne miesta', // Słowacki
                    'sl' => 'Pripravljenost na službena potovanja na različne lokacije', // Słoweński
                    'sq' => 'Gatishmëri për udhëtime pune në vende të ndryshme', // Albański
                    'sr' => 'Спремност за службена путовања на различите локације', // Serbski
                    'sv' => 'Beredd att resa i tjänsten till olika platser', // Szwedzki
                    'tg' => 'Тайёрӣ барои сафарҳои хизматӣ ба ҷойҳои гуногун', // Tadżycki
                    'th' => 'ความพร้อมสำหรับการเดินทางเพื่อธุรกิจในสถานที่ต่างๆ', // Tajski
                    'tk' => 'Dürli ýerlerde gulluk saparlaryna taýýarlyk', // Turkmeński
                    'tr' => 'Farklı lokasyonlara iş seyahatlerine hazır olma', // Turecki
                    'uk' => 'Готовність до відряджень у різні місця', // Ukraiński
                    'uz' => 'Turli joylarga xizmat safariga tayyorlik', // Uzbecki
                    'vi' => 'Sẵn sàng đi công tác tại các địa điểm khác nhau', // Wietnamski
                    'zh' => '愿意出差到不同地点' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 14,
                'name' => json_encode([
                    'am' => 'የገበያ እውቀት', // Amharski
                    'ar' => 'معرفة السوق', // Arabski
                    'az' => 'Bazar haqqında bilik', // Azerski
                    'be' => 'Веданне рынку', // Białoruski
                    'bg' => 'Познания за пазара', // Bułgarski
                    'bn' => 'বাজারের জ্ঞান', // Bengalski
                    'bs' => 'Poznavanje tržišta', // Bośniacki
                    'ca' => 'Coneixement del mercat', // Kataloński
                    'cs' => 'Znalost trhu', // Czeski
                    'da' => 'Kendskab til markedet', // Duński
                    'de' => 'Kenntnis des Marktes', // Niemiecki
                    'dv' => 'މާލޭގެ ދަނޑުގެ ހާލަތު', // Divehi
                    'dz' => 'དཔེ་དེབ་རྒྱབ་གྱི་མཛོད་པ།', // Dzongkha
                    'el' => 'Γνώση της αγοράς', // Grecki
                    'en' => 'Knowledge of the market', // Angielski
                    'es' => 'Conocimiento del mercado', // Hiszpański
                    'et' => 'Turuteadmised', // Estoński
                    'fa' => 'آگاهی از بازار', // Perski
                    'fi' => 'Markkinatuntemus', // Fiński
                    'fr' => 'Connaissance du marché', // Francuski
                    'he' => 'ידע על השוק', // Hebrajski
                    'hi' => 'बाजार का ज्ञान', // Hindi
                    'hr' => 'Poznavanje tržišta', // Chorwacki
                    'hu' => 'Piaci ismeretek', // Węgierski
                    'hy' => 'Շուկայի իմացություն', // Ormiański
                    'id' => 'Pengetahuan tentang pasar', // Indonezyjski
                    'is' => 'Þekking á markaðinum', // Islandzki
                    'it' => 'Conoscenza del mercato', // Włoski
                    'ja' => '市場の知識', // Japoński
                    'ka' => 'ბაზრის ცოდნა', // Gruziński
                    'km' => 'ចំណេះដឹងអំពីទីផ្សារ', // Khmerski
                    'ko' => '시장에 대한 지식', // Koreański
                    'lb' => 'Wëssen iwwer de Maart', // Luksemburski
                    'lo' => 'ຄວາມຮູ້ກ່ຽວກັບຕະຫຼາດ', // Laotański
                    'lt' => 'Rinkos išmanymas', // Litewski
                    'lv' => 'Tirgus zināšanas', // Łotewski
                    'me' => 'Poznavanje tržišta', // Czarnogórski
                    'mk' => 'Познавање на пазарот', // Macedoński
                    'mn' => 'Зах зээлийн мэдлэг', // Mongołski
                    'ms' => 'Pengetahuan tentang pasaran', // Malajski
                    'my' => 'ဈေးကွက်၏ အသိပညာ', // Birmański
                    'ne' => 'बजारको ज्ञान', // Nepalski
                    'nl' => 'Kennis van de markt', // Holenderski
                    'no' => 'Kunnskap om markedet', // Norweski
                    'pl' => 'Znajomość rynku', // Polski
                    'ps' => 'د بازار پوهه', // Paszto
                    'pt' => 'Conhecimento do mercado', // Portugalski
                    'ro' => 'Cunoașterea pieței', // Rumuński
                    'ru' => 'Знание рынка', // Rosyjski
                    'si' => 'වෙළඳපොළ පිළිබඳ දැනුම', // Syngaleski
                    'sk' => 'Znalosť trhu', // Słowacki
                    'sl' => 'Poznavanje trga', // Słoweński
                    'sq' => 'Njohuri për tregun', // Albański
                    'sr' => 'Познавање тржишта', // Serbski
                    'sv' => 'Kunskap om marknaden', // Szwedzki
                    'tg' => 'Донистани бозор', // Tadżycki
                    'th' => 'ความรู้เกี่ยวกับตลาด', // Tajski
                    'tk' => 'Bazar baradaky bilim', // Turkmeński
                    'tr' => 'Pazar bilgisi', // Turecki
                    'uk' => 'Знання ринку', // Ukraiński
                    'uz' => 'Bozor haqidagi bilim', // Uzbecki
                    'vi' => 'Kiến thức về thị trường', // Wietnamski
                    'zh' => '市场知识' // Chiński
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ]

        ];
        DB::table('welcomes')->insert($welcomes);
    }
}
