<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class WorkingModeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('working_modes')->truncate();

        $modes = [
            [
                'id' => 1,
                'title' => json_encode([
                    'pl' => 'Stacjonarny',
                    'en' => 'Stationary',
                    'am' => 'ቆይታ',
                    'ar' => 'ثابت',
                    'az' => 'Stasionar',
                    'be' => 'стацыянарны',
                    'bg' => 'Стационарен',
                    'bn' => 'স্থির',
                    'bs' => 'Stacionarni',
                    'ca' => 'Estacionari',
                    'cs' => 'Stacionární',
                    'da' => 'Stationær',
                    'de' => 'Stationär',
                    'dv' => 'ހާއިރު',
                    'dz' => 'འགྱུར་མི་',
                    'el' => 'Σταθερός',
                    'es' => 'Estacionario',
                    'et' => 'Statsionaarne',
                    'fa' => 'ثابت',
                    'fi' => 'Kiinteä',
                    'fr' => 'Stationnaire',
                    'he' => 'נייח',
                    'hi' => 'स्थिर',
                    'hr' => 'Stacionaran',
                    'hu' => 'Állandó',
                    'hy' => 'Ստացիոնար',
                    'id' => 'Stasioner',
                    'is' => 'Stöðugur',
                    'it' => 'Stazionario',
                    'ja' => '定常',
                    'ka' => 'სტაციონარული',
                    'km' => 'ឥតផ្លាស់ទី',
                    'ko' => '정적',
                    'lb' => 'Stationär',
                    'lo' => 'ສະຖິຕິ',
                    'lt' => 'Stacionarus',
                    'lv' => 'Stacionārs',
                    'me' => 'Stacionarni',
                    'mk' => 'Стационарен',
                    'mn' => 'Тогтвортой',
                    'ms' => 'Pepejal',
                    'my' => 'တည်နေရာ',
                    'ne' => 'स्थिर',
                    'nl' => 'Stationair',
                    'no' => 'Stasjonær',
                    'ps' => 'ثابت',
                    'pt' => 'Estacionário',
                    'ro' => 'Staționar',
                    'ru' => 'Стационарный',
                    'si' => 'ස්ථාවර',
                    'sk' => 'Stacionárny',
                    'sl' => 'Stacionarni',
                    'sq' => 'Stacionar',
                    'sr' => 'Стационарни',
                    'sv' => 'Stationär',
                    'tg' => 'Стационарӣ',
                    'th' => 'อยู่กับที่',
                    'tk' => 'Stasionar',
                    'tr' => 'Sabit',
                    'uk' => 'Стаціонарний',
                    'uz' => 'Statsionar',
                    'vi' => 'Cố định',
                    'zh' => '静止的'
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 2,
                'title' => json_encode([
                    'pl' => 'Zdalny',
                    'en' => 'Remote',
                    'am' => 'ሩቅ',
                    'ar' => 'عن بُعد',
                    'az' => 'Uzaq',
                    'be' => 'дыстанцыйны',
                    'bg' => 'Дистанционен',
                    'bn' => 'দূরবর্তী',
                    'bs' => 'Daljinski',
                    'ca' => 'Remot',
                    'cs' => 'Vzdálený',
                    'da' => 'Fjern',
                    'de' => 'Remote',
                    'dv' => 'ދަނޑުކޮށް',
                    'dz' => 'གནང་ཡོད་པ',
                    'el' => 'Απομακρυσμένος',
                    'es' => 'Remoto',
                    'et' => 'Kaugjuhtimine',
                    'fa' => 'راه دور',
                    'fi' => 'Etä',
                    'fr' => 'À distance',
                    'he' => 'מרוחק',
                    'hi' => 'दूरस्थ',
                    'hr' => 'Udaljeni',
                    'hu' => 'Távoli',
                    'hy' => 'Հեռավոր',
                    'id' => 'Jarak jauh',
                    'is' => 'Fjarstýring',
                    'it' => 'Remoto',
                    'ja' => 'リモート',
                    'ka' => 'დისტანციური',
                    'km' => 'ចម្ងាយ',
                    'ko' => '원격',
                    'lb' => 'Remote',
                    'lo' => 'ໄລຍະ',
                    'lt' => 'Nuotolinis',
                    'lv' => 'Attālināts',
                    'me' => 'Daljinski',
                    'mk' => 'Далечен',
                    'mn' => 'Холын',
                    'ms' => 'Jauh',
                    'my' => 'ဝေးလံ',
                    'ne' => 'दूरस्थ',
                    'nl' => 'Afstandsbediening',
                    'no' => 'Fjernstyrt',
                    'ps' => 'لرې',
                    'pt' => 'Remoto',
                    'ro' => 'La distanță',
                    'ru' => 'Удалённый',
                    'si' => 'දුරස්ථ',
                    'sk' => 'Vzdialený',
                    'sl' => 'Oddaljeno',
                    'sq' => 'I largët',
                    'sr' => 'Даљински',
                    'sv' => 'Fjärr',
                    'tg' => 'Дурдаст',
                    'th' => 'ระยะไกล',
                    'tk' => 'Uzakdan',
                    'tr' => 'Uzaktan',
                    'uk' => 'Дистанційний',
                    'uz' => 'Uzoq',
                    'vi' => 'Từ xa',
                    'zh' => '远程'
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 3,
                'title' => json_encode([
                    'pl' => 'Hybrydowy',
                    'en' => 'Hybrid',
                    'am' => 'ቀጥታ ተዋሕዶ',
                    'ar' => 'هجين',
                    'az' => 'Hibrid',
                    'be' => 'гібрыдны',
                    'bg' => 'Хибриден',
                    'bn' => 'হাইব্রিড',
                    'bs' => 'Hibrid',
                    'ca' => 'Híbrid',
                    'cs' => 'Hybridní',
                    'da' => 'Hybrid',
                    'de' => 'Hybrid',
                    'dv' => 'ހިބްރީޑު',
                    'dz' => 'གནས་རྒྱུས',
                    'el' => 'Υβριδικός',
                    'es' => 'Híbrido',
                    'et' => 'Hübriidne',
                    'fa' => 'هیبریدی',
                    'fi' => 'Hybridi',
                    'fr' => 'Hybride',
                    'he' => 'היברידי',
                    'hi' => 'हाइब्रिड',
                    'hr' => 'Hibridni',
                    'hu' => 'Hibrid',
                    'hy' => 'Հիբրիդային',
                    'id' => 'Hibrida',
                    'is' => 'Blendinn',
                    'it' => 'Ibrido',
                    'ja' => 'ハイブリッド',
                    'ka' => 'ჰიბრიდული',
                    'km' => 'ហាយប្រីត',
                    'ko' => '하이브리드',
                    'lb' => 'Hybrid',
                    'lo' => 'ສົມສານ',
                    'lt' => 'Hibridinis',
                    'lv' => 'Hibrīds',
                    'me' => 'Hibrid',
                    'mk' => 'Хибриден',
                    'mn' => 'Гибрид',
                    'ms' => 'Hibrid',
                    'my' => 'ဖျက်စပ်',
                    'ne' => 'हाइब्रिड',
                    'nl' => 'Hybride',
                    'no' => 'Hybrid',
                    'ps' => 'هایبرډ',
                    'pt' => 'Híbrido',
                    'ro' => 'Hibrid',
                    'ru' => 'Гибридный',
                    'si' => 'සංයුක්ත',
                    'sk' => 'Hybridný',
                    'sl' => 'Hibridni',
                    'sq' => 'Hibrid',
                    'sr' => 'Хибридни',
                    'sv' => 'Hybrid',
                    'tg' => 'Ҳибрид',
                    'th' => 'ไฮบริด',
                    'tk' => 'Gibrid',
                    'tr' => 'Hibrit',
                    'uk' => 'Гібридний',
                    'uz' => 'Gibrid',
                    'vi' => 'Lai',
                    'zh' => '混合的'
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 4,
                'title' => json_encode([
                    'pl' => 'Mobilny',
                    'en' => 'Mobile',
                    'am' => 'ተንቀሳቃሽ',
                    'ar' => 'متحرك',
                    'az' => 'Mobil',
                    'be' => 'мабільны',
                    'bg' => 'Мобилен',
                    'bn' => 'মোবাইল',
                    'bs' => 'Mobilni',
                    'ca' => 'Mòbil',
                    'cs' => 'Mobilní',
                    'da' => 'Mobil',
                    'de' => 'Mobil',
                    'dv' => 'މޮބައިލް',
                    'dz' => 'རྩོམ་སྒྲིག',
                    'el' => 'Φορητός',
                    'es' => 'Móvil',
                    'et' => 'Mobiilne',
                    'fa' => 'سیار',
                    'fi' => 'Mobiili',
                    'fr' => 'Mobile',
                    'he' => 'נייד',
                    'hi' => 'मोबाइल',
                    'hr' => 'Mobilni',
                    'hu' => 'Mobil',
                    'hy' => 'Շարժական',
                    'id' => 'Seluler',
                    'is' => 'Farsími',
                    'it' => 'Mobile',
                    'ja' => 'モバイル',
                    'ka' => 'მობილური',
                    'km' => 'ចល័ត',
                    'ko' => '모바일',
                    'lb' => 'Mobil',
                    'lo' => 'ໂທລະສັບມືຖື',
                    'lt' => 'Mobilus',
                    'lv' => 'Mobilais',
                    'me' => 'Mobilni',
                    'mk' => 'Мобилен',
                    'mn' => 'Гар утас',
                    'ms' => 'Mudah alih',
                    'my' => 'မိုဘိုင်း',
                    'ne' => 'मोबाइल',
                    'nl' => 'Mobiel',
                    'no' => 'Mobil',
                    'ps' => 'موبايل',
                    'pt' => 'Móvel',
                    'ro' => 'Mobil',
                    'ru' => 'Мобильный',
                    'si' => 'ජංගම',
                    'sk' => 'Mobilný',
                    'sl' => 'Mobilni',
                    'sq' => 'I lëvizshëm',
                    'sr' => 'Мобилни',
                    'sv' => 'Mobil',
                    'tg' => 'Мобилӣ',
                    'th' => 'เคลื่อนที่',
                    'tk' => 'Göçme',
                    'tr' => 'Mobil',
                    'uk' => 'Мобільний',
                    'uz' => 'Mobil',
                    'vi' => 'Di động',
                    'zh' => '移动的'
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ]
        ];
        DB::table('working_modes')->insert($modes);
    }
}
