<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class WorkingPlaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('working_places')->truncate();

        $places = [
            [
                'id' => 1,
                'name' => json_encode([
                    'pl' => 'Szkoła',
                    'en' => 'School',
                    'am' => 'ትምህርት ቤት',
                    'ar' => 'مدرسة',
                    'az' => 'Məktəb',
                    'be' => 'школа',
                    'bg' => 'Училище',
                    'bn' => 'স্কুল',
                    'bs' => 'Škola',
                    'ca' => 'Escola',
                    'cs' => 'Škola',
                    'da' => 'Skole',
                    'de' => 'Schule',
                    'dv' => 'ސުކުލް',
                    'dz' => 'སློབ་གྲྭ',
                    'el' => 'Σχολείο',
                    'es' => 'Escuela',
                    'et' => 'Kool',
                    'fa' => 'مدرسه',
                    'fi' => 'Koulu',
                    'fr' => 'École',
                    'he' => 'בית ספר',
                    'hi' => 'विद्यालय',
                    'hr' => 'Škola',
                    'hu' => 'Iskola',
                    'hy' => 'Դպրոց',
                    'id' => 'Sekolah',
                    'is' => 'Skóli',
                    'it' => 'Scuola',
                    'ja' => '学校',
                    'ka' => 'სკოლა',
                    'km' => 'សាលារៀន',
                    'ko' => '학교',
                    'lb' => 'Schoul',
                    'lo' => 'ສະຖາບັນການສຶກສາ',
                    'lt' => 'Mokykla',
                    'lv' => 'Skola',
                    'me' => 'Škola',
                    'mk' => 'Училиште',
                    'mn' => 'Сургууль',
                    'ms' => 'Sekolah',
                    'my' => 'ကျောင်း',
                    'ne' => 'विद्यालय',
                    'nl' => 'School',
                    'no' => 'Skole',
                    'ps' => 'ښوونځی',
                    'pt' => 'Escola',
                    'ro' => 'Școală',
                    'ru' => 'Школа',
                    'si' => 'පාසල',
                    'sk' => 'Škola',
                    'sl' => 'Šola',
                    'sq' => 'Shkollë',
                    'sr' => 'Школа',
                    'sv' => 'Skola',
                    'tg' => 'Мактаб',
                    'th' => 'โรงเรียน',
                    'tk' => 'Mekdep',
                    'tr' => 'Okul',
                    'uk' => 'Школа',
                    'uz' => 'Maktab',
                    'vi' => 'Trường học',
                    'zh' => '学校'
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 2,
                'name' => json_encode([
                    'pl' => 'Szpital',
                    'en' => 'Hospital',
                    'am' => 'ሆስፒታል',
                    'ar' => 'مستشفى',
                    'az' => 'Xəstəxana',
                    'be' => 'бальніца',
                    'bg' => 'Болница',
                    'bn' => 'হাসপাতাল',
                    'bs' => 'Bolnica',
                    'ca' => 'Hospital',
                    'cs' => 'Nemocnice',
                    'da' => 'Hospital',
                    'de' => 'Krankenhaus',
                    'dv' => 'ހޮސްޕިޓަލް',
                    'dz' => 'ཨོམ་ནང་ནས་',
                    'el' => 'Νοσοκομείο',
                    'es' => 'Hospital',
                    'et' => 'Haigla',
                    'fa' => 'بیمارستان',
                    'fi' => 'Sairaala',
                    'fr' => 'Hôpital',
                    'he' => 'בית חולים',
                    'hi' => 'अस्पताल',
                    'hr' => 'Bolnica',
                    'hu' => 'Kórház',
                    'hy' => 'Հիվանդանոց',
                    'id' => 'Rumah Sakit',
                    'is' => 'Spítali',
                    'it' => 'Ospedale',
                    'ja' => '病院',
                    'ka' => 'საავადმყოფო',
                    'km' => 'មន្ទីរពេទ្យ',
                    'ko' => '병원',
                    'lb' => 'Spidol',
                    'lo' => 'ໂຮງໝໍ',
                    'lt' => 'Ligoninė',
                    'lv' => 'Slimnīca',
                    'me' => 'Bolnica',
                    'mk' => 'Болница',
                    'mn' => 'Эмнэлэг',
                    'ms' => 'Hospital',
                    'my' => 'ဆေးရုံ',
                    'ne' => 'अस्पताल',
                    'nl' => 'Ziekenhuis',
                    'no' => 'Sykehus',
                    'ps' => 'روغتون',
                    'pt' => 'Hospital',
                    'ro' => 'Spital',
                    'ru' => 'Больница',
                    'si' => 'රෝහල',
                    'sk' => 'Nemocnica',
                    'sl' => 'Bolnišnica',
                    'sq' => 'Spital',
                    'sr' => 'Болница',
                    'sv' => 'Sjukhus',
                    'tg' => 'Беморхона',
                    'th' => 'โรงพยาบาล',
                    'tk' => 'Hassahan',
                    'tr' => 'Hastane',
                    'uk' => 'Лікарня',
                    'uz' => 'Shifoxona',
                    'vi' => 'Bệnh viện',
                    'zh' => '医院'
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 3,
                'name' => json_encode([
                    'pl' => 'Biuro',
                    'en' => 'Office',
                    'am' => 'ቢሮ',
                    'ar' => 'مكتب',
                    'az' => 'Ofis',
                    'be' => 'офіс',
                    'bg' => 'Офис',
                    'bn' => 'অফিস',
                    'bs' => 'Ured',
                    'ca' => 'Oficina',
                    'cs' => 'Kancelář',
                    'da' => 'Kontor',
                    'de' => 'Büro',
                    'dv' => 'އޮފިސް',
                    'dz' => 'གཞུང་ལས་ཁུངས་',
                    'el' => 'Γραφείο',
                    'es' => 'Oficina',
                    'et' => 'Kontor',
                    'fa' => 'دفتر',
                    'fi' => 'Toimisto',
                    'fr' => 'Bureau',
                    'he' => 'משרד',
                    'hi' => 'कार्यालय',
                    'hr' => 'Ured',
                    'hu' => 'Iroda',
                    'hy' => 'Գրասենյակ',
                    'id' => 'Kantor',
                    'is' => 'Skrifstofa',
                    'it' => 'Ufficio',
                    'ja' => '事務所',
                    'ka' => 'ოფისი',
                    'km' => 'ការិយាល័យ',
                    'ko' => '사무실',
                    'lb' => 'Büro',
                    'lo' => 'ຫ້ອງການ',
                    'lt' => 'Biuras',
                    'lv' => 'Birojs',
                    'me' => 'Kancelarija',
                    'mk' => 'Канцеларија',
                    'mn' => 'Оффис',
                    'ms' => 'Pejabat',
                    'my' => 'ရုံး',
                    'ne' => 'कार्यालय',
                    'nl' => 'Kantoor',
                    'no' => 'Kontor',
                    'ps' => 'دفتر',
                    'pt' => 'Escritório',
                    'ro' => 'Birou',
                    'ru' => 'Офис',
                    'si' => 'කාර්යාලය',
                    'sk' => 'Kancelária',
                    'sl' => 'Pisarna',
                    'sq' => 'Zyrë',
                    'sr' => 'Канцеларија',
                    'sv' => 'Kontor',
                    'tg' => 'Идора',
                    'th' => 'สำนักงาน',
                    'tk' => 'Ofis',
                    'tr' => 'Ofis',
                    'uk' => 'Офіс',
                    'uz' => 'Idora',
                    'vi' => 'Văn phòng',
                    'zh' => '办公室'
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 4,
                'name' => json_encode([
                    'pl' => 'Firma',
                    'en' => 'Company',
                    'am' => 'ኩባንያ',
                    'ar' => 'شركة',
                    'az' => 'Şirkət',
                    'be' => 'кампанія',
                    'bg' => 'Компания',
                    'bn' => 'প্রতিষ্ঠান',
                    'bs' => 'Kompanija',
                    'ca' => 'Empresa',
                    'cs' => 'Společnost',
                    'da' => 'Virksomhed',
                    'de' => 'Unternehmen',
                    'dv' => 'ސާނަމު',
                    'dz' => 'དང་སྲུང་པོ',
                    'el' => 'Εταιρεία',
                    'es' => 'Empresa',
                    'et' => 'Ettevõte',
                    'fa' => 'شرکت',
                    'fi' => 'Yritys',
                    'fr' => 'Entreprise',
                    'he' => 'חֶברָה',
                    'hi' => 'कंपनी',
                    'hr' => 'Kompanija',
                    'hu' => 'Cég',
                    'hy' => 'Ընկերություն',
                    'id' => 'Perusahaan',
                    'is' => 'Fyrirtæki',
                    'it' => 'Azienda',
                    'ja' => '会社',
                    'ka' => 'კომპანია',
                    'km' => 'ក្រុមហ៊ុន',
                    'ko' => '회사',
                    'lb' => 'Firma',
                    'lo' => 'ບໍລິສັດ',
                    'lt' => 'Įmonė',
                    'lv' => 'Uzņēmums',
                    'me' => 'Firma',
                    'mk' => 'Компанија',
                    'mn' => 'Компани',
                    'ms' => 'Syarikat',
                    'my' => 'ကုမ္ပဏီ',
                    'ne' => 'कम्पनी',
                    'nl' => 'Bedrijf',
                    'no' => 'Selskap',
                    'ps' => 'شرکت',
                    'pt' => 'Empresa',
                    'ro' => 'Companie',
                    'ru' => 'Компания',
                    'si' => 'සමාගම',
                    'sk' => 'Spoločnosť',
                    'sl' => 'Podjetje',
                    'sq' => 'Kompani',
                    'sr' => 'Фирма',
                    'sv' => 'Företag',
                    'tg' => 'Ширкат',
                    'th' => 'บริษัท',
                    'tk' => 'Kompaniýa',
                    'tr' => 'Şirket',
                    'uk' => 'Компанія',
                    'uz' => 'Kompaniya',
                    'vi' => 'Công ty',
                    'zh' => '公司'
                ]),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ]
        ];
        DB::table('working_places')->insert($places);
    }
}
