<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8"/>
    <title>{{ config('app.name', 'Work') }}</title>
    <style>
        @page {
            margin: 0;
            padding: 0;
        }

        @font-face {
            font-family: 'Montserrat';
            src: url('{{ storage_path("fonts/Montserrat/Montserrat-Regular.ttf") }}');
            font-weight: normal;
            font-style: normal;
        }

        @font-face {
            font-family: 'Montserrat';
            src: url('{{ storage_path("fonts/Montserrat/Montserrat-SemiBold.ttf") }}') format('truetype');
            font-weight: bold;
            font-style: normal;
        }

        body {
            font-family: "Montserrat", sans-serif !important;
            margin: 0;
            padding: 0;
        }

        .header {
            text-align: center;
            position: relative;
            padding-top: 80px;
        }

        .profile-pic {
            width: 200px;
            height: 200px;
            border-radius: 50%;
            margin: 0 auto;
            overflow: hidden;
            position: relative;
            z-index: 2;
            border: 20px solid white;
        }

        .profile-pic img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .bar {
            background: #e4ebec;
            height: 200px;
            width: 100%;
            position: absolute;
            top: 180px;
            z-index: 1;
        }

        .name-section {
            text-align: center;
            padding: 20px 0;
            position: relative;
            z-index: 3;
        }

        .name-section h1 {
            margin: 0;
            font-size: 32px;
            color: #333;
        }

        .content {
            display: flex;
            padding: 20px 40px;
        }

        .column {
            flex: 1;
            padding: 0 20px;
        }

        .left-column, .right-column {
            width: 50%;
        }

        .section {
            margin-bottom: 30px;
        }

        .section h2 {
            color: #2176FF;
            border-bottom: 2px solid #2176FF;
            padding-bottom: 5px;
            margin-bottom: 15px;
        }

        .section ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        .section ul li {
            margin-bottom: 10px;
        }

        .footer {
            position: absolute;
            top: 20px;
            left: 20px;
            display: flex;
            align-items: center;
            opacity: 0.5;
        }

        .footer span {
            margin-right: 5px;
        }

        .footer img {
            height: 40px;
            vertical-align: middle;
        }
    </style>
</head>
<body>
<div class="footer">
    <span>generated by</span>
    <img src="{{public_path('storage/cv/1/icons/logo.png')}}" alt="logo">
</div>

<div class="header">
    <div class="bar"></div>
    <div class="profile-pic">
        <img src="{{public_path('/images/cv/cvplace.png')}}" alt="Profile Photo">
    </div>
</div>

<div class="name-section">
    <h1>Donna Stroupe</h1>
</div>

<div class="content">
    <div class="column left-column">
        <div class="section">
            <h2>{{__('CvExp')}}</h2>
            <ul>
                <li>
                    <strong>Kierownik sprzedaży</strong><br>
                    Timermann Industries \ Warszawa 2025
                </li>
                <li>
                    <strong>Kierownik sprzedaży</strong><br>
                    Timermann Industries \ Warszawa 2025
                </li>
                <li>
                    <strong>Kierownik sprzedaży</strong><br>
                    Timermann Industries \ Warszawa 2025
                </li>
            </ul>
        </div>

        <div class="section">
            <h2>{{__('CvDo')}}</h2>
            <ul>
                <li>sdsadassd</li>
                <li>sdsadassd</li>
                <li>sdsadassd</li>
                <li>sdsadassd</li>
            </ul>
        </div>
    </div>

    <div class="column right-column">
        <div class="section">
            <h2>{{__('CvSchool')}}</h2>
            <ul>
                <li>
                    <strong>BA SALES Katowice</strong><br>
                    magisterskie ukończono w 2011
                </li>
                <li>
                    <strong>BA SALES Katowice</strong><br>
                    magisterskie ukończono w 2011
                </li>
                <li>
                    <strong>BA SALES Katowice</strong><br>
                    magisterskie ukończono w 2011
                </li>
            </ul>
        </div>

        <div class="section">
            <h2>{{__('CvLangs')}}</h2>
            <ul>
                <li><strong>J. Angielski</strong> - B1 podstawowy</li>
                <li><strong>J. Niemiecki</strong> - A2 podstawowy</li>
                <li><strong>J. Francuski</strong> - A1 podstawowy</li>
            </ul>
        </div>
    </div>
</div>
</body>
</html>
