<?php
return [
    ["name" => "USD", "code" => "Dolar amerykański", "value" => "$"],
    ["name" => "EUR", "code" => "Euro", "value" => "€"],
    ["name" => "GBP", "code" => "Funt szterling", "value" => "£"],
    ["name" => "JPY", "code" => "Jen japoński", "value" => "¥"],
    ["name" => "CHF", "code" => "Frank szwajcarski", "value" => "CHF"],
    ["name" => "CAD", "code" => "Dolar kanadyjski", "value" => "$"],
    ["name" => "AUD", "code" => "Dolar australijski", "value" => "$"],
    ["name" => "NZD", "code" => "Dolar nowozelandzki", "value" => "$"],
    ["name" => "CNY", "code" => "Juan chiński", "value" => "¥"],
    ["name" => "SEK", "code" => "Korona szwedzka", "value" => "kr"],
    ["name" => "NOK", "code" => "Korona norweska", "value" => "kr"],
    ["name" => "DKK", "code" => "Korona duńska", "value" => "kr"],
    ["name" => "INR", "code" => "Rupia indyjska", "value" => "₹"],
    ["name" => "RUB", "code" => "Rubel rosyjski", "value" => "₽"],
    ["name" => "MXN", "code" => "Peso meksykańskie", "value" => "$"],
    ["name" => "BRL", "code" => "Real brazylijski", "value" => "R$"],
    ["name" => "ZAR", "code" => "Rand południowoafrykański", "value" => "R"],
    ["name" => "TRY", "code" => "Lira turecka", "value" => "₺"],
    ["name" => "KRW", "code" => "Won południowokoreański", "value" => "₩"],
    ["name" => "PHP", "code" => "Peso filipińskie", "value" => "₱"],
    ["name" => "SGD", "code" => "Dolar singapurski", "value" => "$"],
    ["name" => "HKD", "code" => "Dolar hongkoński", "value" => "$"],
    ["name" => "THB", "code" => "Baht tajski", "value" => "฿"],
    ["name" => "MYR", "code" => "Ringgit malezyjski", "value" => "RM"],
    ["name" => "IDR", "code" => "Rupia indonezyjska", "value" => "Rp"],
    ["name" => "VND", "code" => "Dong wietnamski", "value" => "₫"],
    ["name" => "PLN", "code" => "Złoty polski", "value" => "zł"],
    ["name" => "CZK", "code" => "Korona czeska", "value" => "Kč"],
    ["name" => "HUF", "code" => "Forint węgierski", "value" => "Ft"],
    ["name" => "RON", "code" => "Lej rumuński", "value" => "lei"],
    ["name" => "BGN", "code" => "Lew bułgarski", "value" => "лв"],
    ["name" => "HRK", "code" => "Kuna chorwacka", "value" => "kn"],
    ["name" => "ISK", "code" => "Korona islandzka", "value" => "kr"],
    ["name" => "ARS", "code" => "Peso argentyńskie", "value" => "$"],
    ["name" => "CLP", "code" => "Peso chilijskie", "value" => "$"],
    ["name" => "COP", "code" => "Peso kolumbijskie", "value" => "$"],
    ["name" => "PEN", "code" => "Sol peruwiański", "value" => "S"],
    ["name" => "EGP", "code" => "Funt egipski", "value" => "£"],
    ["name" => "SAR", "code" => "Rial saudyjski", "value" => "﷼"],
    ["name" => "AED", "code" => "Dirham ZEA", "value" => "د.إ"],
    ["name" => "IQD", "code" => "Dinar iracki", "value" => "ع.د"],
    ["name" => "IRR", "code" => "Rial irański", "value" => "﷼"],
    ["name" => "QAR", "code" => "Rial katarski", "value" => "﷼"],
    ["name" => "KWD", "code" => "Dinar kuwejcki", "value" => "د.ك"],
    ["name" => "OMR", "code" => "Rial omański", "value" => "﷼"],
    ["name" => "BHD", "code" => "Dinar bahrański", "value" => ".د.ب"],
    ["name" => "LKR", "code" => "Rupia lankijska", "value" => "Rs"],
    ["name" => "BDT", "code" => "Taka bangladeska", "value" => "৳"],
    ["name" => "PKR", "code" => "Rupia pakistańska", "value" => "₨"],
    ["name" => "XAF", "code" => "Frank CFA (BEAC)", "value" => "FCFA"],
    ["name" => "XOF", "code" => "Frank CFA (BCEAO)", "value" => "CFA"],
    ["name" => "XCD", "code" => "Dolar wschodniokaraibski", "value" => "$"],
];
